(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"HP_notdone_320x50_atlas_1", frames: [[0,0,600,500]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib._300x250_bkgd = function() {
	this.initialize(ss["HP_notdone_320x50_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.HealthPointLogoai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HealthPointLogo.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#858E23").s().p("AhuDsQgKgGAUgwQATgvAYggQA5hOARg9QAJgggPgpQgIgXgZgtQgeg2BDgEQAZgCAaAGQAZAFACAHIACADQAYA5gFBDQgFBAgdA6QgQAfgdAlQgRAWgiApQgdAkgTARQgZAXgQAAIgFgBg");
	this.shape.setTransform(47.9903,36.3577);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#91190E").s().p("AggBTQgbgdgZgnQgdgugCgeQgDgrAvAGQAVACBCAZQAVAHASgMQATgLAMADQAFACAFAEQAbARgJAoQgJAhgcAkQgaAigZAMQgNAGgLAAQgSAAgQgRg");
	this.shape_1.setTransform(32.4896,28.7262);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F17C29").s().p("AhADzQgmgcgWheQgShLAEhJQAGhXAkg5QAfgxBjgUQAygKAxgBQAJAAgDAIQgTA4goArIguAqQgcAYgLAWQgdAxAIBWQALBugFAeQgEAXgKAHQgFADgFAAQgJAAgLgJg");
	this.shape_2.setTransform(13.9834,25.2205);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#91190E").s().p("AgYCCIAAirQAAgKgDgEQgDgDgJAAIgJAAQgKAAAAgHQAAgHALAAIAXAAIAAhKQAAgHACgCQABgDAGgDIANgHIAEgBQAEgBABADQACADAAAIIAABUIAjAAQAKAAAAAHQAAAEgCACQgDABgHAAIgNAAQgNAAgEAEQgDAFAAAPIAACNQAAAcADAJQAEAIALAAQAGAAADgBIAJgHQAFgDACAAQABAAAAAAQABAAABAAQAAABABAAQAAAAABABQACACAAADQAAAEgGAFQgNANgXAAQgpAAAAgog");
	this.shape_3.setTransform(302.875,34.0714);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#91190E").s().p("AAhB7QgHAAAAgGQAAgEACgCQACgCAHAAIAGgBQAIgBACgFQACgGAAgTIAAh1QAAgkgJgNQgIgNgZAAQghAAgRAVQgQAVAAAsIAABcQAAAUACAGQACAFAIABIALACQAFAAAAAHQAAAGgHAAIhNAAQgHAAAAgGQAAgHAFAAIALgCQAIgBACgFQACgGAAgTIAAiIQAAgRgCgEQgCgEgHgBIgGgBQgIAAAAgGQAAgFAIgEIAjgSQAGgDAEAAQAIAAAAALIgBATQAfgdAqAAQAlAAAQARQAQAQAAAmIAAB+QAAAUACAGQACAFAIABIAKACQAGAAAAAHQAAAGgHAAg");
	this.shape_4.setTransform(282.475,38.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#91190E").s().p("AglCwQgHAAAAgHQAAgGAFgBIALgBQAIgBACgGQACgGAAgSIAAiLQAAgOgDgFQgDgEgJAAIgBAAQgKAAAAgGQAAgFAHgDIAkgTIAIgDQAIAAAAAJIAAC8QAAAUACAFQACAGAIABIALABQAFABAAAGQAAAHgHAAgAgRiHQgGgHAAgKQAAgJAGgHQAHgHAKAAQAJAAAHAHQAHAHAAAKQAAAJgHAHQgHAHgJAAQgKAAgHgHg");
	this.shape_5.setTransform(262.575,33.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#91190E").s().p("AhUBbQghgjAAg4QAAg4AhgiQAhgiA0AAQA0AAAgAiQAhAjAAA3QAAA5ggAiQggAig2AAQg0AAgggigAg5hOQgXAeAAAwQAAAyAWAdQAWAeAlAAQAkAAAWgeQAVgeAAgyQAAgxgVgdQgVgdglAAQgkAAgWAeg");
	this.shape_6.setTransform(244.475,38.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#91190E").s().p("Ah1DHQgNAAAAgIQAAgHAMgBIAGgBQALAAACgHQADgHAAgaIAAkSQAAgRgLgCIgEAAQgJgBAAgIQAAgMArgNQApgNApAAQA7AAAiAeQAhAeAAA2QAAAzgeAhQgfAfgxAAQgVAAgSgGQgRgGAAgIQAAgDADgBQACgDADAAIAFABIALADQAJACAOAAQAjAAAVgXQAUgaAAgrQAAgtgWgbQgWgagoAAQglAAgMAMQgMANAAAnIAAECQAAAaACAHQAEAHAKAAIAPABQANABAAAHQAAAIgNAAg");
	this.shape_7.setTransform(219.6,30.75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#91190E").s().p("AAhDHQgIAAAAgGQAAgEACgCQACgBAHgBIAGgBQAIAAACgGQACgGAAgTIAAiBQAAgagKgMQgKgLgXAAQgiAAgPAVQgQAUAAAwIAABZQAAATADAGQACAFAIABIAGABQAHABACABQABACAAAEQAAAGgHAAIhMAAQgIAAAAgGQAAgGAGgBIAKgCQAIgBACgFQACgGAAgTIAAkjQAAgOgCgFQgDgEgHgBIgGAAQgHAAAAgGQAAgFAGgCIApgVQACgCADAAQAHAAAAAKIAACtQAegeAsAAQAjAAARAQQARARAAAiIAACDQAAATACAGQACAFAHABIALACQAGABAAAGQAAAGgHAAg");
	this.shape_8.setTransform(190.375,30.725);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#91190E").s().p("AgYCCIAAirQAAgKgDgEQgDgDgKAAIgIAAQgKAAAAgHQAAgHALAAIAXAAIAAhKIABgJQACgDAFgDIAOgHIAEgBQAHgBAAAOIAABUIAjAAQAKAAAAAHQAAAEgCACQgDABgHAAIgNAAQgNAAgEAEQgDAFAAAPIAACNQAAAcADAJQAEAIALAAQAFAAADgBIAKgHQAEgDADAAQABAAAAAAQABAAABAAQAAABABAAQAAAAABABQACACAAADQAAAEgGAFQgOANgWAAQgpAAAAgog");
	this.shape_9.setTransform(169.975,34.0741);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#91190E").s().p("AglDHQgHAAAAgHQAAgEABgBQACgCAHgBIAGAAQAIgBACgGQACgFAAgTIAAkqQAAgKgDgEQgEgDgJAAQgKAAAAgGQAAgGAGgBIAogWIAFgBQAIgBAAAKIAAFVQAAATADAGQACAGAIABIAKABQAFABAAAGQAAAHgHAAg");
	this.shape_10.setTransform(156.675,30.7705);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#91190E").s().p("AhNBrQgXgSAAgeQAAgbAUgWQATgVAkgMQAVgJASAAQALAAgBAIQABAGgLACQgkAHgWATQgUAUgBAcQABAWAOAOQANAPAVAAQAWAAAOgPQAPgPACgZQADgaAAglQAAg/gJgQQgIgRggAAQgbAAgcAUQgHAGgDAAQgKAAABgJQAAgFAFgEQANgNAWgHQAVgIAWAAQAmAAASASQASARAAAmIAAB/QAAASACAGQABAGAHABIACAAIADAAIAGACQAGABgBAGQAAAGgGAAIgpAAQgNAAAAgLIAAgLQgOAPgOAGQgOAGgUAAQgiAAgVgTg");
	this.shape_11.setTransform(138.4,38.525);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#91190E").s().p("AhFBaQgggjAAg2QAAg1AgglQAhgkAwABQAgAAAZATQAaAVAAAYQAAAKgFAGQgFAGgOAJIheA3QgGAFgFgBQgIABAAgIQAAgDACgCIAHgGIA/glQARgKAGgIQAHgHAAgKQAAgSgQgQQgPgOgUAAQgfAAgVAeQgUAeAAAwQAAAxAWAeQAWAdAkAAQAnABAegkQAGgFACgBQAIAAAAAJQAAAIgOANQgfAcguABQgwAAgggkg");
	this.shape_12.setTransform(115.125,38.65);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#91190E").s().p("ABBDEQgNgBAAgHQAAgHAMgCIAGAAQALgBACgHQADgGAAgbIAAh0IgBgXQgBgIgEgCQgEgEgFAAQgFgBgQAAIhrAAQgTAAgEAGQgEAGAAAZIAAB1QAAAbACAGQADAHAKABIAHAAQAMACAAAHQAAAHgNABIhRAAQgOgBAAgHQAAgHAMgCIAHAAQALgBACgHQADgGAAgbIAAkSQAAgcgDgHQgCgGgLgBIgHgBQgMAAAAgIQAAgIANAAIBRAAQANAAAAAIQAAAEgCACQgDABgHABIgGABQgLABgCAGQgCAHAAAbIAABmICpAAIAAhlQABgbgDgIQgCgGgLgBIgGgBQgMAAAAgIQAAgIAMAAIBSAAQANAAAAAIQAAAIgLAAIgHABQgLABgCAGQgDAHAAAbIAAESQAAAbADAHQACAHALABIAHAAQALACAAAHQAAAHgMABg");
	this.shape_13.setTransform(86.475,31.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,308.8,60);


(lib.HealthPoint_Sinceai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HealthPoint_Since.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#71212C").s().p("AgYAdQgMgLAAgSQAAgPALgMQAKgMAQAAQARAAAKANQAJALAAAQIAAAFIg3AAQADAUASAAQALAAAJgKIAKAKQgLAOgTAAQgQAAgLgLgAgTgEIAnAAQgDgUgQAAQgRAAgDAUg");
	this.shape.setTransform(32.95,6.675);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#71212C").s().p("AgXAcQgLgLAAgRQAAgPALgMQALgMAQAAQATAAAMANIgLAMQgJgJgLAAQgIAAgHAHQgGAHAAAJQAAAKAGAIQAHAHAJAAQAKAAAKgKIAKALQgNAOgSAAQgQAAgLgMg");
	this.shape_1.setTransform(25.075,6.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#71212C").s().p("AARAnIAAgrQAAgSgRAAQgGAAgFAFQgFAFAAAJIAAAqIgSAAIAAhLIASAAIAAALQAJgNAOAAQANAAAHAIQAIAIAAAOIAAAvg");
	this.shape_2.setTransform(16.7,6.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#71212C").s().p("AgIA1IAAhMIARAAIAABMgAgJgiIAAgSIASAAIAAASg");
	this.shape_3.setTransform(10.4,5.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#71212C").s().p("AgmAkIALgNQAOANAQAAQATAAgBgNQABgFgFgDQgFgEgMgDQgSgEgHgFQgJgHAAgOQAAgNAKgIQAJgIAPAAQAUAAAQANIgJANQgOgKgNAAQgHAAgFADQgEAEAAAFQAAAGAEADQAGADANAEQAQAEAIAFQAIAIAAAMQAAAOgKAIQgJAIgRAAQgXAAgSgQg");
	this.shape_4.setTransform(3.9,5.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,36.7,10.7);


(lib.HealthPoint_1971ai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HealthPoint_1971.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#71212C").s().p("AACAzIAAhTIgRAFIgEgOIAagJIANAAIAABlg");
	this.shape.setTransform(25.025,5.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#71212C").s().p("AgdAzIAshVIgxAAIAAgQIBGAAIAAAOIgtBXg");
	this.shape_1.setTransform(18.55,5.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#71212C").s().p("AgkAoIAKgNQALAJAMAAQAKAAAHgJQAGgIABgPQgJALgOAAQgQAAgKgJQgKgIAAgOQAAgPAKgKQALgKAQAAQARAAALAKQAMAMAAAbQAAAYgMAPQgLAPgTAAQgSAAgPgMgAgPgeQgFAFAAAIQgBAIAHAFQAFAEAJAAQAJAAAFgEQAGgFAAgIQAAgIgGgFQgGgGgIAAQgJAAgGAGg");
	this.shape_2.setTransform(9.8,5.225);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#71212C").s().p("AACAzIAAhTIgRAFIgEgOIAagJIANAAIAABlg");
	this.shape_3.setTransform(1.975,5.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,27,10.5);


(lib.HealthPoint_50onlyai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HealthPoint_50only.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjIDoQhLhcAAiLQAAiKBMhdQBOhgB6AAQB6AABOBfQBLBcAACLQAACKhMBdQhPBgh5ABQh6gBhOhfgAh1ihQgrBAAABhQAABgAsBAQAtBDBIAAQBIAAAthCQArhAAAhgQAAhggshAQguhDhHAAQhJAAgsBBg");
	this.shape.setTransform(97.575,64.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjoDhIBFhQQBRBLBRAAQA4AAAjgdQAigfAAgxQAAgygkgcQgkgcg6gBQg6AAg7AcIhDgrIASk2IF5AAIAABjIkZAAIgKCUQAxgSAzAAQBhAAA7AyQA/A0AABgQAABihAA7QhAA7hpAAQiEAAhkhhg");
	this.shape_1.setTransform(42.475,65.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#71212C").s().p("AjIDoQhLhcAAiLQAAiKBMhdQBPhgB5AAQB7AABNBfQBLBcAACLQAACKhMBdQhPBgh5AAQh7AAhNhfgAh1igQgrA/AABhQAABgAsBBQAtBCBIAAQBIAAAthCQArg/AAhhQAAhggshAQgthDhIAAQhIAAgtBCg");
	this.shape_2.setTransform(99.45,66.575);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#71212C").s().p("AjoDhIBEhQQBTBMBQAAQA4AAAjgeQAigfAAgyQAAgwgkgdQgkgcg6AAQg6AAg7AcIhDgsIASk2IF5AAIAABjIkZAAIgKCUQA0gSAwAAQBhAAA7AxQA/A0AABiQAABhhAA7QhAA7hpAAQiFAAhjhhg");
	this.shape_3.setTransform(44.375,67.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#AE222D").s().p("Ai4HSQiaihiGjbQijkHgLipQgQjvEFAgQBgAMCVAyID2BaQBGAZA6gLQAngIAygfQA6gkATgHQAsgRAwAQQAcAJAgAUQCYBhg3DhQgtC4ifDNQitDfigAyQgsAOgqAAQhqAAhYhbg");
	this.shape_4.setTransform(67.2247,65.8653);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F9762B").s().p("AmVGWQioioAAjuQAAjtCoioQCoipDtAAQDuAACoCpQCoCoAADtQAADuioCoQioCojuABQjtgBioiog");
	this.shape_5.setTransform(57.425,58.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#8BAC43").s().p("AmVGWQipioAAjuQAAjtCpioQCoioDtAAQDuAACoCoQCoCoABDtQgBDuioCoQioCojuAAQjtAAioiog");
	this.shape_6.setTransform(88.25,57.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,145.7,121.6);


(lib.HEAD_50_2linesai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HEAD_50_2lines.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#70202C").s().p("AnFBhQgKgHAAgNQAAgMAJgIQAGgHAGAAQABAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIgBAEIgBAFQAAALAOAAQAUAAAIgyQgQAOgVAAQgJAAgGgFQgFgEgBgHQgMAQgSAAQgKAAgGgFQgGgFAAgIQAAgIAEgKQADgLAAgEQABgHgGAAQgIAAgHAPQgEAGgDALQgEANAAAHQAAAFgFAAIgUABQgFAAAAgFIABgGQgMALgPAAQgJAAgGgGIgDgHQgNANgSAAQgLAAgHgHQgIgIAAgNQAAgTAMgNQANgPAYAAQAIAAAFACIAHACIAKgCIAKgCQABAAABAAQABAAAAABQABAAAAABQAAAAAAABIgEARQgFAQABAKQAAAKAIAAQAEAAAFgFIADgDIABgEQAFgVAAgHIgBgHQgBgEAJgDQAIgCALAAQAHAAAAAGIgCALQAQgRASAAQASAAAAAPQAAAFgDAMQgEAKAAAFQAAAJAIAAQAEAAAFgFQAAgBABAAQAAgBABAAQAAAAABgBQAAAAABAAIADgOQAEgOAAgEIgCgHQAAgEAIgDQAJgCAKAAQAIAAAAAGQAAAFgDAPQgFAOAAAIQAAAIAGAAQAJAAAGgKQAIgLgBgTQgCgEAAgDQABgEAIgDQAHgCALAAQAJAAAAAGQAAAGgKApQgGAqgJARQgOAfgdAAQgNAAgJgHgAp1gOQgEALAAAMQAAALAIAAQAHAAAFgLQAHgOAAgRQAAgHgIAAQgJAAgGAPgAupBFQAAgCADgEQAGgIADgLQAEgNAEgbIAFgbQgBgEgEAAQgEAAAAgEQAAgCACgDQAAAAABgBQAAAAABgBQAAAAAAAAQABAAAAAAQAGAAABgGQAKgoAjAAQALAAAHAEQAGAFAAAHQAAAMgMAAQgHAAgCgHQgCgHgCAAQgEAAgDAIQgDAHAAAGQAAAGADACQAFADALAAQABAAABAAQAAAAABAAQAAABAAAAQABABAAABQgBADgCACQAAABAAAAQgBABAAAAQgBAAAAABQgBAAAAAAQgMAAgFADQgFAEgCAHQgGAigGAWQgDALgPAKQgNAIgHAAQgFAAAAgDgADHAdQgEgEgCgFQgOAQgRAAQgVAAAAgSQAAgHAEgLQADgMABgEQAAgGgHAAQgHAAgHAPQgDAGgEANQgEANAAAFQAAAFgEAAIgVABQgFAAAAgFQAAgJAKgnQALgoAAgTQAAgLgJAAQgEAAAAgDQAAgEAIgFQAJgEAKAAQAUAAAAASQAAATgOAqQANgPASAAQAVAAAAAQQAAAGgEALQgDAJAAAFQgBAJAIAAQAEAAAFgFIABgBIgBgGQAAgRAOgOQAPgOAXAAQANAAAJAIQAIAHAAANQAAAUgMAOQgNAPgWAAQgPAAgKgIgADpgZQgMAJAAASQABAIAEAEQAEAFAIAAQAGAAAFgGQAEgFAAgHQAAgGgEgCQgKgDAAgHQAAgDACgDIABgDQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAgBAAIgHADgAlhAdQgJgJAAgPQAAgRAOgOQAOgOAYAAQANAAAIAIQAIAHAAANQABAUgMAOQgOAPgVAAQgQAAgKgIgAk+gZQgMAJAAASQAAAIAEAEQAEAFAHAAQAHAAAGgGQADgFAAgHQAAgGgEgCQgKgEAAgGQAAgDACgDIACgDQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAIgHADgAtYAdQgJgJAAgPQAAgRAOgOQAOgOAYAAQAMAAAJAIQAIAHAAANQABAUgMAOQgOAPgVAAQgQAAgKgIgAs1gZQgMAJAAASQAAAIAEAEQAFAFAHAAQAHAAAFgGQADgFAAgHQABgGgFgCQgKgEAAgGQAAgDACgDIACgDQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAIgHADgAKwAfQgFgDgCgEQgMAMgQAAQgJAAgFgGIgEgGQgMAMgSAAQgVAAgEgSQgIAIgHAEQgMAHgPAAQgeAAgHgUQgSAUgZAAQgbAAgIgRQgMAQgSAAQgKAAgHgFQgFgFAAgIQAAgIAEgKQADgLAAgEQAAgHgFAAQgIAAgIAPQgDAGgDALQgEANAAAHQAAAFgFAAIgVABQgEAAAAgFQAAgEAEgWQAFgVABgHIgCgHQAAgEAIgDQAIgCALAAQAIAAAAAGIgCALQAFgFAIgGQALgGAJAAQATAAAAAPQAAAFgDAMQgEAKAAAFQAAAJAHAAQAFAAAFgFIAAgBIAAgHQAAgSAOgMQANgOAYAAQAXAAAAASQAAALgLAIQgLAHgRACQAAAGAEAEQAFAFAJAAQAKAAAQgNIABAAIAAgEQAAgSANgMQAOgOAYAAQAXAAAAASQAAALgLAIQgLAHgSACQAAAGAEAEQAGAFAIAAQALAAAPgNIABAAQAAgUAMgNQANgOAVAAQALAAAHAEQAGgcABgNQAAgLgKAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAgEAJgFQAJgEAJAAQAUAAAAASQAAAKgKAiQgKAhAAAPQAAAKAIAAQAEAAAEgDQAAgFADgCQADgEAFAAQAKAAAAAJQAAAKAHAAQAEAAAAgGQABgHgMgJQgMgIAAgKQAAgLAKgGQAJgFAOAAQAZAAAAAQQAAAMgLAAQgDAAgDgCQgCgCgBgEIACgHQABgDgFAAQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAgBABQgCACAAAEQAAAGAOAJQANAIgBAJQABAMgJAHQgKAIgQAAQgNAAgIgGgAJngOQgEANgBAMQAAAJAIAAQAIAAAEgLQADgFACgJQACgKAAgHQAAgHgIAAQgIAAgGAPgAIbgWQgFAIAAALQAJgCAIgIQAFgGAAgFQAAgFgFAAQgGAAgGAHgAHMgWQgFAIAAALQAJgCAHgIQAGgGAAgFQAAgFgFAAQgHAAgFAHgAijAdQgFgEgDgGIgBABQgMAQgSAAQgKAAgGgFQgGgFAAgIQAAgIAEgKQAEgLgBgEQABgHgGAAQgIAAgHAPQgEAGgDALQgEANABAHQgBAFgFAAIgUABQgFAAAAgFQAAgEAFgWQAFgVAAgHIgCgHQAAgEAJgDQAIgCAKAAQAJAAgBAGIgCALQAFgGAIgFQALgGAKAAQASAAAAAPQAAAFgEAMQgDAKAAAFQAAAJAIAAQAEAAAFgFIABgCIAAgGQAAgSANgMQAOgOAYAAQAXAAAAASQABAKgLAJQgMAHgSACQAAAGAFAEQAFAFAHAAQAJAAAJgHIAFgCQABAAABAAQABAAAAAAQABABAAAAQAAABAAAAQAAADgGAGQgPAOgSAAQgSAAgKgIgAiGgWQgGAIAAALQAKgCAHgIQAGgGAAgFQAAgFgGAAQgFAAgGAHgAORAZQAAgGAEgGQAGgGAGAAQADAAADAEQADADAAAEQAAAHgFAFQgFAGgGAAQgKAAABgLgANPAXQgMANgRAAQgLAAgHgGQgFgFAAgJQAAgIADgNQAEgOABgEIgCgHQAAgEAIgDQAIgCALAAQAIAAAAAGQAAAEgEAOQgEAOAAAIQAAAEADADQACADADAAQAEAAAFgFQABgIAEgLQADgNAAgGQAAAAAAAAQAAgBgBAAQAAAAgBAAQAAgBgBAAQgBAAgBAAQAAgBgBAAQAAgBAAAAQgBgBAAAAQABgHAEAAQAQAAAOgXQAEgFADAAQAEAAAAAEQAAAFgEAOQAAAFAIAAQABAAABAAQABAAAAAAQABABAAAAQAAABAAABQAAAIgFAAQgJAAgCAHQgFASAAAJQAAAKAJAAQAEAAAEgDIAGgFQACgDACAAQABAAABAAQAAABABAAQAAAAAAABQAAAAAAABQAAADgCACQgGAIgJAGQgLAIgLAAQgSAAgFgNgAAJAUQgNAQgXAAQgJAAgGgGQgHgFABgIQAAgJADgNQAFgNAAgFIgCgHQAAgEAJgDQAHgCALAAQAIAAAAAGQAAAFgEAPQgEANAAAJQAAAJAHAAQAIAAAFgLQAHgNAAgRQgCgEAAgDQAAgEAIgDQAIgCALAAQAIAAAAAGQAAAFgEAPQgDAOAAAIQgBAJAJAAQAIAAAFgJQAGgJAAgJQAAgEgEgEQgEgEABgFQAAgGADgDQAFgEAGAAQAPAAAAARQAAAUgNARQgPAVgVAAQgUAAgJgQgAsNAfQAAgEAFgWQAFgVAAgHIgCgHQAAgEAJgDQAIgCAKAAQAIAAAAAGQAAAFgBAEQAHgOAPAAQAKAAABALQAAAHgFAGQgEAGgIAAQgEAAgDgDQgDgDABgDQgEABgFAJQgDAGgDALQgDANAAAHQgBAFgFAAIgUABQgFAAAAgFgAMtg4QgFgEAAgFQABgHAFgHQAGgGAGAAQAOAAAAANQAAAHgGAHQgFAGgHAAQgFAAgEgEg");
	this.shape.setTransform(97.55,33.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#70202C").s().p("ApxBiQgKgIAAgMQABgNAHgIQAHgHAGAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAABIgBADQgBACAAAEQAAALANAAQAVAAAHgzQgQAPgVAAQgIgBgGgFQgHgFABgIQAAgJADgOQAFgOAAgDIgCgIQAAgEAIgCQAIgDALAAQAIABAAAFQAAAFgEAPQgFAPABAIQAAAIAFAAQAIgBAIgJQAHgLAAgTQgCgFAAgDQAAgEAIgCQAIgDALAAQAIABAAAFIgCAMIgIAjQgGAqgIASQgOAfgdAAQgNAAgKgHgAhkBFIACgFQAGgIADgLQAEgOAFgbIAEgbQAAgEgEAAQgEAAgBgEQAAAAABgBQAAAAAAgBQAAAAABgBQAAgBABAAQAAgBAAAAQABgBAAAAQABAAAAAAQABAAAAAAQAFAAACgHQAKgoAjAAQALAAAHAFQAFAFAAAGQAAANgMAAQgGAAgDgHQgBgIgCAAQgFAAgCAJQgDAGAAAGQAAAHADACQAEADAMAAQAAAAABAAQABAAAAAAQABAAAAABQAAAAAAABQAAAJgGAAQgLgBgFAEQgGADgBAIQgGAjgHAUQgCAMgQAJQgNAJgHAAQgFgBABgDgAsCAaQgLgNAAgWQAAgoAUgcQAUgbAbAAQASAAAKALQAMAMAAAZQgBAkgRAbQgVAfgdAAQgRAAgLgMgArihAQgJAcAAAqQAAAIADAFQADAFAFAAQANAAAJgkQAHgeAAgfQAAgTgKABQgNAAgIAbgAMgAEQAAgRANgMQAOgOAXAAQAYAAAAARQAAALgLAIQgMAIgRACQAAAGAEAEQAFAEAHAAQAKAAAIgGIAGgDQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABQABADgGAFQgOAOgUABQgngBABghgANHgVQgFAIAAAKQAJgCAHgHQAHgHgBgFQABgFgHAAQgFAAgGAIgAItAdQgLgJAAgPQAAgSANgMQAPgOAWAAQAZAAAAAQQAAAQgOAAQgKAAAAgIQAAgDACgDIACgEQAAgDgFAAQgFgBgGAJQgFAKgBALQABAKAFAFQAFAFAIAAQAMAAAOgMIABgBQAAgTAMgNQANgPAYAAQAHAAAGADIAHACIAJgCIALgDQABAAABABQAAAAABAAQAAABAAAAQABABAAABIgFARQgEAQAAAKQAAAJAJAAQADAAAGgFIADgCIAAgEQAFgVABgHIgCgIQAAgEAIgCQAIgDALAAQAIABAAAFIgCAKQAIgPAOAAQALAAAAAMQAAAGgEAGQgEAHgIAAQgKAAAAgJQgEABgEAJQgDAGgEALQgDAMAAAHQAAAGgFAAIgVABQgEAAAAgGIABgGQgMALgPABQgKAAgFgHIgEgGQgNANgSAAQgLAAgHgIQgEgEgCgHQgJAJgGADQgMAIgPAAQgRgBgKgIgAKVgOQgFAMAAAMQAAALAJAAQAHAAAFgLQAGgNAAgSQAAgHgHAAQgKAAgFAOgABwAVQgNAQgSAAQgVAAAAgTQAAgHAEgLQAEgMAAgEQAAgFgGgBQgHAAgIAPQgDAGgEAOQgDANAAAEQAAAGgFAAIgVABQgFAAABgGQAAgIAKgnQAKgpABgSQAAgMgKAAQgDAAAAgDQAAgEAHgEQAJgFAKAAQAVAAAAATQgBASgOAqQAOgPASAAQAVAAgBAQQAAAHgDAKQgEAJAAAGQAAAIAHAAQAFAAAEgFIABgBIAAgHQAAgRAOgMQAOgOAXAAQAXAAAAARQAAALgLAIQgLAIgRACQAAAGAEAEQAFAEAJAAQALAAAPgMIABgBQAAgTALgNQAOgPAXAAQAIAAAGADIAHACIAJgCIALgDQAAAAABABQABAAAAAAQABABAAAAQAAABAAABIgEARQgEAQgBAKQAAAJAJAAQAEAAAFgFIABgBQABgKAIgaQAJgeAAgUQAAgMgKAAQAAAAgBAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgEAIgEQAJgFAKAAQAJAAAFAFQAGAFAAAJQAAAKgKAjQgJAkAAALQAAAJAIAAQADAAAGgFIAAgBQAAgHAEgLQAEgMAAgGQAAAAgBgBQAAAAAAAAQgBgBAAAAQgBAAgBAAQAAAAgBgBQgBAAAAAAQgBgBAAAAQAAgBAAgBQAAgGAEAAQAQgBAPgWQADgGAEAAQADABAAAEQAAAEgDAOQgBAFAJABQABAAABAAQAAAAABAAQAAAAAAABQABAAAAABQAAAEgCACQgBABAAAAQgBABAAAAQgBAAAAAAQAAABgBAAQgJAAgCAHQgEARAAAKQAAAJAJAAQAEAAAJgHIACgCIAHgYQAKgpAAgSQAAgMgJAAQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQgBgEAJgEQAJgFAJAAQAVAAgBATQAAASgOAqQAOgPASAAQAUAAAAAQQAAAHgDAKQgEAJAAAGQAAAKAFAAQAEgBADgCIADgCQABAAABABQAAAAAAAAQABAAAAABQAAAAAAABQAAACgDAEQgLAOgOAAQgWAAAAgTQAAgHAEgLQAEgMAAgEQAAgFgGgBQgIAAgHAPQgDAGgDAOIgFARQAAAGgEAAIgWABQgEAAAAgGIABgJIgJAHQgMAIgJAAQgTAAgFgOQgLAOgRAAQgSgBgEgNQgMANgRABQgJAAgFgHIgFgGQgMANgSAAQgLAAgHgIQgFgEgCgHQgHAJgHADQgMAIgQAAQgaAAgJgRgADhgOQgFAMgBAMQAAALAJAAQAHAAAGgLQAFgNAAgSQAAgHgGAAQgKAAgFAOgACVgVQgFAIAAAKQAJgCAHgHQAGgHAAgFQAAgFgGAAQgGAAgFAIgAifAdQgJgJAAgOQAAgSAOgNQAOgPAYAAQANABAIAHQAJAIAAAMQAAAUgMAOQgOAPgVABQgQgBgKgIgAh8gZQgLAKAAARQAAAIADAFQAFAFAHAAQAHAAAFgGQAEgGAAgHQAAgGgFgCQgJgEAAgFQAAgEACgDIABgCQAAgBAAAAQAAgBgBAAQAAAAAAAAQgBAAAAAAQgDAAgEACgAoWAEQAAgRANgMQAPgOAXAAQAYAAAAARQAAALgLAIQgLAIgTACQAAAGAFAEQAFAEAIAAQANAAAOgMIAAAAQAAgUAMgNQANgPAZAAQAHAAAGADIAHACIAJgCIALgDQABAAABABQAAAAABAAQAAABAAAAQABABAAABIgFARQgEAQAAAKQAAAJAIAAQAEAAAGgFIADgCIAAgEQAFgVABgHIgCgIQAAgEAIgCQAIgDALAAQAIABAAAFIgCAKQAIgPAOAAQALAAAAAMQAAAHgEAFQgFAHgHAAQgKAAAAgJQgEAAgEAKQgDAGgEALQgDAMAAAHQAAAGgGAAIgUABQgEAAAAgGIABgGQgMALgPABQgKAAgFgHIgEgGQgNANgSAAQgLAAgHgIQgEgEgCgHQgTATgXABQgngBAAghgAmigOQgFAMAAAMQAAALAIAAQAHAAAGgLQAGgPAAgQQAAgHgHAAQgKAAgFAOgAntgVQgGAIgBAKQAKgCAHgHQAHgHAAgFQAAgFgHAAQgFAAgFAIgAkTAfQgJgFAAgKQAAgGAEgDQADgDAEAAQALAAAAAJQgBAKAHAAQAFAAAAgGQABgHgMgJQgNgJAAgJQABgLAJgGQAKgGAOAAQAZAAAAAQQAAANgLAAQgDAAgDgDQgDgCAAgDIACgHQAAgEgFAAQgCAAgCADQgCACAAADQAAAHANAJQANAIAAAJQAAAMgJAHQgJAHgPAAQgPAAgIgGgAtjAXQgKgLAAgQQAAgGAFAAQADAAABAFQAFAOARAAQAKAAAGgIQAGgGgBgLQABgIgEgHQgGgIgKAAIgJABIgCAAQgHAAAAgIIAEgQQAEgRACgLQABgFADgDQADgEAGAAIAIACQAJABALABQAUAAAGgFQAEAAAAAEQAAADgEAJQgGAKgGAEQgDACgIAAQgGgBgUgEQgCANgEALIAKgBQARgBAMALQAMALAAAQQAAAWgNAPQgPAQgVAAQgTgBgKgNg");
	this.shape_1.setTransform(99.4,14.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFEA7D").ss(7.4,0,0,1).p("AJDAIQAAgUAMgNQAOgOAUAAQALAAAHAEQAHgcAAgNQAAgLgKAAQgEAAAAgDQAAgEAJgFQAJgEAJAAQAVAAAAASQAAAKgKAiQgLAhAAAPQAAAKAIAAQAEAAAEgEQAAgEADgCQADgEAFAAQAKAAAAAJQAAAKAGAAQAFAAAAgGQAAgHgLgJQgMgIAAgKQAAgLAKgGQAJgFAOAAQAZAAAAAQQAAAMgKAAQgEAAgDgCQgDgCAAgEQADgFAAgCQAAgDgFAAQgDAAgBACQgDACAAAEQAAAGAOAJQANAIAAAJQAAAMgJAHQgJAIgQAAQgOAAgIgGQgFgDgCgEQgMAMgPAAQgJAAgGgGIgEgGQgMAMgSAAQgVAAgEgSQgIAIgGAEQgMAHgQAAQgeAAgHgUQgBgEAAgFQADgDABAAQACAAAAADQAAADgFAGQgSAUgYAAQgcAAgHgRQgNAQgSAAQgKAAgHgFQgFgFAAgIQAAgIAEgKQAEgLAAgEQAAgHgGAAQgIAAgHAPQgEAGgDALQgEANAAAHQAAAFgFAAIgVABQgFAAAAgFQAAgEAFgWQAFgVAAgHQgBgEAAgDQAAgEAJgDQAHgCALAAQAIAAAAAGQAAAEgBAHQAEgFAIgGQALgGAJAAQATAAAAAPQAAAFgEAMQgDAKAAAFQAAAJAIAAQAEAAAFgFQAAgBABAAQgBgDAAgEQAAgSAOgMQAOgOAXAAQAYAAAAASQAAALgLAIQgMAHgRACQAAAGAEAEQAFAFAJAAQAKAAAQgNQAAAAABAAQAAgCAAgCQAAgSANgMQAOgOAYAAQAXAAAAASQAAALgLAIQgMAHgRACQAAAGAFAEQAFAFAIAAQALAAAPgNQABAAAAAAQADgDABAAQADAAAAADQAAADgFAGQgBAAAAABQgBgEAAgGQAAAAAAAAgAM6hVQAOAAAAANQAAAHgFAHQgGAGgHAAQgGAAgDgEQgEgEAAgFQAAgHAFgHQAGgGAGAAgANPAXQgMANgQAAQgMAAgGgGQgGgFAAgJQAAgIAEgNQAEgOAAgEQgCgEAAgDQAAgEAJgDQAHgCALAAQAIAAAAAGQAAAEgEAOQgEAOAAAIQAAAEADADQACADADAAQAEAAAGgFQAAgIAEgLQADgNAAgGQAAgBgDgBQgEgBAAgCQAAgHAFAAQAQAAAOgXQAEgFADAAQAEAAAAAEQAAAFgDAOQAAAFAHAAQAEAAAAADQAAAIgFAAQgJAAgCAHQgFASAAAJQAAAKAKAAQACAAAFgDQACgCAEgDQADgDABAAQAEAAAAADQAAADgCACQgHAIgJAGQgLAIgKAAQgTAAgFgNQgBgFAAgFQAAgBAAAAQACgDACAAQADAAAAADQAAADgEAFQgBACgBABgAKnANQABAAABgBQACgDACAAQADAAAAADQAAADgEAFQgCACgBACQgCgEAAgEQAAgBAAgCgAOhAHQAEAAADAEQACADAAAEQAAAHgEAFQgFAGgIAAQgIAAAAgLQAAgGAFgGQAFgGAGAAgAGoAUQgDgEAAgFQABgCACAAQADAAAAADQAAADgDAFgAC+ALQAAgDAAgDQAAgRANgOQAPgOAXAAQAOAAAIAIQAIAHAAANQAAAUgMAOQgNAPgVAAQgQAAgKgIQgEgEgCgFQgOAQgRAAQgVAAAAgSQAAgHAEgLQAEgMAAgEQAAgGgGAAQgIAAgHAPQgDAGgEANQgDANAAAFQAAAFgFAAIgVABQgFAAAAgFQAAgJALgnQAKgoAAgTQAAgLgJAAQgEAAAAgDQAAgEAIgFQAJgEAKAAQAUAAAAASQAAATgOAqQANgPATAAQAUAAAAAQQAAAGgDALQgEAJAAAFQAAAJAHAAQAEAAAFgFQAAgBABAAgAD5gHQgKgDAAgHQAAgDACgDIACgDQAAgCgDAAQgBAAgFADQgMAJAAASQAAAIAEAEQAEAFAIAAQAHAAAEgGQAEgFAAgHQAAgGgEgCgAIsgYQAAgFgFAAQgGAAgFAHQgGAIAAALQAKgCAHgIQAFgGAAgFgAJ2gdQgJAAgGAPQgEANAAAMQAAAJAHAAQAIAAAFgLQACgFACgJQACgKAAgHQAAgHgHAAgAHdgYQAAgFgGAAQgFAAgGAHQgFAIAAALQAJgCAHgIQAGgGAAgFgAA6gaQAAgGAEgDQADgEAHAAQAPAAAAARQAAAUgNARQgPAVgVAAQgUAAgJgQQgNAQgXAAQgKAAgFgGQgHgFAAgIQAAgJAFgNQAEgNAAgFQgCgEAAgDQAAgEAIgDQAIgCALAAQAIAAAAAGQAAAFgEAPQgEANAAAJQAAAJAHAAQAIAAAFgLQAHgNAAgRQgCgEAAgDQAAgEAJgDQAHgCALAAQAIAAAAAGQAAAFgDAPQgEAOAAAIQAAAJAIAAQAIAAAFgJQAGgJAAgJQAAgEgEgEQgDgEAAgFgAiuAKQAAgDAAgDQAAgSANgMQAOgOAXAAQAZAAAAASQAAAKgLAJQgMAHgSACQAAAGAFAEQAFAFAHAAQAJAAAJgHQAEgCACAAQADAAAAACQAAADgGAGQgPAOgSAAQgSAAgKgIQgFgEgDgGQAAABgBAAQgMAQgSAAQgKAAgGgFQgGgFAAgIQAAgIAEgKQADgLAAgEQAAgHgFAAQgIAAgHAPQgDAGgEALQgDANAAAHQAAAFgGAAIgUABQgFAAAAgFQAAgEAFgWQAFgVAAgHQgCgEAAgDQAAgEAJgDQAHgCAMAAQAIAAAAAGQAAAEgDAHQAFgGAIgFQALgGAJAAQATAAAAAPQAAAFgEAMQgDAKAAAFQAAAJAIAAQAEAAAFgFQABgBAAgBgAh1gYQAAgFgGAAQgGAAgFAHQgGAIAAALQAKgCAHgIQAGgGAAgFgADBAUQgCgEgBgFQACgCACAAQADAAAAADQAAADgEAFgAnJAJQABgGACgIQAEgOAAgEQgCgEAAgDQAAgEAJgDQAHgCALAAQAIAAAAAGQAAAFgEAPQgEAOAAAIQAAAIAGAAQAIAAAIgKQAGgLAAgTQgBgEAAgDQAAgEAIgDQAIgCAKAAQAJAAAAAGQAAAGgKApQgHAqgHARQgPAfgdAAQgNAAgJgHQgKgHAAgNQAAgMAIgIQAHgHAGAAQACAAAAACQAAABgBADQgBACAAADQAAALAOAAQAUAAAHgyQgQAOgUAAQgJAAgGgFQgFgEgBgHQAAgBAAgBQAAgEABgFIAAAAQAEAAAAADQAAADgEAFIgBAAQgMAQgSAAQgKAAgGgFQgGgFAAgIQAAgIAEgKQAEgLAAgEQAAgHgGAAQgIAAgHAPQgEAGgDALQgEANAAAHQAAAFgFAAIgUABQgFAAAAgFQAAgCABgFQgMAMgPAAQgJAAgGgGIgEgHQgNANgRAAQgLAAgHgHQgIgIAAgNQAAgTAMgNQANgPAYAAQAHAAAGACQAGACABAAQACAAAIgCQAHgCADAAQAEAAAAADQAAACgEAPQgFAQAAAKQAAAKAJAAQAEAAAFgFQACgCABgBQAAgCABgCQAFgVAAgHQgCgEAAgDQAAgEAJgDQAHgCALAAQAIAAAAAGQAAAEgCAHQAQgRARAAQATAAAAAPQAAAFgEAMQgDAKAAAFQAAAJAIAAQAEAAAFgFQACgDACAAgAowAJQABAAAAAAQADAAAAADQAAADgEAFQgBADgCABQABgFACgKgAirATQgCgEgBgFQACgBABAAQAEAAAAADQAAADgEAEgAkvgHQgKgEAAgGQAAgDACgDIACgDQAAgCgDAAQgBAAgFADQgMAJAAASQAAAIAFAEQADAFAHAAQAIAAAFgGQADgFAAgHQAAgGgEgCgAkYgMQAAAUgMAOQgOAPgVAAQgQAAgJgIQgKgJAAgPQAAgRAOgOQAOgOAYAAQANAAAIAIQAJAHAAANgAsmgHQgKgEAAgGQAAgDACgDIACgDQAAgCgDAAQgBAAgFADQgMAJAAASQAAAIAEAEQAFAFAHAAQAHAAAEgGQAEgFAAgHQAAgGgEgCgAsPgMQAAAUgNAOQgMAPgWAAQgQAAgJgIQgKgJAAgPQAAgRANgOQAPgOAYAAQAMAAAJAIQAJAHAAANgAtrgxQAAAGADACQAEADAMAAQADAAAAADQAAADgCACQgBADgCAAQgMAAgFADQgFAEgCAHQgGAigGAWQgDALgPAKQgNAIgIAAQgEAAAAgDQAAgCADgEQAGgIADgLQADgNAFgbQAEgYAAgDQAAgEgEAAQgEAAAAgEQAAgCACgDQABgCACAAQAGAAABgGQAKgoAjAAQALAAAHAEQAGAFAAAHQAAAMgMAAQgHAAgCgHQgCgHgCAAQgEAAgDAIQgDAHAAAGgArvAeQAAAFgFAAIgUABQgFAAAAgFQAAgEAFgWQAFgVAAgHQgCgEAAgDQAAgEAJgDQAHgCALAAQAIAAAAAGQAAAFgBAEQAHgOAOAAQALAAAAALQAAAHgEAGQgFAGgHAAQgEAAgDgDQgDgDAAgDQgDABgFAJQgDAGgDALQgEANAAAHgApmgdQgJAAgGAPQgFALAAAMQAAALAJAAQAHAAAFgLQAGgOAAgRQAAgHgHAAg");
	this.shape_2.setTransform(97.55,33.575);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFEA7D").ss(7.4,0,0,1).p("ANZgXQAAgGgGAAQgGAAgFAIQgGAIAAAKQAJgCAIgHQAGgGAAgFgANlAPIAFgDQAEAAAAADQAAADgGAFQgOAPgTAAQgnAAAAgiQAAgRANgNQAOgNAXAAQAYAAAAARQAAALgLAJQgLAHgSACQAAAGAFAEQAFAEAHAAQAJAAAJgGgALaAKQAAgCABgCQAFgVAAgHQgCgFAAgDQAAgDAJgDQAHgCALAAQAIAAAAAFIgBAKQAHgPAOAAQALAAAAALQAAAHgEAHQgEAGgHAAQgLAAAAgKQgDACgFAJQgDAGgDALQgEANAAAHQAAAFgFAAQgRAAgDAAQgFAAAAgFQAAgBABgFQgMALgPAAQgJAAgGgFIgEgHQgNAMgRAAQgLAAgHgHQgFgEgCgHQgJAJgGAEQgMAHgPAAQgRAAgKgJQgLgJAAgOQAAgTANgNQAPgNAWAAQAZAAAAARQAAAPgOAAQgKAAAAgIQAAgDACgDQACgDAAgBQAAgDgEAAQgGAAgFAIQgGAJAAAMQAAAKAGAFQAFAFAIAAQALAAAOgMQABAAAAgBQAAgTAMgMQANgPAYAAQAIAAAFACQAGACABAAQACAAAIgCQAHgCADAAQAEAAAAADQAAABgEAQQgFAQAAAKQAAAJAJAAQAEAAAFgFQABgCACAAQAAgBABAAQADAAAAAEQAAADgEAFQgCACgBACQAAgFADgKgAKkgcQgJAAgGAOQgFAMAAALQAAAMAJAAQAHAAAFgMQAGgLAAgTQAAgHgHAAgAJxAIQADgCABAAQADAAAAADQAAADgFAFQAAAAgBABQgBgEAAgGgAGQAIQACgKAEgPQALgoAAgSQAAgMgKAAQgDAAAAgDQAAgEAIgFQAJgEAJAAQAVAAAAATQAAASgOAqQANgOASAAQAUAAAAAQQAAAFgDALQgEAJAAAGQAAAKAFAAQAEAAADgDQADgCABAAQACAAAAADQAAACgDAEQgLANgNAAQgXAAAAgSQAAgHAEgLQAEgMAAgEQAAgGgGAAQgIAAgHAPQgDAGgDAOQgEANAAAFQAAAFgFAAQgRAAgEAAQgFAAAAgFQAAgCABgHQABgGADgIQABgBABAAQADAAAAADIgCAEQgDAEgEAEQgEADgEAEQgMAHgKAAQgTAAgFgNQgLANgRAAQgSAAgEgNQgMANgRAAQgJAAgFgFIgEgHQgNAMgSAAQgLAAgHgHQgFgEgBgHQgIAJgHAEQgMAHgPAAQgbAAgIgRQgNAPgSAAQgWAAAAgSQAAgHAEgLQAEgMAAgEQAAgGgGAAQgHAAgIAPQgDAGgDAOQgEANAAAFQAAAFgFAAQgRAAgEAAQgEAAAAgFQAAgIAKgoQALgoAAgSQAAgMgJAAQgEAAAAgDQAAgEAIgFQAJgEAJAAQAVAAAAATQAAASgOAqQANgOASAAQAVAAAAAQQAAAFgEALQgEAJAAAGQAAAIAIAAQAEAAAFgFQAAAAABgBQACgCABAAQADAAAAAEQAAACgDAGQgDgEAAgGQgBgDAAgEQAAgRAOgNQAOgNAXAAQAYAAAAARQAAALgLAJQgMAHgRACQAAAGAEAEQAFAEAJAAQALAAAPgMQAAAAABgBQAAgTALgMQAOgPAYAAQAHAAAGACQAGACABAAQACAAAHgCQAIgCADAAQADAAAAADQAAABgEAQQgEAQAAAKQAAAJAIAAQAEAAAFgFQAAAAABAAQACgDABAAQAEAAAAAEQAAADgEAFQgBABgBABQgBgEAAgFQAAgBAAgBQABgLAIgaQAJgeAAgUQAAgMgJAAQgEAAAAgDQAAgEAIgFQAJgEAKAAQAJAAAGAFQAFAFAAAJQAAAJgJAkQgKAkAAALQAAAJAIAAQAEAAAFgFQAAAAAAAAQAAgIAEgLQAEgNAAgFQAAgCgDAAQgEgBAAgDQAAgHAEAAQARAAAOgWQADgGAEAAQADAAAAAEQAAAFgDAOQAAAFAIAAQAEAAAAADQAAADgCADQgCACgCAAQgIAAgCAIQgFARAAAKQAAAJAJAAQAFAAAIgIQABgBACAAgADwgcQgKAAgFAOQgFAMAAALQAAAMAIAAQAIAAAFgMQAGgLAAgTQAAgHgHAAgAFVAMQADgDABAAQADAAAAAEQAAADgEAFQgBABgBABQgBgEAAgGQAAAAAAgBgACmgXQAAgGgGAAQgFAAgGAIQgFAIAAAKQAJgCAHgHQAGgGAAgFgAC9AIQADgCABAAQADAAAAADQAAADgFAFQgBABAAAAQgBgEAAgGgAgmgwQAAAFADADQAEACAMAAQADAAAAADQAAAIgFAAQgMAAgFAEQgFADgCAIQgGAjgGAUQgDAMgPAKQgNAIgIAAQgEAAAAgEQACgDABgCQAGgIADgMQADgNAFgbQAEgXAAgDQAAgFgEAAQgEAAAAgEQAAgCACgCQABgDACAAQAGAAABgGQAKgoAjAAQALAAAHAFQAGAEAAAHQAAANgMAAQgHAAgCgIQgCgHgCAAQgEAAgDAIQgDAHAAAHgAhtgHQgJgEAAgGQAAgDACgDQABgCAAgBQAAgBgCAAQgDAAgEACQgLAKAAARQAAAJAEAEQAEAFAHAAQAHAAAFgGQAEgGAAgGQAAgHgFgCgAhWgMQAAAUgMAPQgNAPgWAAQgQAAgJgJQgKgIAAgPQAAgSAOgNQAOgPAYAAQANAAAJAIQAIAIAAAMgAkGANQAAAKAGAAQAGAAAAgGQAAgIgMgIQgNgIAAgKQAAgLAKgGQAKgGAOAAQAZAAAAARQAAAMgLAAQgDAAgDgCQgDgDAAgDQACgGAAgCQAAgDgEAAQgDAAgCADQgCACAAADQAAAHANAJQANAIAAAJQAAAMgJAHQgJAHgPAAQgOAAgJgGQgJgFAAgKQAAgFAEgEQADgDAEAAQALAAAAAJgAnGAIQAAgTALgMQAOgPAYAAQAHAAAGACQAGACABAAQACAAAIgCQAHgCADAAQAEAAAAADQAAABgEAQQgFAQAAAKQAAAJAIAAQAFAAAFgFQABgCACAAQAAgCABgCQAFgVAAgHQgCgFAAgDQAAgDAJgDQAHgCALAAQAIAAAAAFIgBAKQAHgPAOAAQALAAAAALQAAAIgEAGQgFAGgHAAQgKAAAAgKQgDABgFAKQgDAGgEALQgDANAAAHQAAAFgFAAQgRAAgDAAQgFAAAAgFQAAgBABgFQgMALgPAAQgJAAgGgFIgEgHQgNAMgRAAQgLAAgHgHQgFgEgCgHQgTAUgXAAQgnAAAAgiQAAgRAOgNQAOgNAXAAQAYAAAAARQAAALgLAJQgLAHgSACQAAAGAEAEQAFAEAJAAQAMAAAOgMQAAAAABgBgAldAKQAAgBABAAQADAAAAAEQAAADgEAFQgCACgBACQAAgFADgKgAmTgcQgJAAgGAOQgFAMAAALQAAAMAIAAQAIAAAFgMQAGgOAAgQQAAgHgHAAgAncgXQAAgGgGAAQgGAAgFAIQgGAIAAAKQAJgCAIgHQAGgGAAgFgApvgeQAAgDAIgDQAIgCALAAQAIAAAAAFQAAAFgEAQQgEAOAAAIQAAAIAGAAQAHAAAIgKQAHgLAAgTQgCgFAAgDQAAgDAJgDQAHgCALAAQAIAAAAAFQAAADgCAJQgDAPgEAUQgHAqgIASQgOAfgdAAQgNAAgKgHQgJgIAAgMQAAgNAIgIQAGgGAGAAQADAAAAACQAAABgBACQgBADAAACQAAAMAOAAQAUAAAHgzQgQAOgUAAQgKAAgFgFQgGgFAAgIQAAgJAEgOQAEgNAAgEQgCgFAAgDgAnFASQgBgEAAgGQACgCACAAQADAAAAADQAAAEgFAEQgBABAAAAgAqig4QAAAjgTAcQgUAfgdAAQgRAAgLgMQgLgNAAgXQAAgnAUgcQAUgbAbAAQASAAAKALQAMAMAAAZgArrAGQAAAHADAGQADAFAGAAQAMAAAJgkQAHgeAAggQAAgSgKAAQgMAAgJAcQgJAbAAArgAsrhjQATAAAHgEQAEAAAAADQAAAEgEAJQgFAKgHADQgDACgIAAQgGAAgTgEQgCAMgFALQADAAAHAAQARAAALAKQANAKAAARQAAAWgOAPQgOAPgVAAQgTAAgKgMQgJgMAAgQQAAgGAEAAQACAAACAFQAFAOARAAQAKAAAGgIQAGgHAAgLQAAgIgEgGQgFgIgLAAIgJABIgCAAQgIAAAAgIQAAgBAFgPQAFgRABgLQABgFADgEQADgDAFAAQACAAAHACQAJABALAAg");
	this.shape_3.setTransform(99.4,14.25);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,0.1,195,47.6);


(lib.CTA = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#79232F").s().p("AgBAXIANgXIgNgWIAMAAIAOAWIgOAXgAgYAXIAOgXIgOgWIAMAAIAOAWIgOAXg");
	this.shape.setTransform(21.325,-0.625);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#79232F").s().p("AgTAXQgIgIAAgOQAAgMAHgIQAIgKANAAQAOAAAHAJQAGAIAAAMIgBAGIglAAQABAFAFAEQAEACAGAAQAJAAAHgCIADAMQgKADgLAAQgPAAgIgHgAALgGQAAgEgCgDQgDgEgGAAQgDAAgEADQgCAEgBAEIAVAAIAAAAg");
	this.shape_1.setTransform(10.95,4.55);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#79232F").s().p("AgRAeIAAgnIAAgTIAPAAIABALIAAAAQABgGAFgDQAEgDAFAAIAEAAIAAARIgFAAQgKAAgCAJIgBADIAAAeg");
	this.shape_2.setTransform(5.725,4.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#79232F").s().p("AgVAXQgJgJAAgOQAAgNAJgIQAIgJAOAAQANAAAIAJQAJAIAAANQAAAOgKAJQgJAIgMAAQgNAAgIgIgAgIgLQgDAFAAAGQAAAIADAEQADAFAFAAQAFAAAEgEQADgFAAgIQAAgGgDgFQgDgGgGAAQgFAAgDAGg");
	this.shape_3.setTransform(-0.225,4.575);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#79232F").s().p("AAaAeIAAgfQAAgNgIAAQgGAAgDAGIAAAEIAAAiIgRAAIAAggQAAgMgIAAQgHgBgCAIIgBAEIAAAhIgRAAIAAgnIgBgTIAQAAIAAAIIABAAQAGgJALAAQALAAAFAKIAAAAQADgFAFgCQAEgDAHAAQAJAAAFAGQAFAHAAAMIAAAig");
	this.shape_4.setTransform(-8.85,4.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#79232F").s().p("AAKAeIAAggQAAgMgKAAQgGAAgBAHIgBAEIAAAhIgSAAIAAgnIgBgTIAQAAIABAIIAAAAQAGgJALAAQAJAAAGAGQAGAHAAAMIAAAig");
	this.shape_5.setTransform(11.65,-4.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#79232F").s().p("AgRAeIAAgnIAAgTIAPAAIABALIAAAAQABgGAFgDQAEgDAFAAIAEAAIAAARIgFAAQgKAAgCAJIgBADIAAAeg");
	this.shape_6.setTransform(6.125,-4.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#79232F").s().p("AgVAZQgFgFAAgHQAAgMAKgEQAJgGAPAAIAAgBQAAgHgKAAQgJAAgHAEIgEgMQAKgFAMAAQAaAAAAAaIAAATIABAOIgRAAIgBgGQgGAIgKAAQgIAAgGgGgAgIALQAAAHAHAAQADAAACgCQADgCABgDIAAgDIAAgGIgBAAQgPAAAAAJg");
	this.shape_7.setTransform(0.325,-4.425);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#79232F").s().p("AgTAXQgIgIAAgOQAAgMAHgIQAJgKAMAAQAOAAAHAJQAGAIAAAMIgBAGIgkAAQAAAFAEAEQAFACAGAAQAIAAAIgCIADAMQgKADgMAAQgOAAgIgHgAALgGQAAgEgCgDQgDgEgGgBQgDAAgEAEQgDAEAAAEIAVAAIAAAAg");
	this.shape_8.setTransform(-5.8,-4.45);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#79232F").s().p("AgYAoIAAhQIASAAIAABBIAfAAIAAAPg");
	this.shape_9.setTransform(-11.775,-5.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.CTA, new cjs.Rectangle(-29.3,-12.5,58.7,25), null);


(lib.Since_50_1971 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Since
	this.instance = new lib.HealthPoint_Sinceai("synched",0);
	this.instance.setTransform(-22.25,48.1,1.27,1.27,0,0,0,18.2,5.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// 1971
	this.instance_1 = new lib.HealthPoint_1971ai("synched",0);
	this.instance_1.setTransform(25.3,47.95,1.27,1.27,0,0,0,13.6,5.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// 50
	this.instance_2 = new lib.HealthPoint_50onlyai("synched",0);
	this.instance_2.setTransform(0.1,0.05,0.55,0.55,0,0,0,73,60.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Since_50_1971, new cjs.Rectangle(-45.3,-33.4,87.69999999999999,88.3), null);


(lib.HP_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HealthPointLogoai("synched",0);
	this.instance.setTransform(-0.05,0,1,1,0,0,0,154.3,30);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HP_logo, new cjs.Rectangle(-154.3,-30,308.70000000000005,60), null);


(lib.HEAD1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.instance = new lib.HEAD_50_2linesai("synched",0);
	this.instance.setTransform(-142.15,-104.3,2.33,2.33,0,0,0,-5.8,-1.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1, new cjs.Rectangle(-128.5,-99.7,454.3,111), null);


// stage content:
(lib.HP_notdone_320x50 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,119];
	// timeline functions:
	this.frame_0 = function() {
		if(!this.alreadyyExecuted){
		this.alreadyyExecuted=true;
			this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
		} else {
		gotoAndPlay(2);
		}
	}
	this.frame_119 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(119).call(this.frame_119).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,2,0,3).p("A46j0MAx1AAAIAAHpMgx1AAAg");
	this.shape.setTransform(160,25);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(120));

	// logo
	this.instance = new lib.HP_logo();
	this.instance.setTransform(102.65,25.3,0.572,0.572,0,0,0,0.6,0.5);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(95).to({_off:false},0).wait(25));

	// HEAD1
	this.instance_1 = new lib.HEAD1();
	this.instance_1.setTransform(116.7,45.6,0.44,0.44,0,0,0,0.2,0.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({_off:true},95).wait(25));

	// Since 50 1971
	this.instance_2 = new lib.Since_50_1971();
	this.instance_2.setTransform(231.05,20,0.47,0.47,0,0,0,0.1,0.1);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(95).to({_off:false},0).wait(25));

	// CTA
	this.instance_3 = new lib.CTA();
	this.instance_3.setTransform(283.9,27.25);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(119).to({_off:false},0).wait(1));

	// bkgd
	this.instance_4 = new lib._300x250_bkgd();
	this.instance_4.setTransform(-2,-217,0.54,0.54);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(120));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(158,-192,164,245);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 320,
	height: 50,
	fps: 24,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/HP_notdone_320x50_atlas_1.jpg?1619376206823", id:"HP_notdone_320x50_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;