(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"HP_notdone_728x90_atlas_1", frames: [[0,0,600,1200],[0,1202,600,540]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib._300x600_bkgd = function() {
	this.initialize(ss["HP_notdone_728x90_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._300x600_watermelon = function() {
	this.initialize(ss["HP_notdone_728x90_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.watermelon = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib._300x600_watermelon();
	this.instance.setTransform(-150,-135,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.watermelon, new cjs.Rectangle(-150,-135,300,270), null);


(lib.HealthPointLogoai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HealthPointLogo.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#858E23").s().p("AhuDsQgKgGAUgwQATgvAYggQA5hOARg9QAJgggPgpQgIgXgZgtQgeg2BDgEQAZgCAaAGQAZAFACAHIACADQAYA5gFBDQgFBAgdA6QgQAfgdAlQgRAWgiApQgdAkgTARQgZAXgQAAIgFgBg");
	this.shape.setTransform(47.9903,36.3577);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#91190E").s().p("AggBTQgbgdgZgnQgdgugCgeQgDgrAvAGQAVACBCAZQAVAHASgMQATgLAMADQAFACAFAEQAbARgJAoQgJAhgcAkQgaAigZAMQgNAGgLAAQgSAAgQgRg");
	this.shape_1.setTransform(32.4896,28.7262);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F17C29").s().p("AhADzQgmgcgWheQgShLAEhJQAGhXAkg5QAfgxBjgUQAygKAxgBQAJAAgDAIQgTA4goArIguAqQgcAYgLAWQgdAxAIBWQALBugFAeQgEAXgKAHQgFADgFAAQgJAAgLgJg");
	this.shape_2.setTransform(13.9834,25.2205);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#91190E").s().p("AgYCCIAAirQAAgKgDgEQgDgDgJAAIgJAAQgKAAAAgHQAAgHALAAIAXAAIAAhKQAAgHACgCQABgDAGgDIANgHIAEgBQAEgBABADQACADAAAIIAABUIAjAAQAKAAAAAHQAAAEgCACQgDABgHAAIgNAAQgNAAgEAEQgDAFAAAPIAACNQAAAcADAJQAEAIALAAQAGAAADgBIAJgHQAFgDACAAQABAAAAAAQABAAABAAQAAABABAAQAAAAABABQACACAAADQAAAEgGAFQgNANgXAAQgpAAAAgog");
	this.shape_3.setTransform(302.875,34.0714);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#91190E").s().p("AAhB7QgHAAAAgGQAAgEACgCQACgCAHAAIAGgBQAIgBACgFQACgGAAgTIAAh1QAAgkgJgNQgIgNgZAAQghAAgRAVQgQAVAAAsIAABcQAAAUACAGQACAFAIABIALACQAFAAAAAHQAAAGgHAAIhNAAQgHAAAAgGQAAgHAFAAIALgCQAIgBACgFQACgGAAgTIAAiIQAAgRgCgEQgCgEgHgBIgGgBQgIAAAAgGQAAgFAIgEIAjgSQAGgDAEAAQAIAAAAALIgBATQAfgdAqAAQAlAAAQARQAQAQAAAmIAAB+QAAAUACAGQACAFAIABIAKACQAGAAAAAHQAAAGgHAAg");
	this.shape_4.setTransform(282.475,38.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#91190E").s().p("AglCwQgHAAAAgHQAAgGAFgBIALgBQAIgBACgGQACgGAAgSIAAiLQAAgOgDgFQgDgEgJAAIgBAAQgKAAAAgGQAAgFAHgDIAkgTIAIgDQAIAAAAAJIAAC8QAAAUACAFQACAGAIABIALABQAFABAAAGQAAAHgHAAgAgRiHQgGgHAAgKQAAgJAGgHQAHgHAKAAQAJAAAHAHQAHAHAAAKQAAAJgHAHQgHAHgJAAQgKAAgHgHg");
	this.shape_5.setTransform(262.575,33.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#91190E").s().p("AhUBbQghgjAAg4QAAg4AhgiQAhgiA0AAQA0AAAgAiQAhAjAAA3QAAA5ggAiQggAig2AAQg0AAgggigAg5hOQgXAeAAAwQAAAyAWAdQAWAeAlAAQAkAAAWgeQAVgeAAgyQAAgxgVgdQgVgdglAAQgkAAgWAeg");
	this.shape_6.setTransform(244.475,38.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#91190E").s().p("Ah1DHQgNAAAAgIQAAgHAMgBIAGgBQALAAACgHQADgHAAgaIAAkSQAAgRgLgCIgEAAQgJgBAAgIQAAgMArgNQApgNApAAQA7AAAiAeQAhAeAAA2QAAAzgeAhQgfAfgxAAQgVAAgSgGQgRgGAAgIQAAgDADgBQACgDADAAIAFABIALADQAJACAOAAQAjAAAVgXQAUgaAAgrQAAgtgWgbQgWgagoAAQglAAgMAMQgMANAAAnIAAECQAAAaACAHQAEAHAKAAIAPABQANABAAAHQAAAIgNAAg");
	this.shape_7.setTransform(219.6,30.75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#91190E").s().p("AAhDHQgIAAAAgGQAAgEACgCQACgBAHgBIAGgBQAIAAACgGQACgGAAgTIAAiBQAAgagKgMQgKgLgXAAQgiAAgPAVQgQAUAAAwIAABZQAAATADAGQACAFAIABIAGABQAHABACABQABACAAAEQAAAGgHAAIhMAAQgIAAAAgGQAAgGAGgBIAKgCQAIgBACgFQACgGAAgTIAAkjQAAgOgCgFQgDgEgHgBIgGAAQgHAAAAgGQAAgFAGgCIApgVQACgCADAAQAHAAAAAKIAACtQAegeAsAAQAjAAARAQQARARAAAiIAACDQAAATACAGQACAFAHABIALACQAGABAAAGQAAAGgHAAg");
	this.shape_8.setTransform(190.375,30.725);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#91190E").s().p("AgYCCIAAirQAAgKgDgEQgDgDgKAAIgIAAQgKAAAAgHQAAgHALAAIAXAAIAAhKIABgJQACgDAFgDIAOgHIAEgBQAHgBAAAOIAABUIAjAAQAKAAAAAHQAAAEgCACQgDABgHAAIgNAAQgNAAgEAEQgDAFAAAPIAACNQAAAcADAJQAEAIALAAQAFAAADgBIAKgHQAEgDADAAQABAAAAAAQABAAABAAQAAABABAAQAAAAABABQACACAAADQAAAEgGAFQgOANgWAAQgpAAAAgog");
	this.shape_9.setTransform(169.975,34.0741);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#91190E").s().p("AglDHQgHAAAAgHQAAgEABgBQACgCAHgBIAGAAQAIgBACgGQACgFAAgTIAAkqQAAgKgDgEQgEgDgJAAQgKAAAAgGQAAgGAGgBIAogWIAFgBQAIgBAAAKIAAFVQAAATADAGQACAGAIABIAKABQAFABAAAGQAAAHgHAAg");
	this.shape_10.setTransform(156.675,30.7705);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#91190E").s().p("AhNBrQgXgSAAgeQAAgbAUgWQATgVAkgMQAVgJASAAQALAAgBAIQABAGgLACQgkAHgWATQgUAUgBAcQABAWAOAOQANAPAVAAQAWAAAOgPQAPgPACgZQADgaAAglQAAg/gJgQQgIgRggAAQgbAAgcAUQgHAGgDAAQgKAAABgJQAAgFAFgEQANgNAWgHQAVgIAWAAQAmAAASASQASARAAAmIAAB/QAAASACAGQABAGAHABIACAAIADAAIAGACQAGABgBAGQAAAGgGAAIgpAAQgNAAAAgLIAAgLQgOAPgOAGQgOAGgUAAQgiAAgVgTg");
	this.shape_11.setTransform(138.4,38.525);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#91190E").s().p("AhFBaQgggjAAg2QAAg1AgglQAhgkAwABQAgAAAZATQAaAVAAAYQAAAKgFAGQgFAGgOAJIheA3QgGAFgFgBQgIABAAgIQAAgDACgCIAHgGIA/glQARgKAGgIQAHgHAAgKQAAgSgQgQQgPgOgUAAQgfAAgVAeQgUAeAAAwQAAAxAWAeQAWAdAkAAQAnABAegkQAGgFACgBQAIAAAAAJQAAAIgOANQgfAcguABQgwAAgggkg");
	this.shape_12.setTransform(115.125,38.65);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#91190E").s().p("ABBDEQgNgBAAgHQAAgHAMgCIAGAAQALgBACgHQADgGAAgbIAAh0IgBgXQgBgIgEgCQgEgEgFAAQgFgBgQAAIhrAAQgTAAgEAGQgEAGAAAZIAAB1QAAAbACAGQADAHAKABIAHAAQAMACAAAHQAAAHgNABIhRAAQgOgBAAgHQAAgHAMgCIAHAAQALgBACgHQADgGAAgbIAAkSQAAgcgDgHQgCgGgLgBIgHgBQgMAAAAgIQAAgIANAAIBRAAQANAAAAAIQAAAEgCACQgDABgHABIgGABQgLABgCAGQgCAHAAAbIAABmICpAAIAAhlQABgbgDgIQgCgGgLgBIgGgBQgMAAAAgIQAAgIAMAAIBSAAQANAAAAAIQAAAIgLAAIgHABQgLABgCAGQgDAHAAAbIAAESQAAAbADAHQACAHALABIAHAAQALACAAAHQAAAHgMABg");
	this.shape_13.setTransform(86.475,31.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,308.8,60);


(lib.HealthPoint_Sinceai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HealthPoint_Since.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#71212C").s().p("AgYAdQgMgLAAgSQAAgPALgMQAKgMAQAAQARAAAKANQAJALAAAQIAAAFIg3AAQADAUASAAQALAAAJgKIAKAKQgLAOgTAAQgQAAgLgLgAgTgEIAnAAQgDgUgQAAQgRAAgDAUg");
	this.shape.setTransform(32.95,6.675);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#71212C").s().p("AgXAcQgLgLAAgRQAAgPALgMQALgMAQAAQATAAAMANIgLAMQgJgJgLAAQgIAAgHAHQgGAHAAAJQAAAKAGAIQAHAHAJAAQAKAAAKgKIAKALQgNAOgSAAQgQAAgLgMg");
	this.shape_1.setTransform(25.075,6.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#71212C").s().p("AARAnIAAgrQAAgSgRAAQgGAAgFAFQgFAFAAAJIAAAqIgSAAIAAhLIASAAIAAALQAJgNAOAAQANAAAHAIQAIAIAAAOIAAAvg");
	this.shape_2.setTransform(16.7,6.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#71212C").s().p("AgIA1IAAhMIARAAIAABMgAgJgiIAAgSIASAAIAAASg");
	this.shape_3.setTransform(10.4,5.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#71212C").s().p("AgmAkIALgNQAOANAQAAQATAAgBgNQABgFgFgDQgFgEgMgDQgSgEgHgFQgJgHAAgOQAAgNAKgIQAJgIAPAAQAUAAAQANIgJANQgOgKgNAAQgHAAgFADQgEAEAAAFQAAAGAEADQAGADANAEQAQAEAIAFQAIAIAAAMQAAAOgKAIQgJAIgRAAQgXAAgSgQg");
	this.shape_4.setTransform(3.9,5.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,36.7,10.7);


(lib.HealthPoint_1971ai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HealthPoint_1971.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#71212C").s().p("AACAzIAAhTIgRAFIgEgOIAagJIANAAIAABlg");
	this.shape.setTransform(25.025,5.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#71212C").s().p("AgdAzIAshVIgxAAIAAgQIBGAAIAAAOIgtBXg");
	this.shape_1.setTransform(18.55,5.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#71212C").s().p("AgkAoIAKgNQALAJAMAAQAKAAAHgJQAGgIABgPQgJALgOAAQgQAAgKgJQgKgIAAgOQAAgPAKgKQALgKAQAAQARAAALAKQAMAMAAAbQAAAYgMAPQgLAPgTAAQgSAAgPgMgAgPgeQgFAFAAAIQgBAIAHAFQAFAEAJAAQAJAAAFgEQAGgFAAgIQAAgIgGgFQgGgGgIAAQgJAAgGAGg");
	this.shape_2.setTransform(9.8,5.225);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#71212C").s().p("AACAzIAAhTIgRAFIgEgOIAagJIANAAIAABlg");
	this.shape_3.setTransform(1.975,5.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,27,10.5);


(lib.HealthPoint_50onlyai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HealthPoint_50only.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjIDoQhLhcAAiLQAAiKBMhdQBOhgB6AAQB6AABOBfQBLBcAACLQAACKhMBdQhPBgh5ABQh6gBhOhfgAh1ihQgrBAAABhQAABgAsBAQAtBDBIAAQBIAAAthCQArhAAAhgQAAhggshAQguhDhHAAQhJAAgsBBg");
	this.shape.setTransform(97.575,64.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjoDhIBFhQQBRBLBRAAQA4AAAjgdQAigfAAgxQAAgygkgcQgkgcg6gBQg6AAg7AcIhDgrIASk2IF5AAIAABjIkZAAIgKCUQAxgSAzAAQBhAAA7AyQA/A0AABgQAABihAA7QhAA7hpAAQiEAAhkhhg");
	this.shape_1.setTransform(42.475,65.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#71212C").s().p("AjIDoQhLhcAAiLQAAiKBMhdQBPhgB5AAQB7AABNBfQBLBcAACLQAACKhMBdQhPBgh5AAQh7AAhNhfgAh1igQgrA/AABhQAABgAsBBQAtBCBIAAQBIAAAthCQArg/AAhhQAAhggshAQgthDhIAAQhIAAgtBCg");
	this.shape_2.setTransform(99.45,66.575);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#71212C").s().p("AjoDhIBEhQQBTBMBQAAQA4AAAjgeQAigfAAgyQAAgwgkgdQgkgcg6AAQg6AAg7AcIhDgsIASk2IF5AAIAABjIkZAAIgKCUQA0gSAwAAQBhAAA7AxQA/A0AABiQAABhhAA7QhAA7hpAAQiFAAhjhhg");
	this.shape_3.setTransform(44.375,67.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#AE222D").s().p("Ai4HSQiaihiGjbQijkHgLipQgQjvEFAgQBgAMCVAyID2BaQBGAZA6gLQAngIAygfQA6gkATgHQAsgRAwAQQAcAJAgAUQCYBhg3DhQgtC4ifDNQitDfigAyQgsAOgqAAQhqAAhYhbg");
	this.shape_4.setTransform(67.2247,65.8653);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F9762B").s().p("AmVGWQioioAAjuQAAjtCoioQCoipDtAAQDuAACoCpQCoCoAADtQAADuioCoQioCojuABQjtgBioiog");
	this.shape_5.setTransform(57.425,58.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#8BAC43").s().p("AmVGWQipioAAjuQAAjtCpioQCoioDtAAQDuAACoCoQCoCoABDtQgBDuioCoQioCojuAAQjtAAioiog");
	this.shape_6.setTransform(88.25,57.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,145.7,121.6);


(lib.HEAD1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgTAVQgEgGgBgJQAAgKAJgLQAKgLAKABQAJAAAGAFQAEAGAAAIQAAAMgJAJQgJAMgMAAQgIgBgFgFg");
	this.shape.setTransform(113.15,13.25);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgmBrQgLgLAAgQQAAgPAPgzQAPgyAAgiQAAgVgNAAQgGABAAgFQAAgHAPgIQAPgHAPAAQARAAAKAIQAKAJAAAPQAAAQgQA8QgQA8AAAUQAAAOALAAQAGAAAJgJQAEgDADAAQAFAAABAFQgBAFgGAJQgVAagdAAQgTAAgNgLg");
	this.shape_1.setTransform(105.1,4.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgmBrQgLgLAAgQQAAgPAPgzQAPgyAAgiQAAgVgNAAQgGABAAgFQAAgHAPgIQAPgHAPAAQARAAAKAIQAKAJAAAPQAAAQgQA8QgQA8AAAUQAAAOALAAQAGAAAJgJQAEgDADAAQAFAAAAAFQAAAFgGAJQgVAagdAAQgUAAgMgLg");
	this.shape_2.setTransform(96.2,4.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AACArQgQAVggAAQgVAAgNgMQgOgNAAgWQAAggATgXQAXgZAoAAQAMAAALAEIAMAEQAFAAAOgEQAPgEAEAAQAGAAAAAGIgHAcQgHAaAAASQAAAQAOAAQAHAAAIgIQAEgEADAAQAGAAAAAGQAAAEgHAJQgVAaggAAQgXAAgKgVgAgYgTQgJATAAAVQAAAPAKAAQAKAAAIgaQAGgWAAgVQAAgIgGAAQgKAAgJAWg");
	this.shape_3.setTransform(82.925,9.425);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhCA3QAAgGAIglQAJgjAAgMQAAgHgDgGQAAgGAQgFQAQgEATAAQANAAAAAKIgBAKQAPgSAVAAQAUAAAAATQAAALgGAKQgIAKgMAAQgJAAgFgGQgFgGAAgGQgGACgHANQgGALgGAWQgGAXAAAMQAAAIgJAAIgoACQgIAAAAgJg");
	this.shape_4.setTransform(59.725,9.425);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag0A0QgSgPAAgYQAAgeAXgXQAagZAmAAQAZAAAPAPQAOANAAAWQAAAjgUAWQgVAYglAAQgcAAgRgOgAAEglQgOANAAAeQAAAdAVAAQAKAAAIgJQAGgJAAgLQAAgLgHgEQgQgGAAgJQAAgJAHgIQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBAAgBAAQgEAAgHAGg");
	this.shape_5.setTransform(45.45,9.425);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhTB+QAAgCAGgHQAKgOAFgSQAFgWAJgtIAHguQAAgIgIAAQgHAAAAgFQAAgEAEgFQADgEACAAQAKAAACgKQAQhDA/AAQATAAALAIQAKAHAAALQAAAWgVAAQgMAAgDgMQgDgNgEAAQgGAAgGAOQgFAMAAAKQAAALAEADQAGAEATAAQAFAAAAAFQAAAOgJAAQgTAAgIAGQgGAFgCANQgJA3gIAnQgFATgdARQgYANgOAAQgIAAAAgGg");
	this.shape_6.setTransform(35.025,8.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag3A0QgUgOAAgcQAAgeAYgVQAZgXAmAAQAUAAALAJQALAIAAAPQAAASgRAOQgSAOgbAAQAAAIAIAHQAKAFAOAAQASAAATgRQAGgFADAAQAGAAAAAFQAAAFgJAJQgiAigoAAQgeAAgSgNgAgDgfQgHAMAAAOQAMgDAJgLQAHgIAAgJQAAgHgHAAQgIAAgGAMg");
	this.shape_7.setTransform(16.125,9.45);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhCA3QAAgGAIglQAJgjAAgMQAAgHgDgGQAAgGAQgFQAQgEATAAQANAAAAAKIgBAKQAPgSAVAAQAUAAAAATQAAALgGAKQgIAKgMAAQgJAAgFgGQgFgGAAgGQgGACgHANQgGALgGAWQgGAXAAAMQAAAIgJAAIgoACQgIAAAAgJg");
	this.shape_8.setTransform(2.025,9.425);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AACArQgQAVggAAQgVAAgNgMQgOgNAAgWQAAggATgXQAXgZAoAAQAMAAALAEIAMAEQAFAAAOgEQAPgEAEAAQAGAAAAAGIgHAcQgHAaAAASQAAAQAOAAQAHAAAIgIQAEgEADAAQAGAAAAAGQAAAEgHAJQgVAaggAAQgXAAgKgVgAgYgTQgJATAAAVQAAAPAKAAQAKAAAIgaQAGgWAAgVQAAgIgGAAQgKAAgJAWg");
	this.shape_9.setTransform(-12.725,9.425);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag4A0QgSgOAAgaQgBggAYgVQAZgXAlAAQAWAAALAIQALAIAAAMQAAANgHAJQgIAIgLAAQgQAAAAgPQAAgFACgFQAEgEgBgCQAAgFgFAAQgIAAgHALQgIANAAAUQAAAOAJAIQAJAIAPAAQARAAAWgQQAGgEACAAQAFAAABAEQAAAGgJAJQgiAigpAAQgeAAgSgNg");
	this.shape_10.setTransform(-28.55,9.45);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAHBuQgKgJAAgOQAAgMAGgTQAGgVAAgGQAAgIgIAAQgJAAgMAXQgFAKgGAXQgFAWAAAIQAAAJgJAAIgqACQgHAAAAgJQAAgOARhDQAShDAAgfQAAgVgNAAQgGABAAgFQAAgHAPgIQAPgHAQAAQARAAAKAIQAJAJAAAPQAAAagWBIQATgXAgAAQAkAAAAAbQAAAKgGATQgGASAAALQAAAKAKAAQAHAAAJgJQAEgDADAAQAFAAAAAFQAAAFgGAJQgVAagfAAQgSAAgMgIg");
	this.shape_11.setTransform(-51.575,4.05);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AguBLQgKgKAAgRQAAgOAGgVQAHgWAAgJQAAgCgGgCQgFgBAAgEQAAgMAHAAQAcAAAbgmQAGgIAGAAQAHgBAAAIQgGAYAAAHQAAAIANAAQAGAAAAAFQAAAOgKgBQgMABgEANQgIAdAAAPQAAAQAPAAQAIAAAOgLQAGgGACABQAGAAAAAEQAAAEgFAGQgKANgRALQgVAMgSgBQgVAAgLgLg");
	this.shape_12.setTransform(-65.175,7.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgmBrQgMgLAAgQQABgPAPgzQAQgyAAgiQAAgVgOAAQgGABAAgFQAAgHAPgIQAQgHAPAAQAQAAAKAIQAKAJAAAPQAAAQgQA8QgQA8AAAUQAAAOALAAQAGAAAJgJQAEgDADAAQAGAAAAAFQAAAFgHAJQgUAageAAQgUAAgMgLg");
	this.shape_13.setTransform(-74.65,4.05);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AACArQgQAVggAAQgVAAgNgMQgOgNAAgWQAAggATgXQAXgZAoAAQAMAAALAEIAMAEQAFAAAOgEQAPgEAEAAQAGAAAAAGIgHAcQgHAaAAASQAAAQAOAAQAHAAAIgIQAEgEADAAQAGAAAAAGQAAAEgHAJQgVAaggAAQgXAAgKgVgAgYgTQgJATAAAVQAAAPAKAAQAKAAAIgaQAGgWAAgVQAAgIgGAAQgKAAgJAWg");
	this.shape_14.setTransform(-87.925,9.425);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag3A0QgUgOAAgcQAAgeAYgVQAZgXAmAAQAUAAALAJQALAIAAAPQAAASgRAOQgSAOgbAAQAAAIAIAHQAKAFAOAAQASAAATgRQAGgFADAAQAGAAAAAFQAAAFgJAJQgiAigoAAQgeAAgSgNgAgDgfQgHAMAAAOQAMgDAJgLQAHgIAAgJQAAgHgHAAQgIAAgGAMg");
	this.shape_15.setTransform(-103.775,9.45);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAHBuQgKgJAAgOQAAgMAGgTQAGgVAAgGQAAgIgIAAQgJAAgMAXQgFAKgGAXQgFAWAAAIQAAAJgJAAIgqACQgHAAAAgJQAAgOARhDQAShDAAgfQAAgVgNAAQgGABAAgFQAAgHAPgIQAPgHAQAAQARAAAKAIQAJAJAAAPQAAAagWBIQATgXAgAAQAkAAAAAbQAAAKgGATQgGASAAALQAAAKAKAAQAHAAAJgJQAEgDADAAQAFAAAAAFQAAAFgGAJQgVAagfAAQgSAAgMgIg");
	this.shape_16.setTransform(-119.625,4.05);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhCA3QAAgGAIglQAJgjAAgMQAAgHgDgGQAAgGAQgFQAQgEATAAQANAAAAAKIgBAKQAPgSAVAAQAUAAAAATQAAALgGAKQgIAKgMAAQgJAAgFgGQgFgGAAgGQgGACgHANQgGALgGAWQgGAXAAAMQAAAIgJAAIgoACQgIAAAAgJg");
	this.shape_17.setTransform(163.625,-18.525);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag0A0QgSgPAAgYQAAgeAXgXQAagZAmAAQAZAAAPAPQAOANAAAWQAAAjgUAWQgVAYglAAQgcAAgRgOgAAEglQgOANAAAeQAAAdAVAAQAKAAAIgJQAGgJAAgLQAAgLgHgEQgQgGAAgJQAAgJAHgIQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBAAgBAAQgEAAgHAGg");
	this.shape_18.setTransform(149.4,-18.525);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhTB+QAAgCAGgHQAKgOAFgSQAFgWAJgtIAHguQAAgIgIAAQgHAAAAgFQAAgEAEgFQADgEACAAQAKAAACgKQAQhDA/AAQATAAALAIQAKAHAAALQAAAWgVAAQgMAAgDgMQgDgNgEAAQgGAAgGAOQgFAMAAAKQAAALAEADQAGAEATAAQAFAAAAAFQAAAOgJAAQgTAAgIAGQgGAFgCANQgJA3gIAnQgFATgdARQgYANgOAAQgIAAAAgGg");
	this.shape_19.setTransform(138.975,-19.275);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AguBLQgKgKAAgSQAAgNAGgWQAHgUAAgJQAAgDgGgCQgFgBAAgEQAAgMAHAAQAcAAAbgmQAGgJAGAAQAHABAAAGQgGAZAAAHQAAAIANAAQAGAAAAAEQAAAPgKAAQgMAAgEAMQgIAeAAAPQAAAQAPAAQAIAAAOgLQAGgFACgBQAGAAAAAGQAAADgFAHQgKAMgRAKQgVANgSAAQgVAAgLgMg");
	this.shape_20.setTransform(121.975,-20.75);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAHBtQgKgIAAgOQAAgMAGgUQAGgTAAgIQAAgHgIAAQgJAAgMAXQgFAJgGAYQgFAWAAAJQAAAIgJAAIgqACQgHAAAAgJQAAgPARhDQAShDAAgfQAAgTgNAAQgGgBAAgEQAAgHAPgHQAPgIAQAAQARAAAKAJQAJAIAAAOQAAAbgWBHQATgVAgAAQAkgBAAAbQAAALgGARQgGATAAAKQAAALAKAAQAHAAAJgJQAEgEADAAQAFAAAAAHQAAAEgGAIQgVAbgfAAQgSAAgMgJg");
	this.shape_21.setTransform(108.025,-23.9);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AhFBuQgRgOAAgVQAAgVAPgOQAMgMALABQAFAAAAADIgCAGQgCAEAAAGQAAASAUAAQAegBAMhKQgPAPgaAAQgVAAgOgMQgNgOAAgUQAAghAUgWQAXgaAoAAQANAAAKADIANAFQADAAANgFQAOgDAGAAQAGAAAAAGIgFATQgGAZgHApQgLBFgOAeQgYA2gxgBQgXABgRgNgAgEhNQgJAUAAAUQAAAPAKABQAJgBAIgZQAHgXAAgWQAAgHgHAAQgKAAgIAWg");
	this.shape_22.setTransform(90.475,-12.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgBAqQgTAWgmAAQgQAAgJgIQgJgJAAgOQgBgOAIgYQAGgYAAgGQAAgHgDgGQAAgGARgFQAQgEATAAQANAAAAAKQAAAIgHAZQgIAYABAQQAAAKAKAAQAGAAAIgPQAOgYAAgaQAAgHgDgGQAAgGAQgFQAQgEATAAQAOAAAAAKQAAAHgHAaQgIAYAAANQABAOAKAAQAIAAAIgIQAEgEADAAQAGAAAAAGQAAAEgHAJQgUAagfAAQggAAgFgWg");
	this.shape_23.setTransform(74.85,-18.525);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("Ag0A0QgSgPAAgYQAAgeAXgXQAagZAnAAQAYAAAPAPQAOANAAAWQAAAjgUAWQgUAYgmAAQgbAAgSgOgAAEglQgNANAAAeQgBAdAVAAQAKAAAIgJQAGgJABgLQgBgLgHgEQgQgGAAgJQAAgJAHgIQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBAAgBAAQgEAAgHAGg");
	this.shape_24.setTransform(57.8,-18.525);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AhTB+QAAgCAGgHQAKgOAFgSQAFgWAJgtIAHguQAAgIgIAAQgHAAAAgFQAAgEAEgFQADgEACAAQAKAAACgKQAQhDA/AAQATAAALAIQAKAHAAALQAAAWgVAAQgMAAgDgMQgDgNgEAAQgGAAgGAOQgFAMAAAKQAAALAEADQAGAEATAAQAFAAAAAFQAAAOgJAAQgTAAgIAGQgGAFgCANQgJA3gIAnQgFATgdARQgYANgOAAQgIAAAAgGg");
	this.shape_25.setTransform(47.375,-19.275);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("Ag3A0QgUgPAAgcQAAgdAYgWQAZgWAmAAQAUAAALAJQALAJAAANQAAAUgRANQgSANgbAAQAAAKAIAFQAKAHAOAAQASAAATgSQAGgFADAAQAGAAAAAGQAAAEgJAJQgiAigoAAQgeAAgSgNgAgDgfQgHANAAANQAMgDAJgKQAHgKAAgIQAAgHgHAAQgIAAgGAMg");
	this.shape_26.setTransform(28.475,-18.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AhJAhQAAgPAHgXQAHgYAAgGQAAgHgDgGQAAgGARgFQAPgEATAAQANAAAAAKQAAAJgGAaQgIAZAAANQAAAKAJAAQAKAAALgPQAMgPAAgPQAAgDgFgHQgFgHAAgIQAAgKAIgHQAHgGALAAQAcAAAAAbQAAAhgkAhQglAignAAQgjAAAAgfg");
	this.shape_27.setTransform(13.075,-18.525);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgbAkQAAgDAGgKQAHgLAAgLQAAgDgCgGQgCgHAAgEQgBgKAHgGQAGgGAKAAQAYAAAAAXQAAATgVAWQgSATgJAAQgHAAAAgGg");
	this.shape_28.setTransform(7.95,-32.425);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("Ag3A0QgUgPAAgcQAAgdAYgWQAZgWAmAAQAUAAALAJQALAJAAANQAAAUgRANQgSANgbAAQAAAKAIAFQAKAHAOAAQASAAATgSQAGgFADAAQAGAAAAAGQAAAEgJAJQgiAigoAAQgeAAgSgNgAgDgfQgHANAAANQAMgDAJgKQAHgKAAgIQAAgHgHAAQgIAAgGAMg");
	this.shape_29.setTransform(-1.875,-18.5);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAAA4QgMgHgFgKQgaAZghAAQgSAAgLgJQgKgJAAgOQAAgPAGgWQAHgWAAgIQAAgHgCgGQAAgGAQgFQAQgEATAAQANAAAAAKQAAAIgHAZQgGAXAAAOQAAAOAKAAQAKAAAIgQQALgVAAgdQAAgHgDgGQAAgGARgFQAOgEATAAQAOAAAAAKQAAAJgHAYQgGAYAAANQAAANANAAQAJAAAIgNQAJgOAAgPQAAgGgGgHQgGgIAAgHQAAgKAHgHQAIgGALAAQAMAAAJAIQAIAIAAAOQAAAhgWAdQgaAjgkAAQgTAAgNgIg");
	this.shape_30.setTransform(-21.425,-18.525);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgbAjQAAgCAHgKQAGgKAAgMIgCgKQgDgGAAgEQAAgJAHgHQAGgGAKAAQAYAAAAAXQAAAUgVAVQgSATgJAAQgHAAAAgHg");
	this.shape_31.setTransform(-43.275,-12.55);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgzBtQAAgjAgh+QgNAFgHAAQgDAAgCgDIgDgFQABgHAGgFIAugkQAGgGAKgEIALgEQAJAAAFAEQAGAFgBAGQAAAEgEANIgKAjQgfB4AAAmQAAAIgIAAIgrACQgHAAAAgJg");
	this.shape_32.setTransform(-49.85,-23.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AhMBuQAAgeAbg4QAdg5AggfQgLgEgYAAQgiAAgLAGQgGAAAAgFQAAgGAIgQQAKgUAJgFQAHgDAMAAQAQAAAvAFQAMAAAMgEQAFAAAHALQAGAKAAAHQAAADgGAGIgPAOQgbAdgUA4QgRAzAAAfQAAAKgKAAQgpAGgLAAQgGAAAAgIg");
	this.shape_33.setTransform(-61.375,-23.875);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AhEBjQgOgRAAgQQAAgJAHAAQACAAAIAHQALAJARAAQAXAAAQgTQAPgSABgWQgOASgeAAQgaAAgQgQQgPgQAAgaQAAgjAYgbQAageAqAAQAhAAAUASQAWAUAAApQAABLggArQgdAogvAAQgaAAgSgUgAgQhHQgIAUAAAaQAAAZAQAAQAKAAAJgUQAIgTAAgYQAAgdgPAAQgLAAgJAVg");
	this.shape_34.setTransform(-78.475,-23.975);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("Ag0BtQABgjAgh+QgNAFgHAAQgCAAgDgDIgCgFQgBgHAIgFIAtgkQAGgGAKgEIAMgEQAHAAAGAEQAFAFAAAGQAAAEgDANIgLAjQgfB4AAAmQAAAIgIAAIgrACQgIAAAAgJg");
	this.shape_35.setTransform(-92.55,-23.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("Ag3A0QgUgPAAgcQAAgdAYgWQAZgWAmAAQAUAAALAJQALAJAAANQAAAUgRANQgSANgbAAQAAAKAIAFQAKAHAOAAQASAAATgSQAGgFADAAQAGAAAAAGQAAAEgJAJQgiAigoAAQgeAAgSgNgAgDgfQgHANAAANQAMgDAJgKQAHgKAAgIQAAgHgHAAQgIAAgGAMg");
	this.shape_36.setTransform(-112.225,-18.5);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("Ag4A0QgSgPgBgaQAAgfAYgWQAYgWAmAAQAWAAALAIQALAIAAAMQAAANgHAIQgIAJgLAAQgQAAAAgPQgBgEADgGQADgEAAgCQAAgFgFAAQgIAAgHALQgIAOAAASQAAAOAJAJQAJAIAPAAQARAAAWgPQAGgFACAAQAGAAAAAFQAAAFgJAJQgiAigpAAQgeAAgSgNg");
	this.shape_37.setTransform(-126.1,-18.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAIA3QgMgJAAgNQAAgNAGgTQAGgSABgHQAAgIgIAAQgIAAgMAXQgFAKgHAUQgFAVAAAMQgBAIgIAAIgpACQgIAAAAgJQAAgGAIglQAJgjAAgMQAAgHgDgGQAAgGARgFQAPgEASAAQAOAAAAAKQAAAHgCAJQAGgJANgHQARgKAQAAQAhAAAAAZQAAAKgFAUQgGATAAAIQAAAMALAAQAGAAAJgIQAFgEACAAQAGAAAAAGQAAAEgGAJQgVAagfAAQgRAAgMgJg");
	this.shape_38.setTransform(-141.9,-18.525);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgmBdQgMgKAAgOQAAgPAHgWQAGgYABgGQAAgGgDgGQAAgGAQgEQAQgFASAAQANAAAAAKQABAHgHAYQgGAYgBAQQAAAGAEAEQAEADAFABQAGAAAIgJQAFgEADAAQAFAAAAAGQAAAEgGAJQgVAbgeAAQgTAAgNgKgAgTg1QgHgGAAgJQAAgNAJgKQAJgKANAAQALAAAHAGQAJAGgBAJQAAAOgKALQgJAJgMAAQgLAAgIgHg");
	this.shape_39.setTransform(-155.05,-22.35);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AhMB5QgYgSAAgcQAAgZAYgRQAVgNAaAAQARAAAAAHQAAAFgHAFQgWAPAAAZQAAAOAIAIQAIAIANAAQANAAAJgOQAKgNgBgUQABgfgaglQgOgUgEgIQgJgQAAgRQAAgdAcgVQAXgRAdAAQAZAAAPAMQAOALAAAVQAAAPgIAKQgJAKgMAAQgIAAgHgEQgFgGAAgJQgBgHAHgIQAHgJAAgFQAAgJgLAAQgKAAgGAJQgHAIAAANQAAAQAJAQQAEAIAQAUQAcAkAAAfQAAAnghAcQgfAbgrAAQgiAAgXgQg");
	this.shape_40.setTransform(-170.15,-25.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1, new cjs.Rectangle(-218.5,-58.7,427.5,131.5), null);


(lib.HEAD_NotDoneai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HEAD_NotDone.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#70202C").s().p("AJZCFQgMgJAAgPQAAgQAKgKQAIgIAIAAQAAAAABAAQABABAAAAQAAAAABABQAAAAAAABIgBAEIgCAHQAAAOARAAQAPAAAJgVQAGgOAEgcQgSASgbAAQgLAAgIgHQgHgGAAgKQAAgLAFgSQAFgRAAgEIgBgGIgBgEQAAgFAKgDQAKgDANAAQAKAAAAAIQAAAGgFATQgFASAAAKQAAAJAIAAQAKAAAJgNQAIgMAAgYIgBgGIgBgEQAAgFAKgDQAKgDANAAQALAAAAAIIgDAOIgJAtQgJAzgKAWQgRAmgkAAQgRAAgLgJgArtAxQgKgKgCgQQgcAkgiAAQgQAAgJgKQgJgJAAgQQAAgUARgrQARgtAAgcQAAgMgNAAQgRAAgPATQgOASAAASQAAAPAMAAQAEAAAGgDQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABQAAAIgKAKQgNAMgPAAQgNAAgJgJQgJgKAAgPQAAgkAggZQAdgXAlAAQAVAAANAKQANALAAATQAAAXgMAlQgNAlAAAMQAAAGAEAEQADADAEAAQARAAAQgZQAIgMAHgYQAGgVAAgJIgBgKQAAgGAPgHQAMgFAGAAQALAAAAALQAAAKgKAlQgLAkAAAKQAAAPAMAAQAUAAAUgqQAMgdAAgkQAAgcgTAAQgFAAAAgFQAAgGAJgIQALgIANAAQAdAAAAAfQAAAmgeA9QgPAegTATQgWAVgUAAQgPAAgKgKgALYAxQgOgLAAgVQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAKAAQAKAAAKgGIANgKIABgBQABgIAEgLQAEgPAAgHQAAgBAAAAQAAAAgBgBQAAAAgBAAQgBAAgBgBQgEgBAAgDIABgFQACgEACAAQALAAALgJQAKgIAGgLQAFgGADAAQAFAAAAAFQAAAGgEARQAAABAAABQAAABABAAQAAABAAAAQAAABABAAQACABAGAAQAEAAAAAEQAAAKgHAAQgKAAgCAJQgHAXAAAKQAAANAMAAQAEAAAFgEIAIgGIAFgDQAEAAAAAEQAAACgCAEQgIAJgLAIQgPAKgMAAQgQAAgIgJQgFgFgCgIQgWAXgdAAQgWAAgMgKgAL8gOQgHAKAAAMQALgDAJgIQAIgIAAgGQAAgHgHAAQgHAAgHAKgAHBAxQgGgFgDgHIgBABQgQAUgWAAQgNAAgHgHQgIgGAAgKQAAgKAFgNQAFgNAAgFQAAgJgHAAQgJAAgKASQgEAIgEAPQgFAQAAAIQAAAGgGAAIgaACQgGAAAAgHQAAgFAHgbQAGgaAAgIIgBgGIgBgEQAAgFAKgDQAKgDANAAQAKAAAAAIQAAAFgCAIQAGgHAKgGQANgIAMAAQAXAAAAATQAAAHgEANQgFAOAAAGQAAALAKAAQAFAAAGgHIACgBIgBgJQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAJAAQAMAAAKgIIAHgEQAEAAAAAEQAAADgHAHQgRASgYAAQgWAAgNgKgAHlgOQgHAKAAAMQALgDAJgIQAIgIAAgGQAAgHgHAAQgHAAgHAKgADWAwQgFgEgDgGQgPAUgXAAQgLAAgHgIIgFgHQgQAPgWAAQggAAAAgjQAAgZAQgRQAQgRAZAAQAPAAAHAFQAIghAAgRQAAgPgLAAQgEAAAAgDQAAgFAKgGQAKgGANAAQALAAAHAGQAHAHAAALQAAAMgNApQgMApAAATQAAAGADAEQADADAEAAQAGAAAFgHIABgBIAAgGQAAgWAQgRQATgSAdAAQAQAAALAKQAKAJAAAQQAAAZgPARQgQATgbAAQgUAAgLgLgAB4gEQgGAOAAAQQAAAMAKAAQAKAAAFgOQADgGADgMQADgMAAgIQAAgJgKAAQgLAAgHATgAEAgSQgOALAAAWQAAAKAFAGQAGAGAIAAQAJAAAGgHQAFgHAAgJQAAgIgGgDQgMgEAAgHQAAgFADgDIACgEQAAAAAAgBQgBAAAAgBQAAAAgBAAQgBAAAAAAQgDAAgGAEgAiOAwQgFgEgDgGQgOAUgYAAQgMAAgIgHQgHgGAAgKQAAgKAFgNQAFgNAAgFQAAgJgHAAQgKAAgJASQgEAIgFAPQgEAQAAAIQAAAGgHAAIgZACQgGAAAAgHQAAgFAGgbQAGgaAAgIIgBgGIgBgEQAAgFALgDQAJgDAOAAQAKAAAAAIQAAAFgCAIQAGgHAKgGQANgIALAAQAXAAAAATQAAAHgEANQgEAOAAAGQAAALAKAAQAFAAAGgHIABAAIgBgHQAAgWARgRQASgSAdAAQARAAAKAKQALAJAAAQQAAAZgQARQgQATgaAAQgUAAgMgLgAhjgSQgPAMAAAVQAAAKAGAGQAFAGAJAAQAIAAAGgHQAGgHAAgJQAAgIgGgDQgMgEAAgHQAAgFACgDIACgEQAAAAAAgBQAAAAgBgBQAAAAAAAAQgBAAgBAAQgCAAgGAEgAmnAxQgOgLAAgVQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAJAAQALAAALgIIAHgEQAEAAAAAEQAAAEgHAGQgRASgYAAQgWAAgNgKgAmDgOQgHAKAAAMQALgDAJgIQAIgIAAgGQAAgHgHAAQgHAAgHAKgApzAxQgOgLAAgVQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAJAAQAMAAAKgIIAHgEQAEAAAAAEQAAADgGAHQgTASgXAAQgWAAgNgKgApPgOQgHAKAAAMQALgDAJgIQAIgIAAgGQAAgHgHAAQgHAAgHAKgAODA2QgDgEAAgGQAAgIAGgGQAGgIAIAAQAFAAADAEQAEAEAAAGQAAAIgGAHQgGAHgJAAQgFAAgDgEgAgoAxQgIgHAAgNQAAgKAFgQQAFgPAAgHQAAgBgBAAQAAAAAAgBQgBAAgBAAQAAAAgBgBQgFgBAAgDIACgFQABgEADAAQAKAAAMgJQAJgIAHgLQADgGAEAAQAFAAAAAFQAAAGgEARQAAABAAABQAAABAAAAQAAABABAAQAAABAAAAQACABAHAAQAEAAAAAEQAAAKgHAAQgKAAgCAJQgGAXAAAKQAAANALAAQAEAAAMgKIAGgDQAEAAAAAEQAAACgDAEQgHAJgMAIQgNAKgNAAQgPAAgIgJgAoRAzQAAgFAHgbQAGgaAAgIIgBgGIgBgEQAAgFAKgDQAKgDANAAQALAAAAAIIgCALQAKgSAQAAQAOAAAAAOQAAAJgFAHQgGAHgJAAQgGAAgDgDQgDgDAAgFQgFADgFAJQgFAIgEAPQgEAQAAAIQAAAGgGAAIgZACQgHAAAAgHgAoVhBIAFgKQAFgJAAgIIgBgHQgCgEAAgDQAAgHAEgEQAEgFAIAAQAPAAAAAQQAAAPgOAQQgNAOgGAAQgFAAAAgEg");
	this.shape.setTransform(97.375,18.825);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFEA7D").ss(9.2,0,0,1).p("AMtAWQABgIAEgLQAEgPAAgHQAAgCgEgBQgEgBAAgDQAAgCABgDQACgEACAAQALAAALgJQAKgIAGgLQAFgGADAAQAFAAAAAFQAAAGgEARQAAAEACABQACABAGAAQAEAAAAAEQAAAKgHAAQgKAAgCAJQgHAXAAAKQAAANAMAAQAEAAAFgEQADgCAFgEQAEgDABAAQAEAAAAAEQAAACgCAEQgIAJgLAIQgPAKgMAAQgQAAgIgJQgFgFgCgIQgWAXgdAAQgWAAgMgKQgOgLAAgVQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAKAAQAKAAAKgGQADgCAKgIQABgBAAAAQADgCACAAQADAAAAADQAAAEgGAHQgBABgBABQAAgDAAgEQAAgDAAgEgAOUAWQAFAAADAEQAEAEAAAGQAAAIgGAHQgGAHgJAAQgFAAgDgEQgDgEAAgGQAAgIAGgGQAGgIAIAAgAJbgZQAAgFAKgDQAKgDANAAQAKAAAAAIQAAAGgFATQgFASAAAKQAAAJAIAAQAKAAAJgNQAIgMAAgYQAAgDgBgDQgBgCAAgCQAAgFAKgDQAKgDANAAQALAAAAAIQAAADgDALQgEARgFAcQgJAzgKAWQgRAmgkAAQgRAAgLgJQgMgJAAgPQAAgQAKgKQAIgIAIAAQADAAAAADQAAABgBADQgCADAAAEQAAAOARAAQAPAAAJgVQAGgOAEgcQgSASgbAAQgLAAgIgHQgHgGAAgKQAAgLAFgSQAFgRAAgEQAAgDgBgDQgBgCAAgCgAMRgRQAAgHgHAAQgHAAgHAKQgHAKAAAMQALgDAJgIQAIgIAAgGgAH6gRQAAgHgHAAQgHAAgHAKQgHAKAAAMQALgDAJgIQAIgIAAgGgAG0AaQgBgEAAgFQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAJAAQAMAAAKgIQAGgEABAAQAEAAAAAEQAAADgHAHQgRASgYAAQgWAAgNgKQgGgFgEgHQAAABAAAAQgQAUgWAAQgNAAgHgHQgIgGAAgKQAAgKAFgNQAFgNAAgFQAAgJgHAAQgJAAgKASQgEAIgEAPQgFAQAAAIQAAAGgGAAQgVACgFAAQgGAAAAgHQAAgFAHgbQAGgaAAgIQAAgDgBgDQgBgCAAgCQAAgFAKgDQAKgDANAAQAKAAAAAIQAAAFgCAIQAGgHAKgGQANgIAMAAQAXAAAAATQAAAHgEANQgFAOAAAGQAAALAKAAQAFAAAGgHQABgBABAAQACgCABAAQAEAAAAAEQAAAEgEAFQgCgFgBgGgADKAaQAAgDAAgDQAAgWAQgRQATgSAdAAQAQAAALAKQAKAJAAAQQAAAZgPARQgQATgbAAQgUAAgLgLQgFgEgDgGQgPAUgXAAQgLAAgHgIIgFgHQgQAPgWAAQggAAAAgjQAAgZAQgRQAQgRAZAAQAPAAAHAFQAIghAAgRQAAgPgLAAQgEAAAAgDQAAgFAKgGQAKgGANAAQALAAAHAGQAHAHAAALQAAAMgNApQgMApAAATQAAAGADAEQADADAEAAQAGAAAFgHQABAAAAgBgAETADQgMgEAAgHQAAgFADgDIACgEQAAgCgDAAQgDAAgGAEQgOALAAAWQAAAKAFAGQAGAGAIAAQAJAAAGgHQAFgHAAgJQAAgIgGgDgACKgXQgLAAgHATQgGAOAAAQQAAAMAKAAQAKAAAFgOQADgGADgMQADgMAAgIQAAgJgKAAgADOAmQgDgFgBgHQADgCABAAQAFAAAAAEQAAAEgFAGgAAAgMQgGAXAAAKQAAANALAAQAEAAAMgKQAEgDACAAQAEAAAAAEQAAACgDAEQgHAJgMAIQgNAKgNAAQgPAAgIgJQgIgHAAgNQAAgKAFgQQAFgPAAgHQAAgCgEgBQgFgBAAgDQAAgCACgDQABgEADAAQAKAAAMgJQAJgIAHgLQADgGAEAAQAFAAAAAFQAAAGgEARQAAAEABABQACABAHAAQAEAAAAAEQAAAKgHAAQgKAAgCAJgAhQADQgMgEAAgHQAAgFACgDIACgEQAAgCgDAAQgCAAgGAEQgPAMAAAVQAAAKAGAGQAFAGAJAAQAIAAAGgHQAGgHAAgJQAAgIgGgDgAiZAbQgBgEAAgDQAAgWARgRQASgSAdAAQARAAAKAKQALAJAAAQQAAAZgQARQgQATgaAAQgUAAgMgLQgFgEgDgGQgOAUgYAAQgMAAgIgHQgHgGAAgKQAAgKAFgNQAFgNAAgFQAAgJgHAAQgKAAgJASQgEAIgFAPQgEAQAAAIQAAAGgHAAQgUACgFAAQgGAAAAgHQAAgFAGgbQAGgaAAgIQAAgDgBgDQgBgCAAgCQAAgFALgDQAJgDAOAAQAKAAAAAIQAAAFgCAIQAGgHAKgGQANgIALAAQAXAAAAATQAAAHgEANQgEAOAAAGQAAALAKAAQAFAAAGgHQABAAAAAAgAiWAmQgCgFgBgGQACgDACAAQAEAAAAAEQAAAEgFAGgAlfAfQAGgEABAAQAEAAAAAEQAAAEgHAGQgRASgYAAQgWAAgNgKQgOgLAAgVQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAJAAQALAAALgIgAn+h6QAPAAAAAQQAAAPgOAQQgNAOgGAAQgFAAAAgEQAAgCAFgIQAFgJAAgIQAAgDgBgEQgCgEAAgDQAAgHAEgEQAEgFAIAAgAnrAyQAAAGgGAAQgVACgEAAQgHAAAAgHQAAgFAHgbQAGgaAAgIQAAgDgBgDQgBgCAAgCQAAgFAKgDQAKgDANAAQALAAAAAIQAAADgCAIQAKgSAQAAQAOAAAAAOQAAAJgFAHQgGAHgJAAQgGAAgDgDQgDgDAAgFQgFADgFAJQgFAIgEAPQgEAQAAAIgAorAfQAGgEABAAQAEAAAAAEQAAADgGAHQgTASgXAAQgWAAgNgKQgOgLAAgVQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAJAAQAMAAAKgIgAlugRQAAgHgHAAQgHAAgHAKQgHAKAAAMQALgDAJgIQAIgIAAgGgAtEh8QgRAAgPATQgOASAAASQAAAPAMAAQAEAAAGgDQACAAAAAEQAAAIgKAKQgNAMgPAAQgNAAgJgJQgJgKAAgPQAAgkAggZQAdgXAlAAQAVAAANAKQANALAAATQAAAXgMAlQgNAlAAAMQAAAGAEAEQADADAEAAQARAAAQgZQAIgMAHgYQAGgVAAgJIgBgKQAAgGAPgHQAMgFAGAAQALAAAAALQAAAKgKAlQgLAkAAAKQAAAPAMAAQAUAAAUgqQAMgdAAgkQAAgcgTAAQgFAAAAgFQAAgGAJgIQALgIANAAQAdAAAAAfQAAAmgeA9QgPAegTATQgWAVgUAAQgPAAgKgKQgKgKgCgQQgcAkgiAAQgQAAgJgKQgJgJAAgQQAAgUARgrQARgtAAgcQAAgMgNAAgAo6gRQAAgHgHAAQgHAAgHAKQgHAKAAAMQALgDAJgIQAIgIAAgGg");
	this.shape_1.setTransform(97.375,18.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,194.8,37.7);


(lib.HEAD_50_2linesai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HEAD_50_2lines.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#70202C").s().p("AnFBhQgKgHAAgNQAAgMAIgIQAHgHAGAAQAAAAABAAQABAAAAABQAAAAABAAQAAABAAAAIgBAEQgCACAAADQAAAMAOAAQAMAAAHgRQAFgLAEgXQgQAOgVAAQgJAAgGgFQgFgEAAgGQgNAPgSAAQgKAAgGgFQgGgFAAgIQAAgIAEgKQAEgLAAgEQAAgHgGAAQgIAAgHAPIgHASQgDAMAAAHQAAAFgGAAIgUABQgFAAAAgFIABgGQgMALgPAAQgJAAgGgGIgEgHQgMANgSAAQgLAAgHgHQgIgHAAgOQAAgTAMgNQANgPAYAAQAIAAAGACIAGACIAKgCIAKgCQAEAAAAADIgEARQgEAQAAAKQAAAKAIAAQAEAAAFgFIADgCIABgFQAFgVAAgHQgCgEAAgDQAAgEAJgDQAHgCALAAQAJAAAAAGIgCALQAFgGAHgFQALgGAJAAQATAAAAAPQAAAGgDALQgEAKAAAFQAAAJAIAAQADAAAGgFQABgBAAAAQABgBAAAAQABAAAAgBQABAAAAAAIADgOQAEgOAAgEIgBgEIgBgDQAAgEAJgDQAHgCALAAQAIAAAAAGQAAAFgEAPQgEAPAAAHQAAAIAGAAQAJAAAGgKQAHgJAAgVIgBgHQAAgEAIgDQAIgCAKAAQAJAAAAAGQAAAGgKApQgGAqgIARQgPAfgcAAQgOAAgJgHgAp1gOQgEALAAAMQAAALAIAAQAIAAAEgLQADgFACgJQACgKAAgHQAAgHgIAAQgJAAgGAPgAupBFQAAgCADgEQAGgHADgMQADgNAFgbIAFgbQAAgEgFAAQgEAAAAgEQAAgCACgDIADgCQAGAAACgGQAJgoAjAAQAMAAAGAEQAGAFAAAHQAAAMgMAAQgHAAgCgHQgCgHgCAAQgEAAgDAIQgDAHAAAGQAAAGAEACQAEADALAAQABAAABAAQAAABABAAQAAAAAAABQAAAAAAABQAAAIgFAAQgMAAgFAEQgFADgBAIIgNA3QgDAMgPAJQgNAIgIAAQgEAAAAgDgADHAdQgEgEgCgEQgNAPgSAAQgVAAAAgSQAAgHAEgLQAEgMAAgEQAAgGgGAAQgIAAgHAPQgDAGgEANIgEASQAAAFgFAAIgVABQgEAAAAgFQAAgJALgnQAKgoAAgTQAAgLgJAAQgBAAgBAAQAAgBgBAAQAAAAgBgBQAAgBAAAAQAAgEAIgFQAJgEAKAAQAUAAAAATQAAASgOAqQAOgPARAAQAVAAAAAQQAAAGgEALQgDAJAAAFQAAAJAHAAQAEAAAFgFIABgBIgBgFQAAgSAOgOQAPgOAXAAQANAAAJAIQAIAIAAAMQAAAUgMAOQgNAPgWAAQgQAAgJgIgADqgZQgMAKAAARQAAAIAEAFQAEAFAHAAQAHAAAFgGQAEgGAAgHQAAgGgFgCQgJgEAAgGQAAgDACgDIABgDQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAQgCAAgEADgAlhAdQgJgJAAgOQAAgSANgOQAPgOAXAAQAOAAAIAIQAJAIAAAMQAAAUgNAOQgNAPgVAAQgQAAgKgIgAk+gZQgMAKAAARQAAAIAEAFQAFAFAHAAQAHAAAEgGQAFgGAAgHQAAgGgFgCQgKgEAAgGQAAgDACgDIACgDQAAgBAAAAQAAgBgBAAQAAAAAAAAQgBAAAAAAQgCAAgFADgAtYAdQgJgJAAgOQAAgSANgOQAPgOAXAAQAOAAAIAIQAJAIAAAMQAAAUgNAOQgNAPgVAAQgQAAgKgIgAs1gZQgMAKAAARQAAASAQAAQAHAAAEgGQAFgGAAgHQAAgGgFgCQgKgEAAgGQAAgDACgDIACgDQAAgBAAAAQAAgBgBAAQAAAAAAAAQgBAAAAAAQgCAAgFADgAKvAfQgEgDgDgEQgLAMgPAAQgKAAgFgGIgEgGQgNAMgRAAQgVAAgEgSQgTATgXAAQgeAAgHgUQgSAUgYAAQgcAAgIgRQgMAQgSAAQgKAAgGgFQgGgFAAgIQAAgIAEgKQADgLAAgEQAAgHgFAAQgIAAgHAPQgEAHgDALQgEAMAAAHQAAAFgFAAIgUABQgFAAAAgFQAAgEAFgWQAFgVAAgHIgCgHQAAgEAJgDQAHgCALAAQAIAAAAAGIgCALQAQgRARAAQATAAAAAPQAAAGgEALQgDAKAAAFQAAAJAIAAQAEAAAFgFIAAgBIAAgHQAAgSANgMQAPgOAXAAQAYAAAAASQAAALgLAIQgMAHgSACQAAAPATAAQAKAAAQgNIAAAAIAAgEQAAgSAOgMQAOgOAXAAQAYAAAAASQAAALgLAIQgLAHgSACQAAAGAFAEQAFAFAIAAQALAAAPgNIABAAQAAgTANgOQANgOAUAAQAMAAAFAEQAHgcAAgNQAAgLgJAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAgBAAAAQAAgEAIgFQAIgEAKAAQAVAAAAATQAAAJgKAiQgLAhAAAPQAAAKAIAAQAEAAADgDQABgEADgDQADgEAFAAQAKAAAAAJQAAAKAGAAQAGAAAAgGQAAgHgMgJQgMgIAAgJQAAgLAKgHQAJgFAOAAQAaAAAAAQQAAANgMAAQgDAAgDgDQgCgCAAgEIACgHQAAgDgFAAQgDAAgCACQgCADAAADQAAAGAOAJQANAIAAAJQAAAMgJAIQgKAHgPAAQgOAAgJgGgAJngOQgEANAAAMQAAAKAHAAQAIAAAFgMQAGgPAAgQQAAgHgHAAQgJAAgGAPgAIcgVQgGAIAAAKQAJgCAIgHQAGgHAAgFQAAgFgGAAQgGAAgFAIgAHMgVQgGAIAAAKQAKgCAHgHQAGgHAAgFQAAgFgGAAQgFAAgGAIgAirAUIAAAAQgNAQgSAAQgKAAgGgFQgGgFAAgIQAAgIAEgKQAEgLAAgEQAAgHgGAAQgIAAgHAPIgHASQgDAMAAAHQAAAFgGAAIgUABQgFAAAAgFQAAgEAFgWQAFgVAAgHQgCgEAAgDQAAgEAJgDQAHgCALAAQAJAAAAAGIgCALQAEgFAIgGQALgGAJAAQATAAAAAPQAAAGgDALQgEAKAAAFQAAAJAIAAQADAAAGgFIABgBIAAgHQAAgSANgMQAPgOAXAAQAXAAAAASQAAALgLAIQgLAHgSACQAAAGAFAEQAFAFAHAAQAJAAAJgGIAGgDQAAAAABAAQABAAAAABQAAAAABAAQAAABAAABQAAACgFAGQgOAOgUAAQgcAAgIgRgAiGgVQgGAIAAAKQAKgCAHgHQAGgHAAgFQAAgFgGAAQgGAAgFAIgAORAZQAAgGAEgFQAFgGAHAAQAJAAAAALQAAAGgEAGQgFAFgHAAQgJAAAAgLgANUAdQgDgDgCgEQgMAOgRAAQgLAAgGgGQgGgFAAgJQAAgIAEgNQAEgOAAgEIgCgHQAAgEAIgDQAIgCALAAQAIAAAAAGQAAAEgEAOQgEAOAAAIQAAAKAIAAQAEAAAFgFIABgBQAAgHAEgLQADgNAAgFQAAgBAAAAQAAAAAAgBQgBAAAAAAQgBAAgBgBQgBAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQAAgHAEAAQAQAAAPgXQADgFADAAQABAAABAAQAAABABAAQAAABABAAQAAABAAABQAAAFgDAOQAAAFAIAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABQAAADgCACQAAABgBAAQAAABAAAAQgBAAAAABQgBAAAAAAQgJAAgCAIQgFARAAAJQAAAKAKAAQAEAAAJgIIAEgCQABAAABAAQAAAAABAAQAAABAAAAQAAABAAAAQAAADgBACQgHAIgJAGQgMAIgKAAQgMAAgGgHgAAJAUQgRAQgSAAQgKAAgGgFQgGgGAAgIQAAgJAEgMQAEgOAAgFIgCgHQAAgEAIgDQAIgCALAAQAIAAAAAGQAAAFgEAPQgEAOAAAIQAAAJAHAAQAIAAAFgLQAHgMAAgSIgCgHQAAgEAIgDQAIgCALAAQAIAAAAAGQAAAFgEAPQgEAOAAAIQAAAJAJAAQAHAAAGgJQAGgJAAgJQAAgEgEgEQgEgEAAgEQAAgHAEgDQAEgEAHAAQAPAAAAARQAAAUgNARQgPAVgWAAQgTAAgJgQgAsNAfQAAgEAFgWQAFgVAAgHQgCgEAAgDQAAgEAJgDQAHgCALAAQAJAAAAAGIgCAJQAJgOAMAAQALAAAAALQAAAIgEAFQgEAGgHAAQgKAAAAgJQgDABgGAJQgDAHgDALQgDAMAAAHQAAAFgGAAIgUABQgFAAAAgFgAMtg4QgEgDAAgGQAAgHAFgGQAGgHAHAAQANAAAAANQAAAHgFAHQgGAGgHAAQgFAAgEgEg");
	this.shape.setTransform(97.525,33.525);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#70202C").s().p("ApxBiQgKgIAAgMQAAgNAJgIQAGgGAGAAQABAAAAAAQABAAAAAAQAAABABAAQAAABAAAAIgBAEIgBAFQAAALAOAAQATAAAIgyQgPAOgWAAQgJAAgFgFQgGgGAAgIQAAgJAEgNQAEgPAAgDQgCgEAAgDQAAgEAIgDQAIgDALABQAIgBAAAHQAAAEgEAQQgFAOAAAIQAAAHAHAAQAIABAHgLQAHgJAAgUIgCgHQAAgEAIgDQAIgDALABQAIgBAAAHIgCALIgHAkQgIArgHAPQgOAggdAAQgNAAgKgHgAhlBFQAAgBAEgFQAGgJACgKIAJgnIAEgbQAAgFgFAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBQAAgDACgCQAAgBABAAQAAgBAAAAQABAAAAAAQAAAAABgBQAFABACgHQAKgoAjABQALAAAHAEQAGAFAAAGQAAAGgEAEQgDADgGAAQgHAAgCgHQgCgIgCAAQgEABgDAHQgCAHAAAHQAAAFADADQAEACAMAAQABAAAAABQABAAAAAAQAAABABAAQAAABAAAAQAAAJgGgBQgUAAgDAPIgMA3QgDAMgPAJQgNAIgIAAQgFAAAAgDgAsCAaQgLgNAAgXQAAgnAUgbQAUgcAbAAQASAAAKAMQALAMAAAZQAAAigSAcQgUAfgdAAQgSAAgKgMgArihAQgJAcAAAqQAAAHADAGQADAFAFAAQANAAAJgjQAHgfAAggQAAgRgJgBQgOABgIAbgAMfAEQAAgRAOgNQAOgNAXAAQAYAAAAASQAAAKgLAJQgMAHgRABQAAAHAFAEQAFAFAHAAQAHAAALgHIAFgDQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABQAAADgFAGQgPANgSAAQgoABAAgigANHgVQgFAIAAALQAJgCAHgIQAGgGAAgFQAAgFgFAAQgGAAgGAHgAItAdQgLgJAAgOQAAgTANgNQAOgNAXAAQAZAAAAARQAAAHgEAEQgEAEgGAAQgKAAAAgHQAAgEACgCIACgFQAAgDgEAAQgGAAgGAIQgGAJAAALQAAALAGAFQAGAFAIABQALAAAOgNIABgBQAAgTALgMQAOgQAYABQAHgBAGADIAHACIAKgCIAKgCQABAAABAAQAAAAABAAQAAABABAAQAAABAAABIgEARQgFAPAAAKQAAAFADADQACADADgBQAEABAGgGIADgCIABgEQAFgVAAgHIgCgHQAAgEAJgDQAHgDALABQAIgBAAAHQAAAFgBAEQAHgPAOAAQALAAAAALQAAAIgEAGQgFAFgHAAQgKAAAAgJQgDABgFAKQgDAGgDALQgEAMAAAIQAAAEgFAAIgUACQgFAAAAgFIABgHQgMAMgPAAQgJAAgGgGIgEgHQgNANgRAAQgMAAgHgHQgEgFgCgHQgJAJgGAEQgMAGgPAAQgRABgKgJgAKVgNQgFALAAALQAAAMAIAAQAIAAAFgMQACgEACgJQACgKAAgHQAAgHgHAAQgJAAgGAPgABwAVQgMAQgSAAQgWAAAAgTQAAgHAEgLQAEgLAAgFQAAgFgGAAQgIgBgHAPQgDAGgDAOIgEASQAAAEgFAAIgVACQgFAAAAgFQAAgJALgoQALgnAAgTQAAgMgKAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBQAAgEAIgEQAJgFAJABQAVAAAAASQAAARgOAsQANgQASABQAUAAAAAQQAAAGgDALQgEAIAAAGQAAAIAIAAQAEABAFgGIAAAAIAAgIQAAgRANgNQAPgNAXAAQAYAAAAASQAAAKgLAJQgMAHgSABQAAAHAFAEQAFAFAIAAQAMAAAOgNIABgBQAAgTAMgMQANgQAYABQAIgBAGADIAHACIAJgCIALgCQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIgEARQgEAPAAAKQAAAFACADQADADADgBQAEABAFgGQABgKAJgaQAJgeAAgVQAAgMgKAAQAAAAgBAAQgBAAAAgBQAAAAgBAAQAAgBAAgBQAAgEAIgEQAJgFAKABQAUAAAAASQAAAKgJAkQgKAiAAALQAAALAIgBQAEABAFgGQAAgIAEgLQADgNAAgFQAAAAAAgBQAAAAgBAAQAAAAAAgBQgBAAgBAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgIAEAAQARABAOgXQADgFADAAQAEAAAAADQAAAGgDAOQAAAEAIAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAQAAAJgFgBQgIAAgDAIIgFAaQAAALAKgBQADAAAEgCIAGgGIADgBIAGgZQAKgnAAgTQAAgMgJAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBQAAgEAIgEQAIgFAKABQAVAAAAASQAAAJgOA0QANgQASABQAUAAAAAQQAAAGgDALQgEAJAAAFQAAAJAFAAQAEAAADgCIAEgBQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAABQAAADgDADQgMAOgNAAQgWAAAAgTQAAgHAEgLQAEgLAAgFQAAgFgGAAQgHgBgIAPQgDAHgEANQgDANAAAFQAAAEgFAAIgVACQgFAAAAgFIABgKIgIAHQgMAIgKAAQgTAAgFgNQgMANgQAAQgMAAgGgHQgDgDgBgEQgMAOgRAAQgJAAgFgGIgEgHQgNANgSAAQgLAAgHgHQgFgFgCgGQgIAIgGAEQgMAGgQAAQgbAAgIgQgADhgNQgFALAAALQAAAMAIAAQAIAAAEgMQADgEACgJQACgKAAgHQAAgHgHAAQgKAAgFAPgACVgVQgGAIAAALQAKgCAHgIQAGgGAAgFQAAgFgGAAQgFAAgGAHgAieAdQgKgIAAgPQAAgRAOgOQAOgOAYAAQANgBAJAJQAIAHAAANQAAATgMAPQgNAOgWAAQgQABgJgJgAh8gYQgMAJAAASQAAAHAFAFQAEAFAHAAQAHAAAFgGQAEgFAAgHQAAgGgFgDQgJgDAAgGQAAgDACgDIABgEQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAgBgBAAQgDABgEADgAkTAgQgJgGAAgKQAAgFAEgEQADgDAEAAQALAAAAAJQAAAKAGAAQAFAAAAgHQAAgGgMgJQgMgJAAgJQAAgLAKgGQAKgGAOAAQAZAAAAARQAAAMgLAAQgEAAgCgCQgDgCAAgEIACgIQAAgCgEAAQgHgBAAAJQAAAGANAJQANAIAAAJQAAAMgJAHQgJAIgQgBQgNABgJgGgAoWAEQAAgRAOgNQAOgNAXAAQAYAAAAASQAAAKgLAJQgMAHgRABQAAAHAEAEQAFAFAJAAQAMAAAOgNIABgBQAAgTALgMQAOgQAYABQAHgBAGADIAHACIAJgCIALgCQAEAAAAADIgEARQgFAPAAAKQAAALAIgBQAFABAEgGIAEgCIABgEQAFgVAAgHIgBgEIgBgDQAAgEAIgDQAIgDALABQAIgBAAAHQAAAFgBAEQAHgPAOAAQALAAAAALQAAAIgEAGQgFAFgHAAQgKAAAAgJQgDABgFAKQgDAGgDALQgEAMAAAIQAAAEgFAAIgUACQgGAAAAgFIABgHQgMAMgPAAQgJAAgFgGIgEgHQgNANgRAAQgMAAgHgHQgEgFgCgHQgJAJgGAEQgMAGgPAAQgnABAAgigAmigNQgFALAAALQAAAMAIAAQAIAAAFgMQACgEACgJQACgKAAgHQAAgHgHAAQgJAAgGAPgAnugVQgFAIAAALQAJgCAHgIQAGgGAAgFQAAgFgFAAQgGAAgGAHgAtjAYQgJgLAAgQQAAgHAEAAQADABABAFQAFANARAAQAKAAAGgIQAGgGAAgLQAAgJgEgFQgFgJgLAAIgJABIgCAAQgDAAgCgCQgDgDAAgDQAJgYACgUQABgEADgFQAEgDAEAAIAJACQAJACALgBQAUAAAGgDQABAAABAAQAAAAABAAQAAABABAAQAAABAAAAQAAAEgEAJQgGALgGACQgDACgHAAQgHABgTgFQgDANgEAKIAKgBQARAAAMALQAMALAAARQAAAVgOAQQgOAPgVAAQgTAAgKgNg");
	this.shape_1.setTransform(99.375,14.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#FFEA7D").ss(7.4,0,0,1).p("AJDAIQAAgTANgOQANgOAUAAQAMAAAFAEQAHgcAAgNQAAgLgJAAQgDAAAAgDQAAgEAIgFQAIgEAKAAQAVAAAAATQAAAJgKAiQgLAhAAAPQAAAKAIAAQAEAAADgDQABgEADgDQADgEAFAAQAKAAAAAJQAAAKAGAAQAGAAAAgGQAAgHgMgJQgMgIAAgJQAAgLAKgHQAJgFAOAAQAaAAAAAQQAAANgMAAQgDAAgDgDQgCgCAAgEQACgFAAgCQAAgDgFAAQgDAAgCACQgCADAAADQAAAGAOAJQANAIAAAJQAAAMgJAIQgKAHgPAAQgOAAgJgGQgEgDgCgEQgMAMgPAAQgKAAgFgGIgEgGQgNAMgRAAQgVAAgEgSQgTATgXAAQgeAAgHgUQgSAUgYAAQgcAAgIgRQgMAQgSAAQgKAAgGgFQgGgFAAgIQAAgIAEgKQADgLAAgEQAAgHgFAAQgIAAgHAPQgEAHgDALQgEAMAAAHQAAAFgFAAIgUABQgFAAAAgFQAAgEAFgWQAFgVAAgHQgCgEAAgDQAAgEAJgDQAHgCALAAQAIAAAAAGQAAAEgCAHQAQgRARAAQATAAAAAPQAAAGgEALQgDAKAAAFQAAAJAIAAQAEAAAFgFQAAgBAAAAQAAgDAAgEQAAgSANgMQAPgOAXAAQAYAAAAASQAAALgLAIQgMAHgSACQAAAPATAAQAKAAAQgNQAAAAABAAQgBgCAAgCQAAgSAOgMQAOgOAXAAQAYAAAAASQAAALgLAIQgLAHgSACQAAAGAFAEQAFAFAIAAQALAAAPgNQABAAAAAAQACgCACAAQADAAAAACQAAAEgFAFQAAABgBAAQgBgEAAgGgAM7hVQANAAAAANQAAAHgFAHQgGAGgHAAQgFAAgEgEQgEgDAAgGQAAgHAFgGQAGgHAHAAgANPAWQgMAOgRAAQgLAAgGgGQgGgFAAgJQAAgIAEgNQAEgOAAgEQgCgEAAgDQAAgEAIgDQAIgCALAAQAIAAAAAGQAAAEgEAOQgEAOAAAIQAAAKAIAAQAEAAAFgFQABgBAAAAQAAgHAEgLQADgNAAgFQAAgCgDgBQgDgBAAgCQAAgHAEAAQAQAAAPgXQADgFADAAQAEAAAAAEQAAAFgDAOQAAAFAIAAQADAAAAADQAAADgCACQgBADgCAAQgJAAgCAIQgFARAAAJQAAAKAKAAQAEAAAJgIQADgCABAAQADAAAAACQAAADgBACQgHAIgJAGQgMAIgKAAQgMAAgGgHQgDgDgCgEQgBgEAAgFQAAgBAAgBQACgCACAAQADAAAAAEQAAACgEAFQgBABgBABgAKmAOQACgBABgBQACgDACAAQADAAAAAEQAAACgEAFQgCADgBABQgDgDAAgFQAAgBAAgBgAOhAIQAJAAAAALQAAAGgEAGQgFAFgHAAQgJAAAAgLQAAgGAEgFQAFgGAHAAgAGnAUQgCgEgBgFQACgCACAAQADAAAAAEQAAACgEAFgAC+ALQgBgCAAgDQAAgSAOgOQAPgOAXAAQANAAAJAIQAIAIAAAMQAAAUgMAOQgNAPgWAAQgQAAgJgIQgEgEgCgFQgNAQgSAAQgVAAAAgSQAAgHAEgLQAEgMAAgEQAAgGgGAAQgIAAgHAPQgDAGgEANQgDANgBAFQAAAFgFAAIgVABQgEAAAAgFQAAgJALgnQAKgoAAgTQAAgLgJAAQgEAAAAgDQAAgEAIgFQAJgEAKAAQAUAAAAATQAAASgOAqQAOgPARAAQAVAAAAAQQAAAGgEALQgDAJAAAFQAAAJAHAAQAEAAAFgFQAAAAABgBQABgCACAAQAEAAAAAEQAAACgEAFIAAAAQgDgEAAgFgAD4gHQgJgEAAgGQAAgDACgDIABgDQAAgCgCAAQgCAAgEADQgMAKAAARQAAAIAEAFQAEAFAHAAQAHAAAFgGQAEgGAAgHQAAgGgFgCgAItgYQAAgFgGAAQgGAAgFAIQgGAIAAAKQAJgCAIgHQAGgHAAgFgAJ2gdQgJAAgGAPQgEANAAAMQAAAKAHAAQAIAAAFgMQAGgPAAgQQAAgHgHAAgAHdgYQAAgFgGAAQgFAAgGAIQgGAIAAAKQAKgCAHgHQAGgHAAgFgAH0AIQACgCACAAQACAAAAACQAAAEgEAFQAAAAgBAAQgBgEAAgFgAA5gZQAAgHAEgDQAEgEAHAAQAPAAAAARQAAAUgNARQgPAVgWAAQgTAAgJgQQgRAQgSAAQgKAAgGgFQgGgGAAgIQAAgJAEgMQAEgOAAgFQgCgEAAgDQAAgEAIgDQAIgCALAAQAIAAAAAGQAAAFgEAPQgEAOAAAIQAAAJAHAAQAIAAAFgLQAHgMAAgSQgCgEAAgDQAAgEAIgDQAIgCALAAQAIAAAAAGQAAAFgEAPQgEAOAAAIQAAAJAJAAQAHAAAGgJQAGgJAAgJQAAgEgEgEQgEgEAAgEgAiuALQAAgEAAgDQAAgSANgMQAPgOAXAAQAXAAAAASQAAALgLAIQgLAHgSACQAAAGAFAEQAFAFAHAAQAJAAAJgGQAEgDACAAQADAAAAADQAAACgFAGQgOAOgUAAQgcAAgIgRIAAAAQgNAQgSAAQgKAAgGgFQgGgFAAgIQAAgIAEgKQAEgLAAgEQAAgHgGAAQgIAAgHAPQgDAHgEALQgDAMAAAHQAAAFgGAAIgUABQgFAAAAgFQAAgEAFgWQAFgVAAgHQgCgEAAgDQAAgEAJgDQAHgCALAAQAJAAAAAGQAAAEgCAHQAEgFAIgGQALgGAJAAQATAAAAAPQAAAGgDALQgEAKAAAFQAAAJAIAAQADAAAGgFQABgBAAAAQACgCABAAQAEAAAAAEQAAACgEAFQgCgEgBgFgAh1gYQAAgFgGAAQgGAAgFAIQgGAIAAAKQAKgCAHgHQAGgHAAgFgAnJAJQABgGACgIQAEgOAAgEQAAgCgBgCQgBgCAAgBQAAgEAJgDQAHgCALAAQAIAAAAAGQAAAFgEAPQgEAPAAAHQAAAIAGAAQAJAAAGgKQAHgJAAgVQgBgEAAgDQAAgEAIgDQAIgCAKAAQAJAAAAAGQAAAGgKApQgGAqgIARQgPAfgcAAQgOAAgJgHQgKgHAAgNQAAgMAIgIQAHgHAGAAQADAAAAACQAAABgBADQgCACAAADQAAAMAOAAQAMAAAHgRQAFgLAEgXQgQAOgVAAQgJAAgGgFQgFgEAAgHQgBgBAAgBQAAgEABgFIAAAAQAEAAAAAEQAAACgEAFIAAAAQgNAQgSAAQgKAAgGgFQgGgFAAgIQAAgIAEgKQAEgLAAgEQAAgHgGAAQgIAAgHAPQgDAHgEALQgDAMAAAHQAAAFgGAAIgUABQgFAAAAgFQAAgCABgEQABgGACgKQABAAAAAAQADAAAAAEQAAACgDAFQgCADgCACQgMALgPAAQgJAAgGgGIgEgHQgMANgSAAQgLAAgHgHQgIgHAAgOQAAgTAMgNQANgPAYAAQAIAAAGACQAGACAAAAQACAAAIgCQAHgCADAAQAEAAAAADQAAACgEAPQgEAQAAAKQAAAKAIAAQAEAAAFgFQACgCABgBQABgCAAgCQAFgVAAgHQgCgEAAgDQAAgEAJgDQAHgCALAAQAJAAAAAGQAAAEgCAHQAFgGAHgFQALgGAJAAQATAAAAAPQAAAGgDALQgEAKAAAFQAAAJAIAAQADAAAGgFQACgDACAAgAkYgMQAAAUgNAOQgNAPgVAAQgQAAgKgIQgJgJAAgOQAAgSANgOQAPgOAXAAQAOAAAIAIQAJAIAAAMgAkvgHQgKgEAAgGQAAgDACgDIACgDQAAgCgCAAQgCAAgFADQgMAKAAARQAAAIAEAFQAFAFAHAAQAHAAAEgGQAFgGAAgHQAAgGgFgCgAsPgMQAAAUgNAOQgNAPgVAAQgQAAgKgIQgJgJAAgOQAAgSANgOQAPgOAXAAQAOAAAIAIQAJAIAAAMgAsmgHQgKgEAAgGQAAgDACgDIACgDQAAgCgCAAQgCAAgFADQgMAKAAARQAAASAQAAQAHAAAEgGQAFgGAAgHQAAgGgFgCgAtrgxQAAAGAEACQAEADALAAQADAAAAADQAAAIgFAAQgMAAgFAEQgFADgBAIQgMAzgBAEQgDAMgPAJQgNAIgIAAQgEAAAAgDQAAgCADgEQAGgHADgMQADgNAFgbQAFgYAAgDQAAgEgFAAQgEAAAAgEQAAgCACgDQACgCABAAQAGAAACgGQAJgoAjAAQAMAAAGAEQAGAFAAAHQAAAMgMAAQgHAAgCgHQgCgHgCAAQgEAAgDAIQgDAHAAAGgAruAeQAAAFgGAAIgUABQgFAAAAgFQAAgEAFgWQAFgVAAgHQgCgEAAgDQAAgEAJgDQAHgCALAAQAJAAAAAGQAAAFgCAEQAJgOAMAAQALAAAAALQAAAIgEAFQgEAGgHAAQgKAAAAgJQgDABgGAJQgDAHgDALQgDAMAAAHgApmgdQgJAAgGAPQgEALAAAMQAAALAIAAQAIAAAEgLQADgFACgJQACgKAAgHQAAgHgIAAg");
	this.shape_2.setTransform(97.525,33.525);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f().s("#FFEA7D").ss(7.4,0,0,1).p("ANlAPQAFgDAAAAQADAAAAADQAAADgFAGQgPAOgSAAQgoAAAAgiQAAgRAOgMQAOgOAXAAQAYAAAAARQAAALgLAJQgMAHgRACQAAAGAFAEQAFAFAHAAQAHAAALgHgANYgXQAAgFgFAAQgGAAgGAHQgFAIAAALQAJgCAHgIQAGgGAAgFgALaAKQAAgCABgCQAFgVAAgHQgCgFAAgCQAAgEAJgDQAHgCALAAQAIAAAAAFQAAAGgBAEQAHgPAOAAQALAAAAALQAAAIgEAGQgFAGgHAAQgKAAAAgKQgDACgFAJQgDAGgDALQgEANAAAHQAAAFgFAAIgUABQgFAAAAgFQAAgCABgFQgMAMgPAAQgJAAgGgGIgEgHQgNANgRAAQgMAAgHgIQgEgEgCgHQgJAJgGAEQgMAHgPAAQgRAAgKgJQgLgIAAgPQAAgTANgMQAOgOAXAAQAZAAAAARQAAAHgEAEQgEAEgGAAQgKAAAAgHQAAgDACgDQACgEAAgBQAAgDgEAAQgGAAgGAJQgGAJAAALQAAAKAGAGQAGAFAIAAQALAAAOgNQAAAAABgBQAAgTALgMQAOgPAYAAQAHAAAGACQAGACABAAQACAAAIgCQAHgCADAAQAEAAAAADQAAACgEAPQgFAQAAAKQAAAEADADQACADADAAQAEAAAGgGQABgCACAAQAAAAABAAQADAAAAADQAAADgEAFQgCACgBACQABgFACgKgAKkgcQgJAAgGAPQgFALAAAMQAAALAIAAQAIAAAFgLQACgFACgJQACgKAAgHQAAgHgHAAgAJxAIQADgCABAAQADAAAAADQAAADgFAGQgBAAAAAAQgBgEAAgFgAGQAIQACgKAEgPQAKgoAAgSQAAgMgJAAQgDAAAAgCQAAgFAIgEQAIgFAKAAQAVAAAAATQAAAJgOA0QANgPASAAQAUAAAAAQQAAAGgDALQgEAJAAAGQAAAJAFAAQAEAAADgCQACgCACAAQACAAAAACQAAACgDAEQgMAOgNAAQgWAAAAgTQAAgHAEgLQAEgMAAgDQAAgHgGAAQgHAAgIAPQgDAHgEANQgDANAAAFQAAAFgFAAIgVABQgFAAAAgFQAAgDACgHQABgGACgIQABgBABAAQADAAAAADQAAADgCACQgDAEgDADQgEAEgFADQgMAIgKAAQgTAAgFgNQgMANgQAAQgMAAgGgHQgDgDgBgEQgMAOgRAAQgJAAgFgGIgEgHQgNANgSAAQgLAAgHgIQgFgEgBgGQgJAIgGAEQgMAHgQAAQgbAAgIgRQgMAQgSAAQgWAAAAgTQAAgHAEgLQAEgMAAgDQAAgHgGAAQgIAAgHAPQgDAGgDAOQgEANAAAFQAAAFgFAAIgVABQgFAAAAgFQAAgJALgoQALgoAAgSQAAgMgKAAQgDAAAAgCQAAgFAIgEQAJgFAJAAQAVAAAAATQAAAQgOAtQANgPASAAQAUAAAAAQQAAAGgDALQgEAJAAAFQAAAJAIAAQAEAAAFgGQAAAAAAAAQACgCACAAQADAAAAADQAAADgEAFQgCgEgBgFQAAgEAAgEQAAgRANgMQAPgOAXAAQAYAAAAARQAAALgLAJQgMAHgSACQAAAGAFAEQAFAFAIAAQAMAAAOgNQABAAAAgBQAAgTAMgMQANgPAYAAQAIAAAGACQAGACABAAQACAAAHgCQAIgCADAAQADAAAAADQAAACgEAPQgEAQAAAKQAAAEACADQADADADAAQAEAAAFgGQACgCACAAQAEAAAAADQAAADgEAFQgBABgBABQgCgEAAgFQAAgBAAgBQABgKAJgaQAJgeAAgVQAAgMgKAAQgDAAAAgCQAAgFAIgEQAJgFAKAAQAUAAAAATQAAAKgJAkQgKAjAAALQAAAKAIAAQAEAAAFgGQAAgIAEgLQADgMAAgGQAAgCgDAAQgDgBAAgCQAAgIAEAAQARAAAOgWQADgGADAAQAEAAAAAFQAAAFgDAOQAAAEAIAAQADAAAAAEQAAAHgFAAQgIAAgDAIQgFAXAAAEQAAAKAKAAQADAAAEgDQACgCAEgDQABgCACAAgADwgcQgKAAgFAPQgFALAAAMQAAALAIAAQAIAAAEgLQADgFACgJQACgKAAgHQAAgHgHAAgAFVAMQACgCACAAQADAAAAADQAAADgEAFQgBABgBACQgBgFAAgFQAAgBAAgBgACmgXQAAgFgGAAQgFAAgGAHQgGAIAAALQAKgCAHgIQAGgGAAgFgAC8AIQADgCACAAQACAAAAADQAAAEgEAFQgBAAAAABQgCgFAAgFgAgmgwQAAAFADADQAEACAMAAQADAAAAAEQAAAHgGAAQgUAAgDAPQgKAxgCAHQgDALgPAKQgNAIgIAAQgFAAAAgDQAAgCAEgEQAGgKACgKQAEgMAFgbQAEgYAAgDQAAgFgFAAQgDAAAAgDQAAgDACgCQABgDACAAQAFAAACgFQAKgpAjAAQALAAAHAFQAGAFAAAGQAAAGgEAEQgDADgGAAQgHAAgCgHQgCgHgCAAQgEAAgDAIQgCAHAAAGgAhWgMQAAAVgMAOQgNAPgWAAQgQAAgJgJQgKgIAAgPQAAgSAOgNQAOgOAYAAQANAAAJAHQAIAIAAAMgAhtgHQgJgCAAgHQAAgDACgDIABgDQAAgCgCAAQgDAAgEADQgMAJAAASQAAAIAFAEQAEAFAHAAQAHAAAFgGQAEgFAAgHQAAgGgFgDgAkGANQAAAKAGAAQAFAAAAgGQAAgHgMgJQgMgIAAgKQAAgLAKgGQAKgGAOAAQAZAAAAARQAAAMgLAAQgEAAgCgCQgDgCAAgEQACgFAAgDQAAgCgEAAQgHAAAAAHQAAAHANAJQANAIAAAJQAAAMgJAHQgJAIgQAAQgNAAgJgGQgJgGAAgJQAAgGAEgDQADgEAEAAQALAAAAAJgAnGAIQAAgTALgMQAOgPAYAAQAHAAAGACQAGACABAAQACAAAHgCQAIgCADAAQAEAAAAADQAAACgEAPQgFAQAAAKQAAAKAIAAQAFAAAEgGQACgBACgBQAAgCABgCQAFgVAAgHQAAgCgBgCQgBgCAAgBQAAgEAIgDQAIgCALAAQAIAAAAAFQAAAGgBAEQAHgPAOAAQALAAAAALQAAAIgEAGQgFAGgHAAQgKAAAAgKQgDACgFAJQgDAGgDALQgEANAAAHQAAAFgFAAIgUABQgGAAAAgFQAAgCABgEQABgGADgKQAAAAABAAQADAAAAADQAAACgEAGQgCACgCADQgMALgPAAQgJAAgFgGIgEgHQgNANgRAAQgMAAgHgIQgEgEgCgHQgJAJgGAEQgMAHgPAAQgnAAAAgiQAAgRAOgMQAOgOAXAAQAYAAAAARQAAALgLAJQgMAHgRACQAAAGAEAEQAFAFAJAAQAMAAAOgNQAAAAABgBgAndgXQAAgFgFAAQgGAAgGAHQgFAIAAALQAJgCAHgIQAGgGAAgFgAmTgcQgJAAgGAPQgFALAAAMQAAALAIAAQAIAAAFgLQACgFACgJQACgKAAgHQAAgHgHAAgApvgdQAAgEAIgDQAIgCALAAQAIAAAAAFQAAAGgEAPQgFAOAAAIQAAAIAHAAQAIAAAHgKQAHgKAAgUQgCgFAAgCQAAgEAIgDQAIgCALAAQAIAAAAAFQAAADgCAJQgEAOgDAWQgIArgHAQQgOAfgdAAQgNAAgKgHQgKgHAAgNQAAgNAJgIQAGgGAGAAQADAAAAACQAAABgBADQgBACAAADQAAALAOAAQATAAAIgyQgPAOgWAAQgJAAgFgFQgGgFAAgJQAAgJAEgNQAEgOAAgEQgCgFAAgCgAnFASQgBgEAAgFIAAgBQADgCABAAQADAAAAADQAAAEgFAFQgBAAAAAAgAqjg3QAAAjgSAbQgUAfgdAAQgSAAgKgLQgLgNAAgXQAAgnAUgcQAUgcAbAAQASAAAKALQALANAAAZgAsrhjQAUAAAGgEQAEAAAAAEQAAAEgEAIQgGALgGACQgDADgHAAQgHAAgTgFQgDAMgEALQADAAAHAAQARAAAMAKQAMAKAAASQAAAVgOAQQgOAPgVAAQgTAAgKgNQgJgLAAgQQAAgGAEAAQADAAABAFQAFAOARAAQAKAAAGgIQAGgHAAgLQAAgIgEgGQgFgJgLAAIgJABIgCAAQgDAAgCgCQgDgDAAgDQAJgZACgSQABgFADgFQAEgDAEAAQACAAAHACQAJABALAAgArrAGQAAAIADAFQADAFAFAAQANAAAJgkQAHgeAAggQAAgSgJAAQgOAAgIAcQgJAbAAArg");
	this.shape_3.setTransform(99.375,14.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,195.1,47.7);


(lib.Since_50_1971 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Since
	this.instance = new lib.HealthPoint_Sinceai("synched",0);
	this.instance.setTransform(-22.25,48.1,1.27,1.27,0,0,0,18.2,5.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// 1971
	this.instance_1 = new lib.HealthPoint_1971ai("synched",0);
	this.instance_1.setTransform(25.3,47.95,1.27,1.27,0,0,0,13.6,5.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// 50
	this.instance_2 = new lib.HealthPoint_50onlyai("synched",0);
	this.instance_2.setTransform(0.1,0.05,0.55,0.55,0,0,0,73,60.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Since_50_1971, new cjs.Rectangle(-45.3,-33.4,87.69999999999999,88.3), null);


(lib.HP_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HealthPointLogoai("synched",0);
	this.instance.setTransform(-0.05,0,1,1,0,0,0,154.3,30);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HP_logo, new cjs.Rectangle(-154.3,-30,308.70000000000005,60), null);


(lib.HEAD3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.instance = new lib.HEAD_50_2linesai("synched",0);
	this.instance.setTransform(-158.05,-39.35,1.53,1.5299,0,0,0,-5.8,-1.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD3, new cjs.Rectangle(-149.2,-36.4,298.4,72.9), null);


(lib.HEAD2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD_NotDoneai("synched",0);
	this.instance.setTransform(0.05,-0.05,1.44,1.44,0,0,0,97.4,18.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-140.2,-27.1,280.4,54.2), null);


// stage content:
(lib.HP_notdone_728x90 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,216];
	// timeline functions:
	this.frame_0 = function() {
		if(!this.alreadyyExecuted){
		this.alreadyyExecuted=true;
			this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
		} else {
		gotoAndPlay(2);
		}
	}
	this.frame_216 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(216).call(this.frame_216).wait(1));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,2,0,3).p("Eg4ygG8MBxlAAAIAAN5MhxlAAAg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(217));

	// HEAD1
	this.instance = new lib.HEAD1();
	this.instance.setTransform(221,52.75);
	this.instance.shadow = new cjs.Shadow("#333333",3,3,12);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(137).to({alpha:0},9).to({_off:true},1).wait(70));

	// HEAD2
	this.instance_1 = new lib.HEAD2();
	this.instance_1.setTransform(580.9,49,0.92,0.92);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(64).to({_off:false},0).to({alpha:1},8).wait(75).to({alpha:0},9).to({_off:true},1).wait(60));

	// HEAD3
	this.instance_2 = new lib.HEAD3();
	this.instance_2.setTransform(198.35,47,1.0545,1.0545);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(157).to({_off:false},0).wait(60));

	// Since 50 1971
	this.instance_3 = new lib.Since_50_1971();
	this.instance_3.setTransform(426,36.85,0.76,0.76);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(157).to({_off:false},0).wait(60));

	// logo
	this.instance_4 = new lib.HP_logo();
	this.instance_4.setTransform(604.2,44.35,0.69,0.69,0,0,0,0.5,0.5);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(157).to({_off:false},0).wait(50).to({y:38.35},9).wait(1));

	// CTA
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#79232F").s().p("AgCAiIAVgiIgVghIASAAIAVAhIgVAigAgkAiIAVgiIgVghIATAAIAUAhIgUAig");
	this.shape_1.setTransform(660.325,76.975);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#79232F").s().p("AgdAiQgMgMAAgVQAAgSALgNQAMgPAVAAQATAAALAOQAJAMAAASIgBAKIg4AAQABAIAHAFQAHAEAJAAQANgBALgDIAEATQgNAFgTAAQgVAAgNgMgAAQgJQAAgHgCgEQgFgHgIAAQgHAAgEAHQgEAEgBAHIAfAAIAAAAg");
	this.shape_2.setTransform(647.875,77.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#79232F").s().p("AgaAtIAAg6IAAgdIAXAAIABAQIABAAQACgJAHgEQAGgFAHAAIAGAAIAAAaIgHAAQgQAAgDANIAAAFIAAAtg");
	this.shape_3.setTransform(640.075,77);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#79232F").s().p("AggAiQgNgMAAgWQAAgTANgOQAMgMAVAAQAUAAANAMQAMANAAAUQAAAWgOAMQgNAMgTAAQgTAAgNgMgAgNgRQgEAHAAAKQAAAMAFAHQAFAHAHAAQAIAAAFgHQAFgHgBgMQAAgKgDgHQgFgJgJAAQgIAAgFAJg");
	this.shape_4.setTransform(631.15,77.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#79232F").s().p("AAoAtIAAgvQAAgUgNAAQgJAAgDAKQgCADAAADIAAAzIgZAAIAAgwQAAgTgNAAQgJAAgEAKIgBAGIAAAzIgaAAIAAg7IgBgcIAXAAIABAMIABAAQAJgOARAAQARAAAHAPQAFgGAGgEQAIgFAJAAQANAAAIAJQAJAKAAATIAAAzg");
	this.shape_5.setTransform(618.225,77);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#79232F").s().p("AAOAtIAAgwQAAgTgNAAQgKAAgDALIgBAGIAAAyIgbAAIAAg7IgBgcIAXAAIACAMIABAAQAIgOASAAQAOAAAIAJQAJAKAAATIAAAzg");
	this.shape_6.setTransform(601.65,77);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#79232F").s().p("AgaAtIAAg6IAAgdIAXAAIABAQIABAAQACgJAHgEQAGgFAHAAIAGAAIAAAaIgHAAQgQAAgDANIAAAFIAAAtg");
	this.shape_7.setTransform(593.375,77);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#79232F").s().p("AggAmQgHgIAAgLQAAgQAOgJQAOgIAXABIAAgCQAAgMgPAAQgOAAgLAIIgFgSQAOgIATAAQAnAAAAAmIAAAeIABAVIgYAAIgCgJIAAAAQgJALgQAAQgMAAgJgIgAgMARQAAAKALgBQAEABAEgDQAEgDABgEIAAgFIAAgKIgBAAQgXAAAAAPg");
	this.shape_8.setTransform(584.625,77.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#79232F").s().p("AgdAiQgMgMAAgVQAAgSALgNQAMgPAVAAQATAAALAOQAJAMAAASIgBAKIg4AAQABAIAHAFQAHAEAJAAQANgBALgDIAEATQgNAFgTAAQgVAAgNgMgAAQgJQAAgHgCgEQgFgHgIAAQgHAAgEAHQgEAEgBAHIAfAAIAAAAg");
	this.shape_9.setTransform(575.375,77.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#79232F").s().p("AglA9IAAh5IAcAAIAABiIAvAAIAAAXg");
	this.shape_10.setTransform(566.425,75.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]},216).wait(1));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_1 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_2 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_3 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_4 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_5 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_6 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_7 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_8 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_9 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_10 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_11 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_12 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_13 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_14 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_15 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_16 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_17 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_18 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_19 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_20 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_21 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_22 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_23 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_24 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_25 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_26 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_27 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_28 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_29 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_30 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_31 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_32 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_33 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_34 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_35 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_36 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_37 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_38 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_39 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_40 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_41 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_42 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_43 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_44 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_45 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_46 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_47 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_48 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_49 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_50 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_51 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_52 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_53 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_54 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_55 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_56 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_57 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_58 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_59 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_60 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_61 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_62 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_63 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_64 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_65 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_66 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_67 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_68 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_69 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_70 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_71 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_72 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_73 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_74 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_75 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_76 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_77 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_78 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_79 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_80 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_81 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_82 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_83 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_84 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_85 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_86 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_87 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_88 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_89 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_90 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_91 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_92 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_93 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_94 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_95 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_96 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_97 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_98 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_99 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_100 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_101 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_102 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_103 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_104 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_105 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_106 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_107 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_108 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_109 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_110 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_111 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_112 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_113 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_114 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_115 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_116 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_117 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_118 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_119 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_120 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_121 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_122 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_123 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_124 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_125 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_126 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_127 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_128 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_129 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_130 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_131 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_132 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_133 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_134 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_135 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_136 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_137 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_138 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_139 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_140 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_141 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_142 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_143 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_144 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_145 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_146 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_147 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_148 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_149 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_150 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_151 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_152 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_153 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_154 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_155 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");
	var mask_graphics_156 = new cjs.Graphics().p("AKAVGMAAAgqLMAu4AAAMAAAAqLg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:364,y:-44}).wait(1).to({graphics:mask_graphics_1,x:364,y:-44}).wait(1).to({graphics:mask_graphics_2,x:364,y:-44}).wait(1).to({graphics:mask_graphics_3,x:364,y:-44}).wait(1).to({graphics:mask_graphics_4,x:364,y:-44}).wait(1).to({graphics:mask_graphics_5,x:364,y:-44}).wait(1).to({graphics:mask_graphics_6,x:364,y:-44}).wait(1).to({graphics:mask_graphics_7,x:364,y:-44}).wait(1).to({graphics:mask_graphics_8,x:364,y:-44}).wait(1).to({graphics:mask_graphics_9,x:364,y:-44}).wait(1).to({graphics:mask_graphics_10,x:364,y:-44}).wait(1).to({graphics:mask_graphics_11,x:364,y:-44}).wait(1).to({graphics:mask_graphics_12,x:364,y:-44}).wait(1).to({graphics:mask_graphics_13,x:364,y:-44}).wait(1).to({graphics:mask_graphics_14,x:364,y:-44}).wait(1).to({graphics:mask_graphics_15,x:364,y:-44}).wait(1).to({graphics:mask_graphics_16,x:364,y:-44}).wait(1).to({graphics:mask_graphics_17,x:364,y:-44}).wait(1).to({graphics:mask_graphics_18,x:364,y:-44}).wait(1).to({graphics:mask_graphics_19,x:364,y:-44}).wait(1).to({graphics:mask_graphics_20,x:364,y:-44}).wait(1).to({graphics:mask_graphics_21,x:364,y:-44}).wait(1).to({graphics:mask_graphics_22,x:364,y:-44}).wait(1).to({graphics:mask_graphics_23,x:364,y:-44}).wait(1).to({graphics:mask_graphics_24,x:364,y:-44}).wait(1).to({graphics:mask_graphics_25,x:364,y:-44}).wait(1).to({graphics:mask_graphics_26,x:364,y:-44}).wait(1).to({graphics:mask_graphics_27,x:364,y:-44}).wait(1).to({graphics:mask_graphics_28,x:364,y:-44}).wait(1).to({graphics:mask_graphics_29,x:364,y:-44}).wait(1).to({graphics:mask_graphics_30,x:364,y:-44}).wait(1).to({graphics:mask_graphics_31,x:364,y:-44}).wait(1).to({graphics:mask_graphics_32,x:364,y:-44}).wait(1).to({graphics:mask_graphics_33,x:364,y:-44}).wait(1).to({graphics:mask_graphics_34,x:364,y:-44}).wait(1).to({graphics:mask_graphics_35,x:364,y:-44}).wait(1).to({graphics:mask_graphics_36,x:364,y:-44}).wait(1).to({graphics:mask_graphics_37,x:364,y:-44}).wait(1).to({graphics:mask_graphics_38,x:364,y:-44}).wait(1).to({graphics:mask_graphics_39,x:364,y:-44}).wait(1).to({graphics:mask_graphics_40,x:364,y:-44}).wait(1).to({graphics:mask_graphics_41,x:364,y:-44}).wait(1).to({graphics:mask_graphics_42,x:364,y:-44}).wait(1).to({graphics:mask_graphics_43,x:364,y:-44}).wait(1).to({graphics:mask_graphics_44,x:364,y:-44}).wait(1).to({graphics:mask_graphics_45,x:364,y:-44}).wait(1).to({graphics:mask_graphics_46,x:364,y:-44}).wait(1).to({graphics:mask_graphics_47,x:364,y:-44}).wait(1).to({graphics:mask_graphics_48,x:364,y:-44}).wait(1).to({graphics:mask_graphics_49,x:364,y:-44}).wait(1).to({graphics:mask_graphics_50,x:364,y:-44}).wait(1).to({graphics:mask_graphics_51,x:364,y:-44}).wait(1).to({graphics:mask_graphics_52,x:364,y:-44}).wait(1).to({graphics:mask_graphics_53,x:364,y:-44}).wait(1).to({graphics:mask_graphics_54,x:364,y:-44}).wait(1).to({graphics:mask_graphics_55,x:364,y:-44}).wait(1).to({graphics:mask_graphics_56,x:364,y:-44}).wait(1).to({graphics:mask_graphics_57,x:364,y:-44}).wait(1).to({graphics:mask_graphics_58,x:364,y:-44}).wait(1).to({graphics:mask_graphics_59,x:364,y:-44}).wait(1).to({graphics:mask_graphics_60,x:364,y:-44}).wait(1).to({graphics:mask_graphics_61,x:364,y:-44}).wait(1).to({graphics:mask_graphics_62,x:364,y:-44}).wait(1).to({graphics:mask_graphics_63,x:364,y:-44}).wait(1).to({graphics:mask_graphics_64,x:364,y:-44}).wait(1).to({graphics:mask_graphics_65,x:364,y:-44}).wait(1).to({graphics:mask_graphics_66,x:364,y:-44}).wait(1).to({graphics:mask_graphics_67,x:364,y:-44}).wait(1).to({graphics:mask_graphics_68,x:364,y:-44}).wait(1).to({graphics:mask_graphics_69,x:364,y:-44}).wait(1).to({graphics:mask_graphics_70,x:364,y:-44}).wait(1).to({graphics:mask_graphics_71,x:364,y:-44}).wait(1).to({graphics:mask_graphics_72,x:364,y:-44}).wait(1).to({graphics:mask_graphics_73,x:364,y:-44}).wait(1).to({graphics:mask_graphics_74,x:364,y:-44}).wait(1).to({graphics:mask_graphics_75,x:364,y:-44}).wait(1).to({graphics:mask_graphics_76,x:364,y:-44}).wait(1).to({graphics:mask_graphics_77,x:364,y:-44}).wait(1).to({graphics:mask_graphics_78,x:364,y:-44}).wait(1).to({graphics:mask_graphics_79,x:364,y:-44}).wait(1).to({graphics:mask_graphics_80,x:364,y:-44}).wait(1).to({graphics:mask_graphics_81,x:364,y:-44}).wait(1).to({graphics:mask_graphics_82,x:364,y:-44}).wait(1).to({graphics:mask_graphics_83,x:364,y:-44}).wait(1).to({graphics:mask_graphics_84,x:364,y:-44}).wait(1).to({graphics:mask_graphics_85,x:364,y:-44}).wait(1).to({graphics:mask_graphics_86,x:364,y:-44}).wait(1).to({graphics:mask_graphics_87,x:364,y:-44}).wait(1).to({graphics:mask_graphics_88,x:364,y:-44}).wait(1).to({graphics:mask_graphics_89,x:364,y:-44}).wait(1).to({graphics:mask_graphics_90,x:364,y:-44}).wait(1).to({graphics:mask_graphics_91,x:364,y:-44}).wait(1).to({graphics:mask_graphics_92,x:364,y:-44}).wait(1).to({graphics:mask_graphics_93,x:364,y:-44}).wait(1).to({graphics:mask_graphics_94,x:364,y:-44}).wait(1).to({graphics:mask_graphics_95,x:364,y:-44}).wait(1).to({graphics:mask_graphics_96,x:364,y:-44}).wait(1).to({graphics:mask_graphics_97,x:364,y:-44}).wait(1).to({graphics:mask_graphics_98,x:364,y:-44}).wait(1).to({graphics:mask_graphics_99,x:364,y:-44}).wait(1).to({graphics:mask_graphics_100,x:364,y:-44}).wait(1).to({graphics:mask_graphics_101,x:364,y:-44}).wait(1).to({graphics:mask_graphics_102,x:364,y:-44}).wait(1).to({graphics:mask_graphics_103,x:364,y:-44}).wait(1).to({graphics:mask_graphics_104,x:364,y:-44}).wait(1).to({graphics:mask_graphics_105,x:364,y:-44}).wait(1).to({graphics:mask_graphics_106,x:364,y:-44}).wait(1).to({graphics:mask_graphics_107,x:364,y:-44}).wait(1).to({graphics:mask_graphics_108,x:364,y:-44}).wait(1).to({graphics:mask_graphics_109,x:364,y:-44}).wait(1).to({graphics:mask_graphics_110,x:364,y:-44}).wait(1).to({graphics:mask_graphics_111,x:364,y:-44}).wait(1).to({graphics:mask_graphics_112,x:364,y:-44}).wait(1).to({graphics:mask_graphics_113,x:364,y:-44}).wait(1).to({graphics:mask_graphics_114,x:364,y:-44}).wait(1).to({graphics:mask_graphics_115,x:364,y:-44}).wait(1).to({graphics:mask_graphics_116,x:364,y:-44}).wait(1).to({graphics:mask_graphics_117,x:364,y:-44}).wait(1).to({graphics:mask_graphics_118,x:364,y:-44}).wait(1).to({graphics:mask_graphics_119,x:364,y:-44}).wait(1).to({graphics:mask_graphics_120,x:364,y:-44}).wait(1).to({graphics:mask_graphics_121,x:364,y:-44}).wait(1).to({graphics:mask_graphics_122,x:364,y:-44}).wait(1).to({graphics:mask_graphics_123,x:364,y:-44}).wait(1).to({graphics:mask_graphics_124,x:364,y:-44}).wait(1).to({graphics:mask_graphics_125,x:364,y:-44}).wait(1).to({graphics:mask_graphics_126,x:364,y:-44}).wait(1).to({graphics:mask_graphics_127,x:364,y:-44}).wait(1).to({graphics:mask_graphics_128,x:364,y:-44}).wait(1).to({graphics:mask_graphics_129,x:364,y:-44}).wait(1).to({graphics:mask_graphics_130,x:364,y:-44}).wait(1).to({graphics:mask_graphics_131,x:364,y:-44}).wait(1).to({graphics:mask_graphics_132,x:364,y:-44}).wait(1).to({graphics:mask_graphics_133,x:364,y:-44}).wait(1).to({graphics:mask_graphics_134,x:364,y:-44}).wait(1).to({graphics:mask_graphics_135,x:364,y:-44}).wait(1).to({graphics:mask_graphics_136,x:364,y:-44}).wait(1).to({graphics:mask_graphics_137,x:364,y:-44}).wait(1).to({graphics:mask_graphics_138,x:364,y:-44}).wait(1).to({graphics:mask_graphics_139,x:364,y:-44}).wait(1).to({graphics:mask_graphics_140,x:364,y:-44}).wait(1).to({graphics:mask_graphics_141,x:364,y:-44}).wait(1).to({graphics:mask_graphics_142,x:364,y:-44}).wait(1).to({graphics:mask_graphics_143,x:364,y:-44}).wait(1).to({graphics:mask_graphics_144,x:364,y:-44}).wait(1).to({graphics:mask_graphics_145,x:364,y:-44}).wait(1).to({graphics:mask_graphics_146,x:364,y:-44}).wait(1).to({graphics:mask_graphics_147,x:364,y:-44}).wait(1).to({graphics:mask_graphics_148,x:364,y:-44}).wait(1).to({graphics:mask_graphics_149,x:364,y:-44}).wait(1).to({graphics:mask_graphics_150,x:364,y:-44}).wait(1).to({graphics:mask_graphics_151,x:364,y:-44}).wait(1).to({graphics:mask_graphics_152,x:364,y:-44}).wait(1).to({graphics:mask_graphics_153,x:364,y:-44}).wait(1).to({graphics:mask_graphics_154,x:364,y:-44}).wait(1).to({graphics:mask_graphics_155,x:364,y:-44}).wait(1).to({graphics:mask_graphics_156,x:364,y:-44}).wait(1).to({graphics:null,x:0,y:0}).wait(60));

	// watermelon
	this.instance_5 = new lib.watermelon();
	this.instance_5.setTransform(578,42);

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(147).to({alpha:0},9).to({_off:true},1).wait(60));

	// bkgd
	this.instance_6 = new lib._300x600_bkgd();
	this.instance_6.setTransform(2,89.95,0.6049,0.6049,-89.9899);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(217));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(344.5,-228,384,389.1);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 728,
	height: 90,
	fps: 24,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/HP_notdone_728x90_atlas_1.jpg?1619367807054", id:"HP_notdone_728x90_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;