(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"HP_notdone_300x600_atlas_1", frames: [[0,0,600,1200],[0,1202,600,540]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib._300x600_bkgd = function() {
	this.initialize(ss["HP_notdone_300x600_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib._300x600_watermelon = function() {
	this.initialize(ss["HP_notdone_300x600_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.watermelon = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib._300x600_watermelon();
	this.instance.setTransform(-150,-135,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.watermelon, new cjs.Rectangle(-150,-135,300,270), null);


(lib.HealthPointLogoai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HealthPointLogo.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#858E23").s().p("AhuDsQgKgGAUgwQATgvAYggQA5hOARg9QAJgggPgpQgIgXgZgtQgeg2BDgEQAZgCAaAGQAZAFACAHIACADQAYA5gFBDQgFBAgdA6QgQAfgdAlQgRAWgiApQgdAkgTARQgZAXgQAAIgFgBg");
	this.shape.setTransform(47.9903,36.3577);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#91190E").s().p("AggBTQgbgdgZgnQgdgugCgeQgDgrAvAGQAVACBCAZQAVAHASgMQATgLAMADQAFACAFAEQAbARgJAoQgJAhgcAkQgaAigZAMQgNAGgLAAQgSAAgQgRg");
	this.shape_1.setTransform(32.4896,28.7262);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#F17C29").s().p("AhADzQgmgcgWheQgShLAEhJQAGhXAkg5QAfgxBjgUQAygKAxgBQAJAAgDAIQgTA4goArIguAqQgcAYgLAWQgdAxAIBWQALBugFAeQgEAXgKAHQgFADgFAAQgJAAgLgJg");
	this.shape_2.setTransform(13.9834,25.2205);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#91190E").s().p("AgYCCIAAirQAAgKgDgEQgDgDgJAAIgJAAQgKAAAAgHQAAgHALAAIAXAAIAAhKQAAgHACgCQABgDAGgDIANgHIAEgBQAEgBABADQACADAAAIIAABUIAjAAQAKAAAAAHQAAAEgCACQgDABgHAAIgNAAQgNAAgEAEQgDAFAAAPIAACNQAAAcADAJQAEAIALAAQAGAAADgBIAJgHQAFgDACAAQABAAAAAAQABAAABAAQAAABABAAQAAAAABABQACACAAADQAAAEgGAFQgNANgXAAQgpAAAAgog");
	this.shape_3.setTransform(302.875,34.0714);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#91190E").s().p("AAhB7QgHAAAAgGQAAgEACgCQACgCAHAAIAGgBQAIgBACgFQACgGAAgTIAAh1QAAgkgJgNQgIgNgZAAQghAAgRAVQgQAVAAAsIAABcQAAAUACAGQACAFAIABIALACQAFAAAAAHQAAAGgHAAIhNAAQgHAAAAgGQAAgHAFAAIALgCQAIgBACgFQACgGAAgTIAAiIQAAgRgCgEQgCgEgHgBIgGgBQgIAAAAgGQAAgFAIgEIAjgSQAGgDAEAAQAIAAAAALIgBATQAfgdAqAAQAlAAAQARQAQAQAAAmIAAB+QAAAUACAGQACAFAIABIAKACQAGAAAAAHQAAAGgHAAg");
	this.shape_4.setTransform(282.475,38.35);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#91190E").s().p("AglCwQgHAAAAgHQAAgGAFgBIALgBQAIgBACgGQACgGAAgSIAAiLQAAgOgDgFQgDgEgJAAIgBAAQgKAAAAgGQAAgFAHgDIAkgTIAIgDQAIAAAAAJIAAC8QAAAUACAFQACAGAIABIALABQAFABAAAGQAAAHgHAAgAgRiHQgGgHAAgKQAAgJAGgHQAHgHAKAAQAJAAAHAHQAHAHAAAKQAAAJgHAHQgHAHgJAAQgKAAgHgHg");
	this.shape_5.setTransform(262.575,33.075);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#91190E").s().p("AhUBbQghgjAAg4QAAg4AhgiQAhgiA0AAQA0AAAgAiQAhAjAAA3QAAA5ggAiQggAig2AAQg0AAgggigAg5hOQgXAeAAAwQAAAyAWAdQAWAeAlAAQAkAAAWgeQAVgeAAgyQAAgxgVgdQgVgdglAAQgkAAgWAeg");
	this.shape_6.setTransform(244.475,38.675);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#91190E").s().p("Ah1DHQgNAAAAgIQAAgHAMgBIAGgBQALAAACgHQADgHAAgaIAAkSQAAgRgLgCIgEAAQgJgBAAgIQAAgMArgNQApgNApAAQA7AAAiAeQAhAeAAA2QAAAzgeAhQgfAfgxAAQgVAAgSgGQgRgGAAgIQAAgDADgBQACgDADAAIAFABIALADQAJACAOAAQAjAAAVgXQAUgaAAgrQAAgtgWgbQgWgagoAAQglAAgMAMQgMANAAAnIAAECQAAAaACAHQAEAHAKAAIAPABQANABAAAHQAAAIgNAAg");
	this.shape_7.setTransform(219.6,30.75);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#91190E").s().p("AAhDHQgIAAAAgGQAAgEACgCQACgBAHgBIAGgBQAIAAACgGQACgGAAgTIAAiBQAAgagKgMQgKgLgXAAQgiAAgPAVQgQAUAAAwIAABZQAAATADAGQACAFAIABIAGABQAHABACABQABACAAAEQAAAGgHAAIhMAAQgIAAAAgGQAAgGAGgBIAKgCQAIgBACgFQACgGAAgTIAAkjQAAgOgCgFQgDgEgHgBIgGAAQgHAAAAgGQAAgFAGgCIApgVQACgCADAAQAHAAAAAKIAACtQAegeAsAAQAjAAARAQQARARAAAiIAACDQAAATACAGQACAFAHABIALACQAGABAAAGQAAAGgHAAg");
	this.shape_8.setTransform(190.375,30.725);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#91190E").s().p("AgYCCIAAirQAAgKgDgEQgDgDgKAAIgIAAQgKAAAAgHQAAgHALAAIAXAAIAAhKIABgJQACgDAFgDIAOgHIAEgBQAHgBAAAOIAABUIAjAAQAKAAAAAHQAAAEgCACQgDABgHAAIgNAAQgNAAgEAEQgDAFAAAPIAACNQAAAcADAJQAEAIALAAQAFAAADgBIAKgHQAEgDADAAQABAAAAAAQABAAABAAQAAABABAAQAAAAABABQACACAAADQAAAEgGAFQgOANgWAAQgpAAAAgog");
	this.shape_9.setTransform(169.975,34.0741);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#91190E").s().p("AglDHQgHAAAAgHQAAgEABgBQACgCAHgBIAGAAQAIgBACgGQACgFAAgTIAAkqQAAgKgDgEQgEgDgJAAQgKAAAAgGQAAgGAGgBIAogWIAFgBQAIgBAAAKIAAFVQAAATADAGQACAGAIABIAKABQAFABAAAGQAAAHgHAAg");
	this.shape_10.setTransform(156.675,30.7705);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#91190E").s().p("AhNBrQgXgSAAgeQAAgbAUgWQATgVAkgMQAVgJASAAQALAAgBAIQABAGgLACQgkAHgWATQgUAUgBAcQABAWAOAOQANAPAVAAQAWAAAOgPQAPgPACgZQADgaAAglQAAg/gJgQQgIgRggAAQgbAAgcAUQgHAGgDAAQgKAAABgJQAAgFAFgEQANgNAWgHQAVgIAWAAQAmAAASASQASARAAAmIAAB/QAAASACAGQABAGAHABIACAAIADAAIAGACQAGABgBAGQAAAGgGAAIgpAAQgNAAAAgLIAAgLQgOAPgOAGQgOAGgUAAQgiAAgVgTg");
	this.shape_11.setTransform(138.4,38.525);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#91190E").s().p("AhFBaQgggjAAg2QAAg1AgglQAhgkAwABQAgAAAZATQAaAVAAAYQAAAKgFAGQgFAGgOAJIheA3QgGAFgFgBQgIABAAgIQAAgDACgCIAHgGIA/glQARgKAGgIQAHgHAAgKQAAgSgQgQQgPgOgUAAQgfAAgVAeQgUAeAAAwQAAAxAWAeQAWAdAkAAQAnABAegkQAGgFACgBQAIAAAAAJQAAAIgOANQgfAcguABQgwAAgggkg");
	this.shape_12.setTransform(115.125,38.65);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#91190E").s().p("ABBDEQgNgBAAgHQAAgHAMgCIAGAAQALgBACgHQADgGAAgbIAAh0IgBgXQgBgIgEgCQgEgEgFAAQgFgBgQAAIhrAAQgTAAgEAGQgEAGAAAZIAAB1QAAAbACAGQADAHAKABIAHAAQAMACAAAHQAAAHgNABIhRAAQgOgBAAgHQAAgHAMgCIAHAAQALgBACgHQADgGAAgbIAAkSQAAgcgDgHQgCgGgLgBIgHgBQgMAAAAgIQAAgIANAAIBRAAQANAAAAAIQAAAEgCACQgDABgHABIgGABQgLABgCAGQgCAHAAAbIAABmICpAAIAAhlQABgbgDgIQgCgGgLgBIgGgBQgMAAAAgIQAAgIAMAAIBSAAQANAAAAAIQAAAIgLAAIgHABQgLABgCAGQgDAHAAAbIAAESQAAAbADAHQACAHALABIAHAAQALACAAAHQAAAHgMABg");
	this.shape_13.setTransform(86.475,31.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,308.8,60);


(lib.HealthPoint_Sinceai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HealthPoint_Since.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#71212C").s().p("AgYAdQgMgLAAgSQAAgPALgMQAKgMAQAAQARAAAKANQAJALAAAQIAAAFIg3AAQADAUASAAQALAAAJgKIAKAKQgLAOgTAAQgQAAgLgLgAgTgEIAnAAQgDgUgQAAQgRAAgDAUg");
	this.shape.setTransform(32.95,6.675);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#71212C").s().p("AgXAcQgLgLAAgRQAAgPALgMQALgMAQAAQATAAAMANIgLAMQgJgJgLAAQgIAAgHAHQgGAHAAAJQAAAKAGAIQAHAHAJAAQAKAAAKgKIAKALQgNAOgSAAQgQAAgLgMg");
	this.shape_1.setTransform(25.075,6.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#71212C").s().p("AARAnIAAgrQAAgSgRAAQgGAAgFAFQgFAFAAAJIAAAqIgSAAIAAhLIASAAIAAALQAJgNAOAAQANAAAHAIQAIAIAAAOIAAAvg");
	this.shape_2.setTransform(16.7,6.6);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#71212C").s().p("AgIA1IAAhMIARAAIAABMgAgJgiIAAgSIASAAIAAASg");
	this.shape_3.setTransform(10.4,5.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#71212C").s().p("AgmAkIALgNQAOANAQAAQATAAgBgNQABgFgFgDQgFgEgMgDQgSgEgHgFQgJgHAAgOQAAgNAKgIQAJgIAPAAQAUAAAQANIgJANQgOgKgNAAQgHAAgFADQgEAEAAAFQAAAGAEADQAGADANAEQAQAEAIAFQAIAIAAAMQAAAOgKAIQgJAIgRAAQgXAAgSgQg");
	this.shape_4.setTransform(3.9,5.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,36.7,10.7);


(lib.HealthPoint_1971ai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HealthPoint_1971.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#71212C").s().p("AACAzIAAhTIgRAFIgEgOIAagJIANAAIAABlg");
	this.shape.setTransform(25.025,5.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#71212C").s().p("AgdAzIAshVIgxAAIAAgQIBGAAIAAAOIgtBXg");
	this.shape_1.setTransform(18.55,5.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#71212C").s().p("AgkAoIAKgNQALAJAMAAQAKAAAHgJQAGgIABgPQgJALgOAAQgQAAgKgJQgKgIAAgOQAAgPAKgKQALgKAQAAQARAAALAKQAMAMAAAbQAAAYgMAPQgLAPgTAAQgSAAgPgMgAgPgeQgFAFAAAIQgBAIAHAFQAFAEAJAAQAJAAAFgEQAGgFAAgIQAAgIgGgFQgGgGgIAAQgJAAgGAGg");
	this.shape_2.setTransform(9.8,5.225);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#71212C").s().p("AACAzIAAhTIgRAFIgEgOIAagJIANAAIAABlg");
	this.shape_3.setTransform(1.975,5.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,27,10.5);


(lib.HealthPoint_50onlyai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HealthPoint_50only.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjIDoQhLhcAAiLQAAiKBMhdQBOhgB6AAQB6AABOBfQBLBcAACLQAACKhMBdQhPBgh5ABQh6gBhOhfgAh1ihQgrBAAABhQAABgAsBAQAtBDBIAAQBIAAAthCQArhAAAhgQAAhggshAQguhDhHAAQhJAAgsBBg");
	this.shape.setTransform(97.575,64.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjoDhIBFhQQBRBLBRAAQA4AAAjgdQAigfAAgxQAAgygkgcQgkgcg6gBQg6AAg7AcIhDgrIASk2IF5AAIAABjIkZAAIgKCUQAxgSAzAAQBhAAA7AyQA/A0AABgQAABihAA7QhAA7hpAAQiEAAhkhhg");
	this.shape_1.setTransform(42.475,65.25);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#71212C").s().p("AjIDoQhLhcAAiLQAAiKBMhdQBPhgB5AAQB7AABNBfQBLBcAACLQAACKhMBdQhPBgh5AAQh7AAhNhfgAh1igQgrA/AABhQAABgAsBBQAtBCBIAAQBIAAAthCQArg/AAhhQAAhggshAQgthDhIAAQhIAAgtBCg");
	this.shape_2.setTransform(99.45,66.575);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#71212C").s().p("AjoDhIBEhQQBTBMBQAAQA4AAAjgeQAigfAAgyQAAgwgkgdQgkgcg6AAQg6AAg7AcIhDgsIASk2IF5AAIAABjIkZAAIgKCUQA0gSAwAAQBhAAA7AxQA/A0AABiQAABhhAA7QhAA7hpAAQiFAAhjhhg");
	this.shape_3.setTransform(44.375,67.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#AE222D").s().p("Ai4HSQiaihiGjbQijkHgLipQgQjvEFAgQBgAMCVAyID2BaQBGAZA6gLQAngIAygfQA6gkATgHQAsgRAwAQQAcAJAgAUQCYBhg3DhQgtC4ifDNQitDfigAyQgsAOgqAAQhqAAhYhbg");
	this.shape_4.setTransform(67.2247,65.8653);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#F9762B").s().p("AmVGWQioioAAjuQAAjtCoioQCoipDtAAQDuAACoCpQCoCoAADtQAADuioCoQioCojuABQjtgBioiog");
	this.shape_5.setTransform(57.425,58.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#8BAC43").s().p("AmVGWQipioAAjuQAAjtCpioQCoioDtAAQDuAACoCoQCoCoABDtQgBDuioCoQioCojuAAQjtAAioiog");
	this.shape_6.setTransform(88.25,57.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,145.7,121.6);


(lib.HEAD1_300x600ai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HEAD1_300x600.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#70202C").s().p("Ag0BRIAEgGQAGgJAEgMQAEgNAFgeIAEgdQABgFgGAAQgEAAAAgDQAAgDACgCQABgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAQAGAAACgHQAJgrAmAAQAMAAAHAFQAGAFABAHQgBAHgDADQgEAEgGAAQgHAAgDgIQgCgIgBAAQgFAAgDAJQgDAIAAAGQAAAHADACQAFADAMAAQABAAABAAQABABAAAAQABAAAAABQAAAAAAABQAAAJgGAAQgNAAgFAEQgGADgBAJIgNA7QgDANgQAKQgOAJgIAAQgGAAAAgEg");
	this.shape.setTransform(41.85,-28.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#70202C").s().p("AghAhQgKgJAAgQQAAgTAPgPQAPgPAYAAQAPAAAJAIQAJAJAAANQAAAWgNAPQgOAQgXAAQgQAAgLgJgAADgZQgLALAAASQAAAJAFAFQADAFAIAAQAHAAAFgGQAFgGAAgIQAAgGgGgCQgKgFAAgGQAAgEACgDIACgDQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAQgDAAgFADg");
	this.shape_1.setTransform(33.75,-27.675);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#70202C").s().p("AgaAkQgKgGAAgKQAAgGAEgEQADgEAFAAQALAAAAAKQAAALAHAAQAGAAAAgHQAAgHgNgKQgNgJAAgKQAAgMALgHQAKgGAOAAQAcAAAAASQAAANgNAAQgEAAgCgCQgDgDAAgEIABgEIABgEQAAgDgFAAQgDAAgCACQgCADAAADQAAAIAOAJQAOAJAAAKQAAANgJAHQgKAIgQAAQgPAAgJgGg");
	this.shape_2.setTransform(20.525,-27.725);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#70202C").s().p("AgnAjQAAgEAFgXQAGgXAAgHIgBgFIgBgEQAAgEAJgDQAJgCALAAQAIAAAAAGIgCALQAJgQAOAAQAMAAAAAMQAAAIgEAGQgFAHgIAAQgFAAgDgEQgCgCgBgEQgDABgGAKQgDAGgDANQgDANAAAHQAAAGgGAAIgWABQgFAAAAgGg");
	this.shape_3.setTransform(13.3,-27.675);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#70202C").s().p("AAGAiIgEgHQgNAOgTAAQgMAAgIgHQgIgJAAgOQAAgVANgOQAOgQAaAAQAHAAAGACIAIADIAKgDIALgCQAEAAAAAEIgEASQgFARAAAKQAAAFADADQACADAEAAQADAAAHgFQACgDACAAQABAAABAAQAAABABAAQAAABABAAQAAABAAABQAAADgEAFQgOARgTAAQgKAAgGgHgAgTgNQgFAMAAANQAAAMAJAAQAIAAAFgMQAGgOAAgTQAAgIgHAAQgKAAgGAQg");
	this.shape_4.setTransform(4.325,-27.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#70202C").s().p("AguAGQAAgTAPgNQAPgPAYAAQAaAAAAATQAAAMgMAIQgNAJgSABQAAAHAFAFQAFAEAJAAQAMAAAQgNIAFgDQABAAABAAQAAABABAAQAAAAABABQAAAAAAABQAAADgGAGQgJAKgIAEQgMAIgQAAQgqAAAAgkgAgCgVQgHAIAAALQAKgBAHgIQAHgHAAgGQAAgGgGAAQgHAAgEAJg");
	this.shape_5.setTransform(-5.475,-27.675);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#70202C").s().p("AgqBHQgLgJAAgNQAAgOAJgIQAHgIAHAAQABAAAAABQABAAAAAAQAAAAABABQAAAAAAABIgBAEQgCACAAADQAAAMAPABQAVgBAIg1QgQAOgXAAQgJABgHgFQgGgGAAgJQAAgJAFgQQAEgPAAgEIgBgEIgBgFQAAgDAJgDQAIgDAMAAQAJAAAAAGQAAAFgFARQgFARAAAIQAAAJAHgBQAIABAIgLQAHgMAAgVIgBgEIgBgFQAAgDAJgDQAJgDALAAQAJAAAAAGIgCANIgIAoQgIArgIAUQgPAhgeAAQgPAAgKgHg");
	this.shape_6.setTransform(-15.675,-24);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#70202C").s().p("AgtBBQgLgOgBgaQAAgqAXgeQAVgdAcAAQATAAAMAMQALAOABAaQAAAlgUAeQgVAigfAAQgTAAgMgMgAgLghQgJAeAAAtQAAAJAEAFQADAGAGAAQANAAAJgnQAHgfABgjQAAgTgKgBQgOAAgKAeg");
	this.shape_7.setTransform(-31.1,-31.15);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#70202C").s().p("AgoA+QgKgNAAgSQAAgHAEAAQADAAACAGQAFAQASAAQALAAAHgJQAFgIAAgMQAAgIgEgHQgFgIgLAAIgKABIgCAAQgEAAgCgDQgDgCAAgEIAFgRQAFgSACgMQAAgFAEgEQAEgEAFAAIAKACQAIACAMAAQAVAAAHgFQAEAAAAAEQAAAEgEAJQgGAMgGADQgEACgIAAQgJAAgSgFQgCANgFAMIAKgBQASAAANALQANALAAASQAAAZgPAQQgPARgXAAQgTAAgLgOg");
	this.shape_8.setTransform(-41.975,-31.125);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#70202C").s().p("AgKALQgCgCAAgGQAAgFAFgGQAFgGAFAAQAKAAAAAMQAAAFgEAGQgGAGgGAAQgEAAgDgEg");
	this.shape_9.setTransform(49.925,37.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#70202C").s().p("AgaAuQgGgGAAgKQAAgJAEgOQADgMAAgFQAAgBAAAAQAAgBAAAAQgBAAAAAAQgBgBgBAAQAAAAgBgBQgBAAAAAAQgBgBAAAAQAAgBAAgBQAAgGAEAAQARAAAOgYQADgGAEAAQAEAAAAAFQAAAFgDAOQgBAFAJABQABAAABAAQAAAAABAAQAAAAAAABQABAAAAABQAAAJgHAAQgIgBgCAJQgGATAAAIQAAAKALAAQAEAAAJgIQADgDACABQABAAAAAAQABAAAAAAQABABAAAAQAAABAAAAQAAADgCADQgGAHgKAHQgMAIgKAAQgNABgGgIg");
	this.shape_10.setTransform(44.95,33.45);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#70202C").s().p("AgXA5QgGgGAAgJQAAgJAEgOQAEgOAAgEIgCgHQAAgEAJgDQAIgCAKAAQAJAAAAAGQAAAEgEAOQgEAPAAAJQAAAKAIAAQAEAAAFgFQADgDACAAQABAAAAAAQABABAAAAQABABAAAAQAAABAAABQAAACgEAGQgOAQgRAAQgMAAgGgGgAgLggQgEgEAAgGQAAgHAGgHQAGgGAGAAQAOAAAAANQAAAHgGAHQgGAHgGAAQgFAAgFgEg");
	this.shape_11.setTransform(39.375,32.475);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#70202C").s().p("AgZAiQgJgFAAgLQAAgFADgEQAEgDAEAAQALAAAAAJQAAAKAHAAQAFAAAAgGQAAgHgMgJQgNgJAAgKQAAgLALgHQAJgFAOAAQAagBAAASQAAANgLgBQgEABgDgDQgCgDAAgDIACgIQAAgDgFAAQgDAAgCACQgCADAAADQAAAHAOAKQANAIAAAJQAAANgJAHQgJAIgQAAQgOAAgJgHg");
	this.shape_12.setTransform(27.825,34.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#70202C").s().p("AAGBDIgFgHQgMANgRAAQgbAAAAgdQAAgWANgOQANgNAVAAQAJAAAIAEQAHgfABgLQAAgNgKAAQgBAAgBAAQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgEAIgFQAKgFAKAAQAUAAABAUQAAAKgLAjQgLAhABAQQgBAKAJAAQAEAAAGgEQACgDACAAQABAAABAAQAAAAABABQAAAAAAABQAAABAAAAQAAADgEAGQgNAQgTAAQgJAAgFgGgAgSAVQgFAMAAAOQAAAKAIAAQAJgBAEgLQACgGABgJQADgLAAgHQAAgHgHgBQgJABgGAQg");
	this.shape_13.setTransform(19.65,31.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#70202C").s().p("AgsAGQAAgSAOgNQAPgOAXAAQAZAAAAASQAAALgMAJQgMAIgRABQAAAHAFAEQAEAFAJAAQALAAAQgNIAFgDQAAAAABAAQABAAAAABQAAAAABAAQAAABAAABQAAADgFAFQgTAVgZAAQgoAAAAgigAgCgUQgGAIAAALQAJgCAHgIQAGgGAAgGQAAgFgGAAQgGAAgEAIg");
	this.shape_14.setTransform(10.225,34.825);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#70202C").s().p("AgsAGQAAgSAOgNQAPgOAXAAQAZAAAAASQAAALgMAJQgMAIgRABQAAAHAFAEQAEAFAJAAQALAAAQgNIAFgDQABAAAAAAQABAAAAABQAAAAABAAQAAABAAABQAAADgFAFQgTAVgZAAQgoAAAAgigAgCgUQgGAIAAALQAJgCAHgIQAGgGAAgGQAAgFgGAAQgGAAgEAIg");
	this.shape_15.setTransform(1.975,34.825);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#70202C").s().p("AAFAiQgGgFAAgJQAAgIAEgLQADgKAAgFQABgHgGAAQgHAAgIAQQgEAGgDAMQgDANAAAHQAAAFgGAAIgVACQgFAAgBgGQABgEAFgWQAFgWAAgHIgCgIQAAgEAJgDQAIgDALAAQAJAAAAAHIgCALQAFgGAIgFQAKgHAKAAQATAAAAAQQAAAGgEAMQgDAKAAAFQAAAJAIAAQAFAAAEgFQADgCACAAQABAAABAAQAAAAABABQAAAAAAABQABAAAAABQAAADgFAFQgOARgRAAQgLAAgGgGg");
	this.shape_16.setTransform(-7.5,34.825);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#70202C").s().p("AgfAgQgLgJAAgPQAAgSAOgOQAQgQAXAAQAOAAAJAIQAJAJAAANQgBAVgNAOQgNAQgVAAQgRAAgJgJgAAEgYQgMAKAAASQAAAIAFAFQADAFAIAAQAHAAAEgGQAFgGAAgHQAAgGgFgCQgKgEAAgGQAAgEACgDIACgDQAAgBgBAAQAAAAAAgBQAAAAgBAAQAAAAgBAAQgCAAgEADg");
	this.shape_17.setTransform(-22.2,34.825);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#70202C").s().p("AAAA2QAAgIADgMQAEgMAAgEQAAgHgGABQgGAAgJAPQgCAGgEAPQgEAOAAAFQAAAEgFABIgWABQgFAAAAgGQAAgJALgpQALgpAAgTQAAgNgJAAQgBAAgBAAQgBAAAAAAQgBgBAAAAQAAgBAAAAQAAgEAJgFQAIgFALAAQATAAABAUQgBARgNAsQAOgOARAAQAWAAgBAQQABAGgEALQgEALAAAFQAAAJAIgBQADAAAGgEQABgBABgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAABAAQABAAAAABQABAAAAABQAAABAAAAQAAADgEAGQgMAQgUAAQgVAAAAgTg");
	this.shape_18.setTransform(-31.4,31.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#70202C").s().p("AgJAXQgPARgXAAQgKAAgHgGQgGgGAAgIQAAgJAFgNQAEgOAAgFIgCgIQAAgEAJgDQAIgDALAAQAIAAAAAHQAAAFgEAPQgEAPAAAIQAAAKAHAAQAJAAAGgMQAHgMAAgSIgCgIQAAgEAIgDQAIgDALAAQAIAAAAAHQAAAFgEAQQgEAOAAAIQAAAKAJAAQAIAAAGgKQAGgJAAgJQAAgEgEgEQgEgFAAgEQAAgHAEgEQAFgEAGAAQAQAAAAATQAAAUgOASQgPAWgXAAQgTAAgJgRg");
	this.shape_19.setTransform(-44.125,34.825);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#70202C").s().p("ABEBfQgKgJAAgNQAAgNAJgJQAHgHAGAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIgBAEIgBAGQAAAMAPAAQAMAAAIgSQAFgMAEgZQgPAQgYAAQgKAAgGgGQgFgFgBgGQgNARgUAAQgLAAgGgGQgHgFAAgJQAAgJAEgKQAEgMAAgFQAAgHgGAAQgIAAgHAQQgDAHgEAMQgEAOAAAHQAAAGgGAAIgWABQgFAAAAgGIABgHQgNANgQAAQgKAAgGgHIgEgHQgOAOgTAAQgMAAgIgIQgIgIAAgOQAAgVANgOQAOgRAaAAQAIAAAHADIAHACIAKgCIALgDQAEAAAAAEIgEATQgFAQAAAMQAAAKAJAAQAFAAAFgGIADgCIABgEQAGgXAAgIIgCgIQAAgEAJgDQAJgDALAAQAJAAAAAHIgCAMQAQgTASAAQAUAAAAARQAAAGgDAMQgEAMAAAFQAAAJAIAAQAFAAAFgGQABAAAAgBQABAAAAgBQABAAABAAQAAAAAAAAIAEgPQAEgQAAgEIgCgIQAAgEAJgDQAJgDALAAQAJAAAAAHQAAAFgFARQgEAQAAAIQAAAIAHAAQAJAAAHgKQAIgLAAgWIgCgIQAAgEAJgDQAIgDAMAAQAIAAAAAHQAAAHgKAsQgIAugIASQgPAhgfAAQgPAAgKgHgAh4gaQgFANAAANQAAAMAJAAQAIAAAFgMQAHgNAAgVQAAgHgIAAQgKAAgGAPgAnFBAQAAgCAEgEQAGgJADgMQAEgOAGgcIAEgeQAAgFgFAAQgEAAAAgDQAAgDACgDQAAAAABgBQAAAAABgBQAAAAAAAAQABAAAAAAQAEAAACgCQABgBABgEQAKgrAnAAQAMAAAHAFQAGAFAAAHQAAAOgNAAQgHAAgDgIQgCgIgCAAQgEAAgDAJQgDAHAAAHQAAAGADADQAEADANAAQAEAAAAADQAAAIgGAAQgNAAgGAEQgFAEgCAIIgNA8QgDANgQAKQgOAJgJAAQgFAAAAgEgAF9AVQgFgEgDgGIAAABQgOARgTAAQgLAAgHgGQgGgFAAgJQAAgJAEgKQAEgMAAgFQAAgHgGAAQgJAAgHAQQgEAHgEAMQgEAOAAAHQAAAGgFAAIgWABQgGAAAAgGQAAgEAGgXQAFgXAAgIIgCgIQAAgEAJgDQAJgDAMAAQAIAAAAAHIgCAMQAGgGAIgGQAMgHAKAAQAUAAAAARQAAAGgEAMQgEAMAAAFQAAAJAJAAQAEAAAGgGIABgBIgBgGQAAgUAPgOQAPgOAZAAQAaAAAAATQAAALgMAJQgMAKgTABQAAAGAFAFQAFAEAIAAQAKAAAJgHIAGgDQABAAABAAQAAABABAAQAAAAABABQAAABAAAAQAAAEgGAFQgOAQgWAAQgUAAgLgJgAGdgiQgGAJAAALQAKgCAHgIQAHgGAAgGQAAgGgGAAQgHAAgFAIgACxAVQgKgKAAgOQAAgUAOgPQAQgQAZAAQAPAAAJAJQAJAIAAAOQAAAWgNAPQgPAQgXAAQgRAAgKgJgADWglQgMAKAAAUQAAAHAEAGQAFAFAHAAQAIAAAFgHQAFgFAAgHQAAgHgGgDQgKgEAAgGQAAgEACgDIACgDQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgDAAgFAEgAltAVQgKgKAAgOQAAgUAPgPQAPgQAaAAQAOAAAJAJQAJAIAAAOQAAAWgNAPQgOAQgXAAQgSAAgKgJgAlHglQgNAKAAAUQAAAHAFAGQAEAFAIAAQAHAAAFgHQAFgEAAgIQAAgIgFgCQgLgEAAgGQAAgEACgDIACgDQAAgBAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQgDAAgEAEgAkcAXQAAgEAFgXQAGgXAAgIIgCgIQAAgEAJgDQAIgDAMAAQAJAAAAAHQAAAGgCAEQAIgPAPAAQAMAAAAAMQAAAHgEAHQgFAGgIAAQgLAAAAgKQgDABgGALQgDAGgEAMQgDAOAAAHQAAAGgGAAIgWABQgFAAAAgGg");
	this.shape_20.setTransform(0.025,15.125);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#70202C").s().p("AGOBEQgMgKAAgSQAAgTAOgOQAPgNAZAAQAaAAAAASQAAALgMAJQgMAJgTACQAAAGAFAFQAGAFAHAAQAJAAAKgHIAGgDQABAAABAAQAAAAABABQAAAAABABQAAAAAAABQAAADgGAGQgPAPgVAAQgTAAgLgIgAGtAMQgGAJAAALQAKgCAIgIQAGgHAAgFQAAgGgGAAQgGAAgGAIgAB8BDQgMgJAAgQQAAgVAOgOQAQgNAYAAQAbAAAAARQAAAQgPAAQgKAAAAgIQAAgDACgEIACgEQAAgEgFAAQgGAAgGAKQgHAKAAANQAAAKAHAGQAFAGAJAAQANAAAOgNIABgBQAAgVANgOQAOgQAaAAQAIAAAHADIAHACIAKgCIAMgDQADAAAAAEIgEARQgFARAAAMQAAAKAJAAQAFAAAFgFIAEgCIABgFQAFgXAAgIIgCgIQAAgDAJgDQAJgDALAAQAJAAAAAGIgBAKQAHgPAPAAQAMAAAAALQAAAIgEAGQgFAHgIAAQgKAAAAgKQgEACgFAJQgEAHgDANQgEAOAAAHQAAAFgGAAIgVABQgGAAAAgFIABgHQgMAMgRAAQgKAAgGgGIgEgHQgOANgTAAQgMAAgIgHQgFgFgBgHQgKAJgHAEQgMAHgQAAQgTAAgLgJgADsAUQgFANAAANQAAAMAJAAQAIAAAGgMQAGgPAAgTQAAgHgHAAQgKAAgHAPgAljA6QgNARgUAAQgXAAAAgUQAAgHAFgNQAEgNAAgEQAAgGgHAAQgHAAgJAQQgDAGgEAQQgEAOAAAFQAAAFgFAAIgXABQgFAAAAgFQAAgJAMgsQALgqAAgUQAAgNgKAAQgBAAAAAAQgBAAgBgBQAAAAAAAAQgBgBAAgBQAAgEAJgFQAJgFALAAQAWAAAAAUQAAAQgPAwQAOgPATAAQAWAAAAARQAAAGgDAMQgEALAAAGQAAAIAIAAQAFAAAEgFIABgBIAAgIQAAgTAOgOQAQgNAZAAQAZAAAAASQAAALgMAJQgMAJgTACQAAAHAFAEQAFAFAJAAQAMAAAQgNIACgCQAAgUAMgOQAOgQAaAAQAIAAAHADIAHACIAKgCIAMgDQAEAAAAAEIgFARQgFARAAAMQAAAKAJAAQAFAAAFgFIAAAAQABgMAJgcQAKggAAgWQAAgNgKAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBQAAgEAIgFQAKgFAKAAQAWAAAAAUQAAALgKAmQgKAlAAANQAAAKAIAAQAEAAAGgFIAAgBQABgIADgMQAEgOAAgGQAAAAAAgBQAAAAgBAAQAAAAgBgBQAAAAgBAAQgEgBAAgDQAAgHAEAAQASAAAQgYQADgGAEAAQAEAAAAAEQAAAGgEAPQAAABAAABQAAAAABABQAAAAAAABQAAAAABAAIAHABQABAAABAAQAAABABAAQAAAAABABQAAAAAAABQAAADgCADQgBAAAAABQgBAAAAABQgBAAAAAAQgBAAAAAAQgJAAgCAIQgGAVAAAJQAAAKAKAAQAGAAAJgIIACgBIAHgcQALgqAAgUQAAgNgKAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBAAgBQAAgEAIgFQAKgFAKAAQAKAAAFAFQAGAGAAAJQAAAQgOAwQANgPAUAAQAWAAAAARQAAAGgEAMQgEALAAAGQAAAKAGAAQACAAAFgDIAEgCQAAAAABAAQAAABABAAQAAAAAAABQAAABAAAAQAAADgDAEQgMAOgOAAQgMAAgGgFQgGgGAAgJQAAgHAEgNQAEgNAAgEQAAgGgGAAQgIAAgIAQQgDAGgEAQQgDAOAAAFQAAAFgGAAIgXABQgFAAAAgFIACgLIgKAIQgMAIgLAAQgNAAgHgHQgEgDgBgFQgNAPgSAAQgNAAgHgHQgDgDgBgEQgNAOgSAAQgKAAgGgGIgEgHQgOANgTAAQgMAAgHgHQgFgFgCgIQgTAVgbAAQgdAAgJgSgAjqAUQgFANAAANQAAAMAJAAQAIAAAGgMQAGgPAAgTQAAgHgHAAQgKAAgHAPgAk7AMQgGAJAAALQAKgCAIgIQAGgHAAgFQAAgGgGAAQgGAAgGAIg");
	this.shape_21.setTransform(0.025,-10.325);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AGvgkQAAgGgGAAQgHAAgFAIQgGAJAAALQAKgCAHgIQAHgGAAgGgAFyABQgBgCAAgEQAAgUAPgOQAPgOAZAAQAaAAAAATQAAALgMAJQgMAKgTABQAAAGAFAFQAFAEAIAAQAKAAAJgHQAFgDABAAQAEAAAAADQAAAEgGAFQgOAQgWAAQgUAAgLgJQgFgEgDgGQAAABAAAAQgOARgTAAQgLAAgHgGQgGgFAAgJQAAgJAEgKQAEgMAAgFQAAgHgGAAQgJAAgHAQQgEAHgEAMQgEAOAAAHQAAAGgFAAQgSABgEAAQgGAAAAgGQAAgEAGgXQAFgXAAgIQgCgFAAgDQAAgEAJgDQAJgDAMAAQAIAAAAAHQAAAEgCAIQAGgGAIgGQAMgHAKAAQAUAAAAARQAAAGgEAMQgEAMAAAFQAAAJAJAAQAEAAAGgGQAAAAABgBQACgBABAAQAEAAAAADQAAADgEAFQgCgEgBgGgAmBg/QAAAGADADQAEADANAAQAEAAAAADQAAAIgGAAQgNAAgGAEQgFAEgCAIQgJAugEAOQgDANgQAKQgOAJgJAAQgFAAAAgEQAAgCAEgEQAGgJADgMQAEgOAGgcQAEgaAAgEQAAgFgFAAQgEAAAAgDQAAgDACgDQACgCABAAQAEAAACgCQABgBABgEQAKgrAnAAQAMAAAHAFQAGAFAAAHQAAAOgNAAQgHAAgDgIQgCgIgCAAQgEAAgDAJQgDAHAAAHgAj7AWQAAAGgGAAQgSABgEAAQgFAAAAgGQAAgEAFgXQAGgXAAgIQgCgFAAgDQAAgEAJgDQAIgDAMAAQAJAAAAAHQAAAGgCAEQAIgPAPAAQAMAAAAAMQAAAHgEAHQgFAGgIAAQgLAAAAgKQgDABgGALQgDAGgEAMQgDAOAAAHgAgxAQQgNANgQAAQgKAAgGgHIgEgHQgOAOgTAAQgMAAgIgIQgIgIAAgOQAAgVANgOQAOgRAaAAQAIAAAHADQAGACABAAQACAAAIgCQAIgDADAAQAEAAAAAEQAAACgEARQgFAQAAAMQAAAKAJAAQAFAAAFgGQACgBABgBQABgBAAgDQAGgXAAgIQgCgFAAgDQAAgEAJgDQAJgDALAAQAJAAAAAHQAAAEgCAIQAQgTASAAQAUAAAAARQAAAGgDAMQgEAMAAAFQAAAJAIAAQAFAAAFgGQADgCACAAIAAAAQADAAAAADQAAADgEAGIAAAAQAAgCAAgBQAAgEABgFQABgGACgJQAEgQAAgEQgCgFAAgDQAAgEAJgDQAJgDALAAQAJAAAAAHQAAAFgFARQgEAQAAAIQAAAIAHAAQAJAAAHgKQAIgLAAgWQgCgFAAgDQAAgEAJgDQAIgDAMAAQAIAAAAAHQAAAHgKAsQgIAugIASQgPAhgfAAQgPAAgKgHQgKgJAAgNQAAgNAJgJQAHgHAGAAQADAAAAACQAAABgBADQgBADAAADQAAAMAPAAQAMAAAIgSQAFgMAEgZQgPAQgYAAQgKAAgGgGQgFgFgBgGQgNARgUAAQgLAAgGgGQgHgFAAgJQAAgJAEgKQAEgMAAgFQAAgHgGAAQgIAAgHAQQgDAHgEAMQgEAOAAAHQAAAGgGAAQgSABgEAAQgFAAAAgGQAAgBABgGgAk3gSQgLgEAAgGQAAgEACgDIACgDQAAgDgCAAQgDAAgEAEQgNAKAAAUQAAAHAFAGQAEAFAIAAQAHAAAFgHQAFgEAAgIQAAgIgFgCgAkfgXQAAAWgNAPQgOAQgXAAQgSAAgKgJQgKgKAAgOQAAgUAPgPQAPgQAaAAQAOAAAJAJQAJAIAAAOgADmgSQgKgEAAgGQAAgEACgDIACgDQAAgDgCAAQgDAAgFAEQgMAKAAAUQAAAHAEAGQAFAFAHAAQAIAAAFgHQAFgFAAgHQAAgHgGgDgAD/gXQAAAWgNAPQgPAQgXAAQgRAAgKgJQgKgKAAgOQAAgUAOgPQAQgQAZAAQAPAAAJAJQAJAIAAAOgAhogpQgKAAgGAPQgFANAAANQAAAMAJAAQAIAAAFgMQAHgNAAgVQAAgHgIAAgAguAAQABAAAAAAQAEAAAAADQAAADgEAGQgCACgCACQABgGACgKg");
	this.shape_22.setTransform(0.025,15.125);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AE3AuQAAgCABgCQAFgXAAgIQgCgFAAgDQAAgDAJgDQAJgDALAAQAJAAAAAGQAAAEgBAGQAHgPAPAAQAMAAAAALQAAAIgEAGQgFAHgIAAQgKAAAAgKQgEACgFAJQgEAHgDANQgEAOAAAHQAAAFgGAAQgSABgDAAQgGAAAAgFQAAgCABgFQABgGADgLQAAAAABAAQADAAAAAEQAAADgEAFQgCADgCACQgMAMgRAAQgKAAgGgGIgEgHQgOANgTAAQgMAAgIgHQgFgFgBgHQgKAJgHAEQgMAHgQAAQgTAAgLgJQgMgJAAgQQAAgVAOgOQAQgNAYAAQAbAAAAARQAAAQgPAAQgKAAAAgIQAAgDACgEQACgDAAgBQAAgEgFAAQgGAAgGAKQgHAKAAANQAAAKAHAGQAFAGAJAAQANAAAOgNQABgBAAAAQAAgVANgOQAOgQAaAAQAIAAAHADQAGACABAAQACAAAIgCQAJgDADAAQADAAAAAEQAAACgEAPQgFARAAAMQAAAKAJAAQAFAAAFgFQACgCACgBgAHMA0QAGgDAAAAQAEAAAAADQAAADgGAGQgPAPgVAAQgTAAgLgIQgMgKAAgSQAAgTAOgOQAPgNAZAAQAaAAAAASQAAALgMAJQgMAJgTACQAAAGAFAFQAGAFAHAAQAJAAAKgHgAG/AKQAAgGgGAAQgGAAgGAIQgGAJAAALQAKgCAIgIQAGgHAAgFgAgtAtQACgMAFgQQALgqAAgUQAAgNgKAAQgDAAAAgDQAAgEAIgFQAKgFAKAAQAKAAAFAFQAGAGAAAJQAAAQgOAwQANgPAUAAQAWAAAAARQAAAGgEAMQgEALAAAGQAAAKAGAAQACAAAFgDQADgCABAAQACAAAAADQAAADgDAEQgMAOgOAAQgMAAgGgFQgGgGAAgJQAAgHAEgNQAEgNAAgEQAAgGgGAAQgIAAgIAQQgDAGgEAQQgDAOAAAFQAAAFgGAAIgXABQgFAAAAgFQAAgDACgHQgFADgFAEQgMAIgLAAQgNAAgHgHQgEgDgBgEQgCgFAAgFQAAgBAAgCQADgCABAAQAEAAAAAEQAAADgEAFQgBABgBACQgNAOgSAAQgNAAgHgHQgDgDgBgEQgNAOgSAAQgKAAgGgGIgEgHQgOANgTAAQgMAAgHgHQgFgFgCgIQgTAVgbAAQgdAAgJgSQgNARgUAAQgXAAAAgUQAAgHAFgNQAEgNAAgEQAAgGgHAAQgHAAgJAQQgDAGgEAQQgEAOAAAFQAAAFgFAAIgXABQgFAAAAgFQAAgJAMgsQALgqAAgUQAAgNgKAAQgEAAAAgDQAAgEAJgFQAJgFALAAQAWAAAAAUQAAAQgPAwQAOgPATAAQAWAAAAARQAAAGgDAMQgEALAAAGQAAAIAIAAQAFAAAEgFQABgBAAAAQADgCABAAQAEAAAAAEQAAACgFAGQgCgEgBgGQAAgEAAgEQAAgTAOgOQAQgNAZAAQAZAAAAASQAAALgMAJQgMAJgTACQAAAHAFAEQAFAFAJAAQAMAAAQgNQABgBABAAQAAgVAMgOQAOgQAaAAQAIAAAHADQAGACABAAQACAAAIgCQAJgDADAAQAEAAAAAEQAAACgFAPQgFARAAAMQAAAKAJAAQAFAAAFgFIABAAQAAgMAJgcQAKggAAgWQAAgNgKAAQgDAAAAgDQAAgEAIgFQAKgFAKAAQAWAAAAAUQAAALgKAmQgKAlAAANQAAAKAIAAQAEAAAGgFQAAAAAAgBQABgIADgMQAEgOAAgGQAAgBgDgBQgEgBAAgDQAAgHAEAAQASAAAQgYQADgGAEAAQAEAAAAAEQAAAGgEAPQAAADACABQACABAFAAQAEAAAAADQAAADgCADQgCACgCAAQgJAAgCAIQgGAVAAAJQAAAKAKAAQAGAAAJgIQABgBABAAQACgBABAAQADAAAAADQAAACgCADQgDAEgEAEQABgGACgJgADHA4QgCgFAAgGIAAAAQADgDACAAQADAAAAAEQAAADgFAFQgBABAAABgAD9AFQgKAAgHAPQgFANAAANQAAAMAJAAQAIAAAGgMQAGgPAAgTQAAgHgHAAgAjZAFQgKAAgHAPQgFANAAANQAAAMAJAAQAIAAAGgMQAGgPAAgTQAAgHgHAAgAkpAKQAAgGgGAAQgGAAgGAIQgGAJAAALQAKgCAIgIQAGgHAAgFgAkPA3QgBgEAAgGQAAAAAAAAQADgDABAAQADAAAAAEQAAADgFAFQgBABAAAAgAiiAxQACgDACAAQADAAAAAEQAAADgEAFQgBACgBABQgCgEAAgGQAAgBABgBg");
	this.shape_23.setTransform(0.025,-10.325);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AAPguQAAAHADACQAFADAMAAQAEAAAAADQAAAJgGAAQgNAAgFAEQgGADgBAJQgKAygCAJQgEANgQAKQgOAJgJAAQgFAAAAgEQAAAAAEgGQAGgJADgMQAFgNAFgeQAFgZAAgEQAAgFgGAAQgEAAAAgDQAAgDACgCQACgDABAAQAGAAACgHQAKgrAmAAQAMAAAHAFQAHAFAAAHQAAAHgEADQgEAEgFAAQgIAAgCgIQgCgIgDAAQgEAAgDAJQgDAIAAAGg");
	this.shape_24.setTransform(41.85,-28.175);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AAsgLQAAAWgNAPQgOAQgWAAQgRAAgKgJQgLgJAAgQQAAgTAPgPQAPgPAZAAQAOAAAJAIQAJAJAAANgAAUgFQgKgFAAgGQAAgEACgDIABgDQAAgCgCAAQgDAAgEADQgMALAAASQAAAJAFAFQADAFAIAAQAHAAAGgGQAEgGAAgIQAAgGgFgCg");
	this.shape_25.setTransform(33.75,-27.675);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AgNAQQAAALAHAAQAGAAAAgHQAAgHgNgKQgNgJAAgKQAAgMALgHQAKgGAOAAQAcAAAAASQAAANgNAAQgEAAgCgCQgDgDAAgEQAAgCABgCQABgDAAgBQAAgDgFAAQgDAAgCACQgCADAAADQAAAIAOAJQAOAJAAAKQAAANgJAHQgKAIgQAAQgPAAgJgGQgKgGAAgKQAAgGAEgEQADgEAFAAQALAAAAAKg");
	this.shape_26.setTransform(20.525,-27.725);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AgGAiQAAAGgGAAIgWABQgFAAAAgGQAAgEAFgXQAGgXAAgHQAAgDgBgCQgBgCAAgCQAAgEAJgDQAIgCAMAAQAIAAAAAGQAAAFgCAGQAIgQAPAAQAMAAAAAMQAAAIgFAGQgEAHgIAAQgFAAgDgEQgCgCAAgEQgEABgGAKQgDAGgDANQgDANAAAHg");
	this.shape_27.setTransform(13.3,-27.675);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AAWApQgKAAgGgHIgEgHQgNAOgTAAQgMAAgIgHQgIgJAAgOQAAgVANgOQAOgQAaAAQAHAAAGACQAHADABAAQACAAAIgDQAIgCADAAQAEAAAAAEQAAABgEARQgFARAAAKQAAAFADADQACADAEAAQADAAAHgFQACgDACAAQAEAAAAAEQAAADgEAFQgOARgTAAgAgDgdQgKAAgGAQQgFAMAAANQAAAMAJAAQAIAAAFgMQAGgOAAgTQAAgIgHAAg");
	this.shape_28.setTransform(4.325,-27.675);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AAmALQAEgDABAAQAEAAAAADQAAADgGAGQgJAKgIAEQgMAIgQAAQgqAAAAgkQAAgTAPgNQAPgPAYAAQAaAAAAATQAAAMgMAIQgNAJgSABQAAAHAFAFQAFAEAJAAQAMAAAQgNgAAPgYQAAgGgGAAQgHAAgEAJQgHAIAAALQAKgBAHgIQAHgHAAgGg");
	this.shape_29.setTransform(-5.475,-27.675);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AgohEQAAgEAJgDQAIgCAMAAQAJAAAAAGQAAAFgFARQgFARAAAIQAAAIAHAAQAIAAAIgLQAHgLAAgVQAAgDgBgCQgBgCAAgCQAAgEAJgDQAJgCALAAQAJAAAAAGQAAADgCAKQgEAQgEAXQgIAsgIATQgPAigeAAQgPAAgKgIQgLgIAAgNQAAgOAJgJQAHgHAHAAQADAAAAADQAAABgBACQgCADAAADQAAAMAPAAQAVAAAIg1QgQAOgXAAQgJAAgHgEQgGgGAAgJQAAgJAFgQQAEgPAAgEQAAgDgBgCQgBgCAAgCg");
	this.shape_30.setTransform(-15.675,-24);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AA6gYQAAAlgUAfQgWAhgeAAQgTAAgMgMQgMgOAAgaQAAgqAWgdQAWgeAcAAQATAAAMAMQAMAOAAAagAgUArQAAAIADAFQAEAGAFAAQAOAAAJgnQAIgfAAgjQAAgUgKAAQgOAAgJAeQgKAeAAAug");
	this.shape_31.setTransform(-31.1,-31.15);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AAThGQAVAAAHgFQAEAAAAAEQAAAEgEAJQgGAMgGADQgEACgIAAQgJAAgSgFQgCANgFAMQADgBAHAAQASAAANALQANALAAASQAAAZgPAQQgPARgXAAQgTAAgLgOQgKgNAAgSQAAgHAEAAQADAAACAGQAFAQASAAQALAAAHgJQAFgIAAgMQAAgIgEgHQgFgIgLAAIgKABIgCAAQgEAAgCgDQgDgCAAgEQAAgBAFgQQAFgSACgMQAAgFAEgEQAEgEAFAAQACAAAIACQAIACAMAAg");
	this.shape_32.setTransform(-41.975,-31.125);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AADgOQAKAAAAALQAAAGgEAGQgGAGgGAAQgEAAgDgEQgCgDAAgFQAAgFAFgGQAFgGAFAAg");
	this.shape_33.setTransform(49.925,37.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AAHgFQgGAUAAAIQAAAKAKAAQAFAAAJgIQADgDACAAQADAAAAADQAAADgCACQgGAIgKAHQgMAIgKAAQgNAAgGgHQgGgGAAgLQAAgIAEgOQADgMAAgGQAAgBgDgBQgDgBAAgDQAAgHAEAAQARAAAOgXQAEgGADAAQAEAAAAAEQAAAGgEAOQAAAFAJAAQADAAAAADQAAAIgFAAQgJAAgCAIg");
	this.shape_34.setTransform(44.95,33.45);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AADg+QAOAAAAANQAAAHgGAHQgGAHgGAAQgFAAgFgEQgEgEAAgGQAAgHAGgHQAGgGAGAAgAgdAqQAAgJAEgOQAEgOAAgEQgCgEAAgDQAAgEAJgDQAIgCAKAAQAJAAAAAGQAAAEgEAOQgEAPAAAJQAAAKAIAAQAEAAAFgFQADgDACAAQADAAAAAEQAAACgEAGQgOAQgRAAQgMAAgGgGQgGgGAAgJg");
	this.shape_35.setTransform(39.375,32.475);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AgMAPQAAAKAHAAQAFAAAAgGQAAgHgMgJQgNgJAAgKQAAgLALgHQAJgGAOAAQAaAAAAARQAAANgLAAQgEAAgDgCQgCgDAAgDQACgGAAgCQAAgDgFAAQgDAAgCACQgCADAAADQAAAHAOAJQANAIAAAKQAAAMgJAIQgJAHgQAAQgOAAgJgGQgJgGAAgKQAAgFADgEQAEgDAEAAQALAAAAAJg");
	this.shape_36.setTransform(27.825,34.8);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AAxAwQACgDACAAQAEAAAAAEQAAACgEAGQgOAQgSAAQgKAAgFgGIgEgGQgMAMgSAAQgbAAAAgdQAAgVANgPQANgNAVAAQAKAAAHAEQAIgfAAgLQAAgMgKAAQgEAAAAgDQAAgEAJgFQAJgFAKAAQAVAAAAAUQAAAKgLAjQgKAiAAAQQAAAKAIAAQAFAAAFgFgAgDAFQgJAAgGAQQgFAMAAAOQAAAKAIAAQAIAAAFgMQACgFACgKQACgLAAgHQAAgHgHAAg");
	this.shape_37.setTransform(19.65,31.5);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AAOgXQAAgFgGAAQgGAAgEAIQgGAIAAALQAJgCAHgIQAGgGAAgGgAAlALQAEgDABAAQADAAAAADQAAADgFAFQgTAVgZAAQgoAAAAgiQAAgSAOgNQAPgOAXAAQAZAAAAASQAAALgMAJQgMAIgRABQAAAHAFAEQAEAFAJAAQALAAAQgNg");
	this.shape_38.setTransform(10.225,34.825);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AAOgXQAAgFgGAAQgGAAgEAIQgGAIAAALQAJgCAHgIQAGgGAAgGgAAlALQAEgDABAAQADAAAAADQAAADgFAFQgTAVgZAAQgoAAAAgiQAAgSAOgNQAPgOAXAAQAZAAAAASQAAALgMAJQgMAIgRABQAAAHAFAEQAEAFAJAAQALAAAQgNg");
	this.shape_39.setTransform(1.975,34.825);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AgBAUQAAgIAEgLQADgKAAgFQAAgHgFAAQgHAAgIAQQgEAGgDAMQgEANAAAHQAAAFgFAAIgVACQgGAAAAgGQAAgEAGgWQAFgWAAgHQgCgFAAgDQAAgEAJgDQAIgDALAAQAJAAAAAHQAAAEgCAHQAFgGAIgFQAKgHAKAAQATAAAAAQQAAAGgEAMQgDAKAAAFQAAAJAIAAQAEAAAFgFQADgCACAAQAEAAAAADQAAADgFAFQgOARgSAAQgKAAgGgGQgGgFAAgJg");
	this.shape_40.setTransform(-7.5,34.825);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AArgKQAAAVgNAOQgOAQgVAAQgRAAgKgJQgKgJAAgPQAAgSAOgOQAQgQAXAAQAOAAAJAIQAJAJAAANgAATgFQgKgEAAgGQAAgEACgDIACgDQAAgCgDAAQgBAAgFADQgMAKAAASQAAAIAEAFQAEAFAIAAQAHAAAFgGQAEgGAAgHQAAgGgFgCg");
	this.shape_41.setTransform(-22.2,34.825);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AAAA2QAAgHADgNQAEgMAAgEQAAgGgGAAQgHAAgHAPQgEAGgEAPQgDAOAAAFQAAAFgGAAIgVABQgFAAAAgFQAAgJALgqQALgpAAgTQAAgMgJAAQgEAAAAgDQAAgEAJgFQAIgFAKAAQAVAAAAAUQAAARgOAsQAOgOARAAQAVAAAAAQQAAAGgDALQgEALAAAFQAAAJAIAAQADAAAGgFQACgDACAAQAEAAAAAEQAAACgEAGQgMAQgUAAQgVAAAAgTg");
	this.shape_42.setTransform(-31.4,31.5);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f().s("#FFEA7D").ss(8,0,0,1).p("AAogYQAAgHAEgEQAFgEAGAAQAQAAAAATQAAAUgOASQgPAWgXAAQgTAAgJgRQgPARgXAAQgKAAgHgGQgGgGAAgIQAAgJAFgNQAEgOAAgFQgCgFAAgDQAAgEAJgDQAIgDALAAQAIAAAAAHQAAAFgEAPQgEAPAAAIQAAAKAHAAQAJAAAGgMQAHgMAAgSQgCgFAAgDQAAgEAIgDQAIgDALAAQAIAAAAAHQAAAFgEAQQgEAOAAAIQAAAKAJAAQAIAAAGgKQAGgJAAgJQAAgEgEgEQgEgFAAgEg");
	this.shape_43.setTransform(-44.125,34.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-56.2,-42.8,111.5,85.69999999999999);


(lib.HEAD1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgUAWQgGgGAAgKQAAgLAKgLQALgMAMAAQAJAAAFAHQAGAGAAAJQAAAMgKALQgKAMgOAAQgIAAgFgHg");
	this.shape.setTransform(128.125,14.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgqB0QgMgLAAgSQAAgQARg4QARg2AAglQAAgWgPAAQgHAAAAgFQABgIAQgIQARgIAQAAQASAAALAJQALAJAAAQQAAASgSBCQgRBBgBAVQABAQALAAQAIAAAJgKQAEgEAEAAQAGAAAAAGQAAAFgHAJQgXAdgfAAQgWAAgOgMg");
	this.shape_1.setTransform(119.45,4.225);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgpB0QgNgLAAgSQAAgQARg4QARg2AAglQAAgWgQAAQgFAAAAgFQgBgIARgIQARgIAQAAQASAAALAJQALAJAAAQQAAASgRBCQgSBBAAAVQgBAQAMAAQAIAAAJgKQAEgEAEAAQAGAAAAAGQAAAFgHAJQgXAdgfAAQgWAAgNgMg");
	this.shape_2.setTransform(109.8,4.225);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AABAvQgQAXgkAAQgVAAgPgNQgPgOAAgYQAAgkAVgYQAYgcAsAAQANAAAMAFIAOAEQAFAAAPgEQAQgFAEAAQAHAAAAAHIgIAfQgHAcgBATQAAASAPAAQAIAAAJgJQAEgEAEAAQAGAAAAAGQAAAFgHAJQgXAdgjAAQgZAAgMgXgAgagVQgKAVAAAXQAAAQAKAAQAMAAAIgcQAHgYAAgXQABgIgIAAQgKAAgKAXg");
	this.shape_3.setTransform(95.35,10.075);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhIA8QAAgHAJgoQAJgmAAgNQAAgIgDgGQAAgHASgFQARgFAVAAQAOAAAAAMIgBAKQARgUAWAAQAWAAAAAVQAAANgHAKQgIALgNAAQgKAAgGgHQgFgGAAgGQgHACgHAOQgHALgGAYQgHAaAAANQAAAJgKAAIgrACQgJAAAAgKg");
	this.shape_4.setTransform(70.075,10.075);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ag5A4QgTgQAAgaQAAghAZgZQAcgbAqABQAbAAAQAPQAPAOAAAYQAAAmgVAZQgXAagpAAQgeAAgTgQgAAEgoQgOAOAAAgQAAAgAWAAQALAAAIgKQAHgKAAgMQAAgMgIgEQgRgHAAgJQAAgLAHgHQAAgBAAgBQgBAAAAgBQAAAAgBAAQAAgBgBAAQgFAAgIAIg");
	this.shape_5.setTransform(54.625,10.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhaCKQAAgDAGgIQAKgPAGgTQAGgYAJgyIAJgyQgBgIgIAAQgIAAABgGQgBgFAEgEQADgEADAAQALAAACgMQAShJBEAAQAUAAAMAJQALAIAAANQAAAXgXAAQgNAAgDgNQgEgOgDAAQgHAAgHAPQgFANAAAKQAAAMAEAEQAGAFAVAAQAHAAAAAFQAAAPgLAAQgVgBgIAIQgHAFgCAPQgKA7gJAqQgEAVggASQgaAOgQAAQgIAAAAgFg");
	this.shape_6.setTransform(43.3,9.25);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag8A4QgVgQAAgeQAAggAZgXQAbgZAqAAQAVAAANAKQAMAJAAAPQAAAVgTAPQgUAOgdAAQAAAKAJAHQALAGAPAAQATAAAWgTQAGgFADAAQAGAAAAAGQAAAFgJAKQglAlgsAAQggAAgUgPgAgDgiQgIAOAAAOQAOgDAJgLQAIgKAAgJQAAgIgIAAQgJAAgGANg");
	this.shape_7.setTransform(22.725,10.125);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AhIA8QAAgHAJgoQAJgmAAgNQAAgIgDgGQAAgHASgFQARgFAVAAQAOAAAAAMIgBAKQARgUAWAAQAWAAAAAVQAAANgHAKQgIALgNAAQgKAAgGgHQgFgGAAgGQgHACgHAOQgHALgGAYQgHAaAAANQAAAJgKAAIgrACQgJAAAAgKg");
	this.shape_8.setTransform(7.375,10.075);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AACAvQgSAXgiAAQgWAAgOgNQgQgOAAgYQAAgkAVgYQAYgcAsAAQANAAAMAFIANAEQAGAAAPgEQAPgFAGAAQAGAAAAAHIgHAfQgJAcABATQgBASAPAAQAIAAAJgJQAEgEADAAQAHAAAAAGQAAAFgHAJQgXAdgjAAQgaAAgKgXgAgbgVQgJAVAAAXQAAAQAKAAQALAAAJgcQAIgYAAgXQgBgIgGAAQgLAAgLAXg");
	this.shape_9.setTransform(-8.65,10.075);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag8A4QgVgPAAgdQAAgiAZgXQAbgZApAAQAYAAANAJQALAJAAANQAAAOgIAJQgIAJgMAAQgTAAABgQQAAgFACgFIAEgHQAAgGgGAAQgJAAgHAMQgIAPgBAUQAAAQAKAJQAKAJAQAAQASAAAZgRQAGgFADAAQAFAAAAAFQAAAGgKAKQgkAlgtAAQggAAgTgPg");
	this.shape_10.setTransform(-25.85,10.125);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAJB3QgMgJAAgPQAAgNAGgWQAHgVAAgIQAAgIgJAAQgKAAgNAZQgFAKgHAaQgFAYAAAJQAAAJgKAAIgtACQgJAAAAgJQABgQAThJQAThJAAghQAAgWgPAAQgGAAAAgFQAAgIAQgIQARgIARAAQASAAALAJQALAJgBAQQABAdgYBOQAUgYAjAAQAnAAAAAdQAAALgGAUQgHAUAAALQAAAMALAAQAIAAAJgKQAFgEADAAQAFAAAAAGQABAFgHAJQgXAdghAAQgVAAgLgJg");
	this.shape_11.setTransform(-50.9,4.225);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgyBSQgLgMAAgSQABgPAGgYQAHgWAAgKQAAgCgGgCQgGgCAAgEQAAgNAHAAQAgAAAcgqQAIgJAGAAQAIAAgBAIQgFAbAAAHQAAAJANAAQAGAAAAAFQAAAPgKAAQgOAAgDAOQgKAgAAAQQAAARASABQAIAAAOgMQAIgGACAAQAFAAABAGQAAADgGAHQgKAOgTALQgWANgVAAQgWAAgMgMg");
	this.shape_12.setTransform(-65.65,7.65);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgpB0QgNgLAAgSQAAgQARg4QARg2AAglQAAgWgPAAQgHAAABgFQgBgIARgIQARgIAQAAQASAAALAJQALAJAAAQQAAASgSBCQgRBBgBAVQAAAQAMAAQAIAAAJgKQAFgEADAAQAGAAAAAGQAAAFgHAJQgXAdgfAAQgWAAgNgMg");
	this.shape_13.setTransform(-75.95,4.225);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AABAvQgQAXgkAAQgVAAgPgNQgPgOAAgYQAAgkAVgYQAYgcAsAAQANAAAMAFIAOAEQAFAAAPgEQAQgFAEAAQAHAAAAAHIgIAfQgHAcgBATQAAASAPAAQAIAAAJgJQAFgEADAAQAGAAAAAGQAAAFgHAJQgXAdgjAAQgZAAgMgXgAgbgVQgJAVAAAXQAAAQAKAAQALAAAJgcQAHgYAAgXQABgIgIAAQgKAAgLAXg");
	this.shape_14.setTransform(-90.4,10.075);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Ag8A4QgVgQAAgeQAAggAZgXQAbgZAqAAQAVAAANAKQAMAJAAAPQAAAVgTAPQgUAOgdAAQAAAKAJAHQALAGAPAAQATAAAWgTQAGgFADAAQAGAAAAAGQAAAFgJAKQglAlgsAAQggAAgUgPgAgDgiQgIAOAAAOQAOgDAJgLQAIgKAAgJQAAgIgIAAQgJAAgGANg");
	this.shape_15.setTransform(-107.625,10.125);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAIB3QgLgJAAgPQAAgNAGgWQAHgVAAgIQAAgIgJAAQgKAAgMAZQgGAKgHAaQgFAYAAAJQAAAJgJAAIguACQgIAAAAgJQAAgQAThJQAThJAAghQAAgWgPAAQgGAAAAgFQAAgIAQgIQARgIARAAQATAAAKAJQALAJAAAQQAAAdgZBOQAVgYAiAAQAoAAAAAdQAAALgGAUQgHAUAAALQAAAMALAAQAIAAAJgKQAEgEADAAQAHAAAAAGQgBAFgGAJQgXAdghAAQgUAAgNgJg");
	this.shape_16.setTransform(-124.85,4.225);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AhIA8QAAgHAJgoQAJgmAAgNQAAgIgDgGQAAgHASgFQARgFAVAAQAOAAAAAMIgBAKQARgUAWAAQAWAAAAAVQAAANgHAKQgIALgNAAQgKAAgGgHQgFgGAAgGQgHACgHAOQgHALgGAYQgHAaAAANQAAAJgKAAIgrACQgJAAAAgKg");
	this.shape_17.setTransform(102.675,-20.375);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag5A4QgTgQAAgaQAAghAZgZQAcgbAqAAQAbABAQAPQAPAOAAAYQAAAngVAXQgXAagpAAQgeAAgTgPgAAEgoQgOAOAAAgQAAAgAWAAQALAAAIgKQAHgKAAgMQAAgMgIgEQgRgHAAgKQAAgJAHgJQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAgBgBAAQgFABgIAHg");
	this.shape_18.setTransform(87.225,-20.35);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AhaCJQAAgCAGgIQAKgPAGgUQAHgXAIgyIAJgyQgBgIgIAAQgIAAAAgGQABgEADgFQADgEADAAQAKAAADgMQARhIBEgBQAVABAMAIQALAIAAAMQAAAYgXAAQgNAAgDgOQgDgNgEAAQgIAAgGAPQgFANAAAKQAAANAEADQAHAFAUAAQAGAAABAFQAAAPgLAAQgVAAgIAGQgGAFgDAQQgKA7gJAqQgFAVgfASQgaAPgPAAQgJAAAAgHg");
	this.shape_19.setTransform(75.9,-21.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgyBSQgLgLAAgTQAAgPAHgXQAHgXAAgKQAAgCgGgDQgGgBAAgEQAAgNAHAAQAgAAAcgpQAIgKAGAAQAIAAAAAIQgHAaABAIQAAAJANAAQAGAAAAAFQAAAPgKAAQgOAAgDAOQgKAgAAARQAAARASAAQAIAAAOgMQAIgGACAAQAFAAAAAFQAAAEgEAHQgMAOgSALQgWANgVAAQgWAAgMgMg");
	this.shape_20.setTransform(57.4,-22.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAJB3QgMgJAAgPQAAgNAGgWQAHgVAAgIQAAgIgJAAQgKAAgNAZQgFAKgHAaQgFAYAAAJQAAAJgKAAIgtACQgJAAAAgJQABgQAThJQAThJAAghQAAgWgPAAQgGAAAAgFQAAgIAQgIQARgIASAAQARAAALAJQALAJgBAQQABAdgYBOQAUgYAjAAQAnAAAAAdQAAALgGAUQgHAUAAALQAAAMALAAQAIAAAJgKQAFgEADAAQAFAAAAAGQABAFgHAJQgXAdghAAQgVAAgLgJg");
	this.shape_21.setTransform(42.25,-26.225);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AhLB3QgSgPgBgWQAAgYARgPQAMgMAOAAQAEAAAAAEIgCAGQgCAFABAFQgBAUAWAAQAgAAAOhRQgRAQgdAAQgWAAgPgNQgOgOAAgXQgBgkAWgYQAagcArAAQANAAANAEIAMAEQAFAAAOgEQAPgEAGAAQAGAAAAAHIgEAVQgHAbgIAsQgMBLgPAhQgaA6g1AAQgZAAgTgOgAgFhVQgJAXAAAWQAAARAKAAQAKAAAJgcQAJgZgBgXQAAgJgIAAQgKAAgKAXg");
	this.shape_22.setTransform(23.15,-14.025);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgCAuQgUAYgqAAQgQAAgLgJQgKgKAAgPQABgPAHgaQAIgbAAgGQAAgIgEgGQAAgHASgFQASgFAUAAQAPAAAAAMQAAAIgIAbQgIAaAAASQAAALALAAQAHAAAIgQQAPgbAAgcQAAgIgDgGQAAgHATgFQAQgFAVAAQAPAAAAAMQAAAHgIAcQgHAbgBAOQAAAPAMAAQAIAAAJgJQAFgEACAAQAGAAABAGQgBAFgGAJQgXAdggAAQgjAAgHgYg");
	this.shape_23.setTransform(6.2,-20.375);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("Ag5A4QgTgQAAgaQAAghAZgZQAcgbAqAAQAbABAQAPQAPAOAAAYQAAAngVAXQgXAagpAAQgeAAgTgPgAAEgoQgOAOAAAgQAAAgAWAAQALAAAIgKQAHgKAAgMQAAgMgIgEQgRgHAAgKQAAgJAHgJQAAAAAAgBQgBAAAAgBQAAAAgBAAQAAgBgBAAQgFABgIAHg");
	this.shape_24.setTransform(-12.325,-20.35);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AhaCJQAAgCAGgIQALgPAFgUQAHgXAIgyIAJgyQgBgIgIAAQgIAAABgGQAAgEADgFQADgEADAAQALAAACgMQARhIBEgBQAVABAMAIQALAIAAAMQAAAYgXAAQgNAAgDgOQgEgNgDAAQgHAAgHAPQgFANAAAKQAAANAEADQAHAFAUAAQAGAAABAFQAAAPgLAAQgVAAgIAGQgHAFgCAQQgKA7gJAqQgEAVggASQgaAPgPAAQgJAAAAgHg");
	this.shape_25.setTransform(-23.65,-21.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("Ag8A4QgVgQAAgeQAAggAZgXQAbgZAqAAQAVAAANAKQAMAJAAAPQAAAVgTAPQgUAOgdAAQAAAKAJAHQALAGAPAAQATAAAWgTQAGgFADAAQAGAAAAAGQAAAFgJAKQglAlgsAAQggAAgUgPgAgDgiQgIAOAAAOQAOgDAJgLQAIgKAAgJQAAgIgIAAQgJAAgGANg");
	this.shape_26.setTransform(-44.225,-20.325);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AhPAkQAAgQAHgaQAHgaAAgGQAAgIgCgGQAAgHASgFQAQgFAVAAQAOAAAAAMQAAAJgHAcQgIAcAAAOQAAALAKAAQAKAAANgRQAMgQAAgRQAAgDgFgHQgGgIAAgIQAAgMAJgHQAIgHAMAAQAeAAAAAeQAAAkgnAjQgoAmgqAAQgmAAAAgig");
	this.shape_27.setTransform(-60.925,-20.375);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgdAnQAAgDAHgLQAHgLAAgNQAAgDgDgHQgDgHAAgFQAAgKAHgHQAIgHAKAAQAaAAAAAaQAAAUgXAYQgTAVgKAAQgHAAAAgHg");
	this.shape_28.setTransform(-66.475,-35.475);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("Ag8A4QgVgQAAgeQAAggAZgXQAbgZAqAAQAVAAANAKQAMAJAAAPQAAAVgTAPQgUAOgdAAQAAAKAJAHQALAGAPAAQATAAAWgTQAGgFADAAQAGAAAAAGQAAAFgJAKQglAlgsAAQggAAgUgPgAgDgiQgIAOAAAOQAOgDAJgLQAIgKAAgJQAAgIgIAAQgJAAgGANg");
	this.shape_29.setTransform(-77.225,-20.325);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAAA9QgNgIgGgLQgcAcgkAAQgTAAgMgKQgLgKAAgPQAAgQAHgYQAHgZAAgIQAAgIgCgGQAAgHASgFQAQgFAVAAQAPAAAAAMQAAAIgIAbQgHAZAAAQQAAAOALAAQALAAAIgRQANgXAAgfQAAgIgDgGQAAgHASgFQAQgFAUAAQAPAAAAAMQAAAJgHAaQgHAaAAAPQAAAOAOAAQAKAAAJgPQAJgPAAgRQAAgGgGgHQgHgIAAgIQAAgLAIgIQAJgHALAAQAOAAAJAJQAJAJAAAPQAAAkgYAgQgcAmgnAAQgUAAgPgJg");
	this.shape_30.setTransform(-98.475,-20.375);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgdAnQgBgDAIgLQAGgLAAgNQABgDgDgHQgCgHAAgFQAAgKAGgHQAIgHAKAAQAaAAAAAaQABAUgXAYQgUAVgKAAQgIAAABgHg");
	this.shape_31.setTransform(72.5,-44.325);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("Ag4B3QAAgmAkiJQgOAFgIAAQgDAAgDgDIgCgGQAAgHAHgFIAygoQAHgGAKgFIANgEQAIAAAGAEQAGAFAAAHQAAAFgFAOIgKAmQgiCCAAApQAAAJgJAAIgvACQgIAAAAgJg");
	this.shape_32.setTransform(65.35,-56.675);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AhTB4QAAghAeg9QAfg/AjggQgMgFgbAAQgkAAgMAHQgGAAAAgGQAAgGAIgSQAKgVALgGQAHgDANAAQASAAAzAFQANAAANgEQAGAAAHALQAHAMAAAHQAAAEgHAGIgRAPQgcAggWA8QgTA4AAAiQAAALgKAAQguAGgLAAQgHAAAAgIg");
	this.shape_33.setTransform(52.825,-56.65);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AhJBrQgQgSAAgRQAAgKAIAAQACAAAJAIQALAJATAAQAYAAASgVQARgUAAgWQgOASgiABQgcAAgQgSQgRgRAAgcQAAgnAagdQAcggAuAAQAkAAAVATQAZAWgBAtQAABRgiAvQggArgzAAQgdAAgSgWgAgRhNQgJAWAAAcQAAAaARABQALAAAJgWQAJgUAAgbQAAgfgPAAQgNAAgJAXg");
	this.shape_34.setTransform(34.25,-56.75);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("Ag4B3QAAgmAkiJQgOAFgIAAQgDAAgDgDIgCgGQAAgHAHgFIAygoQAHgGAKgFIANgEQAIAAAGAEQAGAFAAAHQAAAFgFAOIgKAmQgiCCAAApQAAAJgJAAIgvACQgIAAAAgJg");
	this.shape_35.setTransform(18.9,-56.675);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("Ag8A4QgVgQAAgeQAAggAZgXQAbgZAqAAQAVAAANAKQAMAJAAAPQAAAVgTAPQgUAOgdAAQAAAKAJAHQALAGAPAAQATAAAWgTQAGgFADAAQAGAAAAAGQAAAFgJAKQglAlgsAAQggAAgUgPgAgDgiQgIAOAAAOQAOgDAJgLQAIgKAAgJQAAgIgIAAQgJAAgGANg");
	this.shape_36.setTransform(-2.425,-50.775);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("Ag8A4QgVgPAAgdQAAgiAZgXQAbgZApAAQAYAAANAJQALAJAAANQAAAOgIAJQgJAJgMAAQgRAAgBgQQAAgFADgFIAEgHQAAgGgHAAQgIAAgHAMQgJAPAAAUQABAQAJAJQAKAJAQAAQATAAAXgRQAHgFADAAQAFAAAAAFQAAAGgJAKQglAlgtAAQgfAAgUgPg");
	this.shape_37.setTransform(-17.55,-50.775);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAIA8QgLgKAAgOQAAgPAGgUQAHgTAAgIQAAgJgIAAQgKAAgNAZQgGALgGAWQgHAXAAANQAAAJgJAAIgsACQgJAAAAgKQAAgHAJgoQAJgmAAgNQAAgIgDgGQAAgHASgFQARgFAUAAQAPAAAAAMQAAAHgDAKQAIgKAOgIQASgLARAAQAkAAAAAcQAAAKgGAWQgGAVAAAJQAAANAMAAQAHAAAKgJQAEgEADAAQAGAAAAAGQAAAFgHAJQgWAdgiAAQgSAAgOgKg");
	this.shape_38.setTransform(-34.725,-50.825);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgpBlQgNgLAAgPQAAgQAHgZQAHgZAAgHQAAgGgCgHQAAgHASgFQAQgEAUAAQAPAAAAALQAAAHgHAaQgHAaAAASQAAAHAEAEQAEAEAFAAQAHAAAJgKQAEgEADAAQAGAAAAAGQAAAFgGAJQgXAdggAAQgWAAgNgKgAgVg5QgHgHAAgKQAAgOAJgLQAKgLAOAAQAMAAAJAGQAIAHAAAKQAAAQgLALQgKAKgNAAQgNAAgIgHg");
	this.shape_39.setTransform(-49.025,-54.975);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AhTCEQgagTAAggQAAgcAbgRQAXgOAbAAQATAAAAAHQAAAGgIAFQgYARAAAbQAAAPAJAIQAJAJAOgBQAPAAAKgNQAJgOAAgXQAAgigcgoQgPgVgEgJQgJgSAAgRQAAgiAegVQAZgTAgAAQAbAAAPAMQAQANAAAXQAAAQgJALQgJALgNAAQgKABgGgGQgHgGAAgJQAAgIAHgJQAIgJAAgGQAAgKgNAAQgJAAgIAJQgHAJAAAPQAAAQAJASQAFAJARAVQAfAoAAAhQAAAsgjAeQgjAdgvAAQglAAgZgRg");
	this.shape_40.setTransform(-65.425,-58.35);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD1, new cjs.Rectangle(-150,-94.4,300,173.3), null);


(lib.HEAD_NotDoneai = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// HEAD_NotDone.ai
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#70202C").s().p("AJZCFQgMgJAAgPQAAgQAKgKQAIgIAIAAQAAAAABAAQABABAAAAQAAAAABABQAAAAAAABIgBAEIgCAHQAAAOARAAQAPAAAJgVQAGgOAEgcQgSASgbAAQgLAAgIgHQgHgGAAgKQAAgLAFgSQAFgRAAgEIgBgGIgBgEQAAgFAKgDQAKgDANAAQAKAAAAAIQAAAGgFATQgFASAAAKQAAAJAIAAQAKAAAJgNQAIgMAAgYIgBgGIgBgEQAAgFAKgDQAKgDANAAQALAAAAAIIgDAOIgJAtQgJAzgKAWQgRAmgkAAQgRAAgLgJgArtAxQgKgKgCgQQgcAkgiAAQgQAAgJgKQgJgJAAgQQAAgUARgrQARgtAAgcQAAgMgNAAQgRAAgPATQgOASAAASQAAAPAMAAQAEAAAGgDQAAAAABAAQAAABABAAQAAABAAAAQAAABAAABQAAAIgKAKQgNAMgPAAQgNAAgJgJQgJgKAAgPQAAgkAggZQAdgXAlAAQAVAAANAKQANALAAATQAAAXgMAlQgNAlAAAMQAAAGAEAEQADADAEAAQARAAAQgZQAIgMAHgYQAGgVAAgJIgBgKQAAgGAPgHQAMgFAGAAQALAAAAALQAAAKgKAlQgLAkAAAKQAAAPAMAAQAUAAAUgqQAMgdAAgkQAAgcgTAAQgFAAAAgFQAAgGAJgIQALgIANAAQAdAAAAAfQAAAmgeA9QgPAegTATQgWAVgUAAQgPAAgKgKgALYAxQgOgLAAgVQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAKAAQAKAAAKgGIANgKIABgBQABgIAEgLQAEgPAAgHQAAgBAAAAQAAAAgBgBQAAAAgBAAQgBAAgBgBQgEgBAAgDIABgFQACgEACAAQALAAALgJQAKgIAGgLQAFgGADAAQAFAAAAAFQAAAGgEARQAAABAAABQAAABABAAQAAABAAAAQAAABABAAQACABAGAAQAEAAAAAEQAAAKgHAAQgKAAgCAJQgHAXAAAKQAAANAMAAQAEAAAFgEIAIgGIAFgDQAEAAAAAEQAAACgCAEQgIAJgLAIQgPAKgMAAQgQAAgIgJQgFgFgCgIQgWAXgdAAQgWAAgMgKgAL8gOQgHAKAAAMQALgDAJgIQAIgIAAgGQAAgHgHAAQgHAAgHAKgAHBAxQgGgFgDgHIgBABQgQAUgWAAQgNAAgHgHQgIgGAAgKQAAgKAFgNQAFgNAAgFQAAgJgHAAQgJAAgKASQgEAIgEAPQgFAQAAAIQAAAGgGAAIgaACQgGAAAAgHQAAgFAHgbQAGgaAAgIIgBgGIgBgEQAAgFAKgDQAKgDANAAQAKAAAAAIQAAAFgCAIQAGgHAKgGQANgIAMAAQAXAAAAATQAAAHgEANQgFAOAAAGQAAALAKAAQAFAAAGgHIACgBIgBgJQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAJAAQAMAAAKgIIAHgEQAEAAAAAEQAAADgHAHQgRASgYAAQgWAAgNgKgAHlgOQgHAKAAAMQALgDAJgIQAIgIAAgGQAAgHgHAAQgHAAgHAKgADWAwQgFgEgDgGQgPAUgXAAQgLAAgHgIIgFgHQgQAPgWAAQggAAAAgjQAAgZAQgRQAQgRAZAAQAPAAAHAFQAIghAAgRQAAgPgLAAQgEAAAAgDQAAgFAKgGQAKgGANAAQALAAAHAGQAHAHAAALQAAAMgNApQgMApAAATQAAAGADAEQADADAEAAQAGAAAFgHIABgBIAAgGQAAgWAQgRQATgSAdAAQAQAAALAKQAKAJAAAQQAAAZgPARQgQATgbAAQgUAAgLgLgAB4gEQgGAOAAAQQAAAMAKAAQAKAAAFgOQADgGADgMQADgMAAgIQAAgJgKAAQgLAAgHATgAEAgSQgOALAAAWQAAAKAFAGQAGAGAIAAQAJAAAGgHQAFgHAAgJQAAgIgGgDQgMgEAAgHQAAgFADgDIACgEQAAAAAAgBQgBAAAAgBQAAAAgBAAQgBAAAAAAQgDAAgGAEgAiOAwQgFgEgDgGQgOAUgYAAQgMAAgIgHQgHgGAAgKQAAgKAFgNQAFgNAAgFQAAgJgHAAQgKAAgJASQgEAIgFAPQgEAQAAAIQAAAGgHAAIgZACQgGAAAAgHQAAgFAGgbQAGgaAAgIIgBgGIgBgEQAAgFALgDQAJgDAOAAQAKAAAAAIQAAAFgCAIQAGgHAKgGQANgIALAAQAXAAAAATQAAAHgEANQgEAOAAAGQAAALAKAAQAFAAAGgHIABAAIgBgHQAAgWARgRQASgSAdAAQARAAAKAKQALAJAAAQQAAAZgQARQgQATgaAAQgUAAgMgLgAhjgSQgPAMAAAVQAAAKAGAGQAFAGAJAAQAIAAAGgHQAGgHAAgJQAAgIgGgDQgMgEAAgHQAAgFACgDIACgEQAAAAAAgBQAAAAgBgBQAAAAAAAAQgBAAgBAAQgCAAgGAEgAmnAxQgOgLAAgVQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAJAAQALAAALgIIAHgEQAEAAAAAEQAAAEgHAGQgRASgYAAQgWAAgNgKgAmDgOQgHAKAAAMQALgDAJgIQAIgIAAgGQAAgHgHAAQgHAAgHAKgApzAxQgOgLAAgVQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAJAAQAMAAAKgIIAHgEQAEAAAAAEQAAADgGAHQgTASgXAAQgWAAgNgKgApPgOQgHAKAAAMQALgDAJgIQAIgIAAgGQAAgHgHAAQgHAAgHAKgAODA2QgDgEAAgGQAAgIAGgGQAGgIAIAAQAFAAADAEQAEAEAAAGQAAAIgGAHQgGAHgJAAQgFAAgDgEgAgoAxQgIgHAAgNQAAgKAFgQQAFgPAAgHQAAgBgBAAQAAAAAAgBQgBAAgBAAQAAAAgBgBQgFgBAAgDIACgFQABgEADAAQAKAAAMgJQAJgIAHgLQADgGAEAAQAFAAAAAFQAAAGgEARQAAABAAABQAAABAAAAQAAABABAAQAAABAAAAQACABAHAAQAEAAAAAEQAAAKgHAAQgKAAgCAJQgGAXAAAKQAAANALAAQAEAAAMgKIAGgDQAEAAAAAEQAAACgDAEQgHAJgMAIQgNAKgNAAQgPAAgIgJgAoRAzQAAgFAHgbQAGgaAAgIIgBgGIgBgEQAAgFAKgDQAKgDANAAQALAAAAAIIgCALQAKgSAQAAQAOAAAAAOQAAAJgFAHQgGAHgJAAQgGAAgDgDQgDgDAAgFQgFADgFAJQgFAIgEAPQgEAQAAAIQAAAGgGAAIgZACQgHAAAAgHgAoVhBIAFgKQAFgJAAgIIgBgHQgCgEAAgDQAAgHAEgEQAEgFAIAAQAPAAAAAQQAAAPgOAQQgNAOgGAAQgFAAAAgEg");
	this.shape.setTransform(97.375,18.825);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FFEA7D").ss(9.2,0,0,1).p("AMtAWQABgIAEgLQAEgPAAgHQAAgCgEgBQgEgBAAgDQAAgCABgDQACgEACAAQALAAALgJQAKgIAGgLQAFgGADAAQAFAAAAAFQAAAGgEARQAAAEACABQACABAGAAQAEAAAAAEQAAAKgHAAQgKAAgCAJQgHAXAAAKQAAANAMAAQAEAAAFgEQADgCAFgEQAEgDABAAQAEAAAAAEQAAACgCAEQgIAJgLAIQgPAKgMAAQgQAAgIgJQgFgFgCgIQgWAXgdAAQgWAAgMgKQgOgLAAgVQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAKAAQAKAAAKgGQADgCAKgIQABgBAAAAQADgCACAAQADAAAAADQAAAEgGAHQgBABgBABQAAgDAAgEQAAgDAAgEgAOUAWQAFAAADAEQAEAEAAAGQAAAIgGAHQgGAHgJAAQgFAAgDgEQgDgEAAgGQAAgIAGgGQAGgIAIAAgAJbgZQAAgFAKgDQAKgDANAAQAKAAAAAIQAAAGgFATQgFASAAAKQAAAJAIAAQAKAAAJgNQAIgMAAgYQAAgDgBgDQgBgCAAgCQAAgFAKgDQAKgDANAAQALAAAAAIQAAADgDALQgEARgFAcQgJAzgKAWQgRAmgkAAQgRAAgLgJQgMgJAAgPQAAgQAKgKQAIgIAIAAQADAAAAADQAAABgBADQgCADAAAEQAAAOARAAQAPAAAJgVQAGgOAEgcQgSASgbAAQgLAAgIgHQgHgGAAgKQAAgLAFgSQAFgRAAgEQAAgDgBgDQgBgCAAgCgAMRgRQAAgHgHAAQgHAAgHAKQgHAKAAAMQALgDAJgIQAIgIAAgGgAG0AaQgBgEAAgFQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAJAAQAMAAAKgIQAGgEABAAQAEAAAAAEQAAADgHAHQgRASgYAAQgWAAgNgKQgGgFgEgHQAAABAAAAQgQAUgWAAQgNAAgHgHQgIgGAAgKQAAgKAFgNQAFgNAAgFQAAgJgHAAQgJAAgKASQgEAIgEAPQgFAQAAAIQAAAGgGAAQgVACgFAAQgGAAAAgHQAAgFAHgbQAGgaAAgIQAAgDgBgDQgBgCAAgCQAAgFAKgDQAKgDANAAQAKAAAAAIQAAAFgCAIQAGgHAKgGQANgIAMAAQAXAAAAATQAAAHgEANQgFAOAAAGQAAALAKAAQAFAAAGgHQABgBABAAQACgCABAAQAEAAAAAEQAAAEgEAFQgCgFgBgGgAH6gRQAAgHgHAAQgHAAgHAKQgHAKAAAMQALgDAJgIQAIgIAAgGgADKAaQAAgDAAgDQAAgWAQgRQATgSAdAAQAQAAALAKQAKAJAAAQQAAAZgPARQgQATgbAAQgUAAgLgLQgFgEgDgGQgPAUgXAAQgLAAgHgIIgFgHQgQAPgWAAQggAAAAgjQAAgZAQgRQAQgRAZAAQAPAAAHAFQAIghAAgRQAAgPgLAAQgEAAAAgDQAAgFAKgGQAKgGANAAQALAAAHAGQAHAHAAALQAAAMgNApQgMApAAATQAAAGADAEQADADAEAAQAGAAAFgHQABAAAAgBQADgCABAAQAFAAAAAEQAAAEgFAGQgDgFgBgHgAETADQgMgEAAgHQAAgFADgDIACgEQAAgCgDAAQgDAAgGAEQgOALAAAWQAAAKAFAGQAGAGAIAAQAJAAAGgHQAFgHAAgJQAAgIgGgDgACKgXQgLAAgHATQgGAOAAAQQAAAMAKAAQAKAAAFgOQADgGADgMQADgMAAgIQAAgJgKAAgAAAgMQgGAXAAAKQAAANALAAQAEAAAMgKQAEgDACAAQAEAAAAAEQAAACgDAEQgHAJgMAIQgNAKgNAAQgPAAgIgJQgIgHAAgNQAAgKAFgQQAFgPAAgHQAAgCgEgBQgFgBAAgDQAAgCACgDQABgEADAAQAKAAAMgJQAJgIAHgLQADgGAEAAQAFAAAAAFQAAAGgEARQAAAEABABQACABAHAAQAEAAAAAEQAAAKgHAAQgKAAgCAJgAiZAbQgBgEAAgDQAAgWARgRQASgSAdAAQARAAAKAKQALAJAAAQQAAAZgQARQgQATgaAAQgUAAgMgLQgFgEgDgGQgOAUgYAAQgMAAgIgHQgHgGAAgKQAAgKAFgNQAFgNAAgFQAAgJgHAAQgKAAgJASQgEAIgFAPQgEAQAAAIQAAAGgHAAQgUACgFAAQgGAAAAgHQAAgFAGgbQAGgaAAgIQAAgDgBgDQgBgCAAgCQAAgFALgDQAJgDAOAAQAKAAAAAIQAAAFgCAIQAGgHAKgGQANgIALAAQAXAAAAATQAAAHgEANQgEAOAAAGQAAALAKAAQAFAAAGgHQABAAAAAAQACgDACAAQAEAAAAAEQAAAEgFAGQgCgFgBgGgAhQADQgMgEAAgHQAAgFACgDIACgEQAAgCgDAAQgCAAgGAEQgPAMAAAVQAAAKAGAGQAFAGAJAAQAIAAAGgHQAGgHAAgJQAAgIgGgDgAlfAfQAGgEABAAQAEAAAAAEQAAAEgHAGQgRASgYAAQgWAAgNgKQgOgLAAgVQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAJAAQALAAALgIgAn+h6QAPAAAAAQQAAAPgOAQQgNAOgGAAQgFAAAAgEQAAgCAFgIQAFgJAAgIQAAgDgBgEQgCgEAAgDQAAgHAEgEQAEgFAIAAgAnrAyQAAAGgGAAQgVACgEAAQgHAAAAgHQAAgFAHgbQAGgaAAgIQAAgDgBgDQgBgCAAgCQAAgFAKgDQAKgDANAAQALAAAAAIQAAADgCAIQAKgSAQAAQAOAAAAAOQAAAJgFAHQgGAHgJAAQgGAAgDgDQgDgDAAgFQgFADgFAJQgFAIgEAPQgEAQAAAIgAorAfQAGgEABAAQAEAAAAAEQAAADgGAHQgTASgXAAQgWAAgNgKQgOgLAAgVQAAgWARgPQARgRAdAAQAeAAAAAWQAAANgOAKQgOAKgWACQAAAIAGAFQAGAGAJAAQAMAAAKgIgAlugRQAAgHgHAAQgHAAgHAKQgHAKAAAMQALgDAJgIQAIgIAAgGgAtEh8QgRAAgPATQgOASAAASQAAAPAMAAQAEAAAGgDQACAAAAAEQAAAIgKAKQgNAMgPAAQgNAAgJgJQgJgKAAgPQAAgkAggZQAdgXAlAAQAVAAANAKQANALAAATQAAAXgMAlQgNAlAAAMQAAAGAEAEQADADAEAAQARAAAQgZQAIgMAHgYQAGgVAAgJIgBgKQAAgGAPgHQAMgFAGAAQALAAAAALQAAAKgKAlQgLAkAAAKQAAAPAMAAQAUAAAUgqQAMgdAAgkQAAgcgTAAQgFAAAAgFQAAgGAJgIQALgIANAAQAdAAAAAfQAAAmgeA9QgPAegTATQgWAVgUAAQgPAAgKgKQgKgKgCgQQgcAkgiAAQgQAAgJgKQgJgJAAgQQAAgUARgrQARgtAAgcQAAgMgNAAgAo6gRQAAgHgHAAQgHAAgHAKQgHAKAAAMQALgDAJgIQAIgIAAgGg");
	this.shape_1.setTransform(97.375,18.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,194.8,37.7);


(lib.Since_50_1971 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Since
	this.instance = new lib.HealthPoint_Sinceai("synched",0);
	this.instance.setTransform(-68.15,2.15,1.27,1.27,0,0,0,18.2,5.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// 1971
	this.instance_1 = new lib.HealthPoint_1971ai("synched",0);
	this.instance_1.setTransform(61.6,2,1.27,1.27,0,0,0,13.6,5.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// 50
	this.instance_2 = new lib.HealthPoint_50onlyai("synched",0);
	this.instance_2.setTransform(0.1,0.05,0.55,0.55,0,0,0,73,60.9);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Since_50_1971, new cjs.Rectangle(-91.2,-33.4,169.9,66.9), null);


(lib.HP_logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HealthPointLogoai("synched",0);
	this.instance.setTransform(-0.05,0,1,1,0,0,0,154.3,30);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HP_logo, new cjs.Rectangle(-154.3,-30,308.70000000000005,60), null);


(lib.HEAD3 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.instance = new lib.HEAD1_300x600ai("synched",0);
	this.instance.setTransform(-13.5,-27.45,2.33,2.33,0,0,0,-5.8,-1.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD3, new cjs.Rectangle(-128.6,-122.8,257.4,199.8), null);


(lib.HEAD2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.HEAD_NotDoneai("synched",0);
	this.instance.setTransform(0.05,-0.05,1.44,1.44,0,0,0,97.4,18.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.HEAD2, new cjs.Rectangle(-140.2,-27.1,280.4,54.2), null);


// stage content:
(lib.HP_notdone_300x600 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,147];
	// timeline functions:
	this.frame_0 = function() {
		if(!this.alreadyyExecuted){
		this.alreadyyExecuted=true;
			this.clickthru_btn.on("click", function(evt){
		  window.open(clickTag, "_blank");
		});
		} else {
		gotoAndPlay(2);
		}
	}
	this.frame_147 = function() {
		//if(!this.alreadyExecuted){
		//this.alreadyExecuted=true;
		//this.loopNum=1;
		//} else {
		//this.loopNum++;
		//if(this.loopNum==2){
		this.stop();
		//}
		//}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(147).call(this.frame_147).wait(2));

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,2,0,3).p("EgXWguyMAutAAAMAAABdlMgutAAAg");
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(149));

	// HEAD1
	this.instance = new lib.HEAD1();
	this.instance.setTransform(150,150);
	this.instance.shadow = new cjs.Shadow("#333333",3,3,12);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(54).to({y:121.85},10).to({_off:true},83).wait(2));

	// HEAD2
	this.instance_1 = new lib.HEAD2();
	this.instance_1.setTransform(150,314);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(64).to({_off:false},0).to({_off:true},83).wait(2));

	// HEAD3
	this.instance_2 = new lib.HEAD3();
	this.instance_2.setTransform(150,169.05);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(147).to({_off:false},0).wait(2));

	// Since 50 1971
	this.instance_3 = new lib.Since_50_1971();
	this.instance_3.setTransform(156.3,351.65);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(147).to({_off:false},0).wait(2));

	// logo
	this.instance_4 = new lib.HP_logo();
	this.instance_4.setTransform(151.25,494.35,0.86,0.86,0,0,0,0.5,0.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(149));

	// CTA
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#79232F").s().p("AgCAiIAVgiIgVghIASAAIAVAhIgVAigAgkAiIAVgiIgVghIATAAIAUAhIgUAig");
	this.shape_1.setTransform(207.325,553.975);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#79232F").s().p("AgdAiQgMgMAAgVQAAgSALgNQAMgPAVAAQATAAALAOQAJAMAAASIgBAKIg4AAQABAIAHAFQAHADAJAAQANAAALgDIAEATQgNAFgTAAQgVAAgNgMgAAQgJQAAgHgCgEQgFgHgIAAQgHAAgEAHQgEAEgBAHIAfAAIAAAAg");
	this.shape_2.setTransform(194.875,554.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#79232F").s().p("AgaAtIAAg6IAAgdIAXAAIABAQIABAAQACgJAHgEQAGgFAHAAIAGAAIAAAaIgHAAQgQAAgDANIAAAFIAAAtg");
	this.shape_3.setTransform(187.075,554);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#79232F").s().p("AggAiQgNgMAAgWQAAgTANgOQANgMAUAAQAUAAANAMQAMANAAAUQAAAWgPAMQgMAMgTAAQgUAAgMgMgAgNgRQgEAHAAAKQAAALAFAIQAFAHAHAAQAIAAAFgHQAEgHABgMQAAgKgFgHQgEgJgJAAQgIAAgFAJg");
	this.shape_4.setTransform(178.15,554.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#79232F").s().p("AAoAtIAAgvQAAgUgNAAQgJAAgDAKQgCADAAADIAAAzIgZAAIAAgwQAAgTgNAAQgJAAgEAKIgBAGIAAAzIgaAAIAAg7IgBgcIAXAAIABAMIABAAQAJgOARAAQARAAAHAPQAFgGAGgEQAIgFAJAAQANAAAIAJQAJAKAAATIAAAzg");
	this.shape_5.setTransform(165.225,554);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#79232F").s().p("AAPAtIAAgwQAAgTgOAAQgKAAgDALIgBAGIAAAyIgbAAIAAg7IgBgcIAXAAIABAMIABAAQAKgOAQAAQAPAAAIAJQAJAKAAATIAAAzg");
	this.shape_6.setTransform(148.65,554);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#79232F").s().p("AgaAtIAAg6IAAgdIAXAAIABAQIABAAQACgJAHgEQAGgFAHAAIAGAAIAAAaIgHAAQgQAAgDANIAAAFIAAAtg");
	this.shape_7.setTransform(140.375,554);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#79232F").s().p("AggAmQgHgIAAgLQAAgQAOgJQAOgIAXABIAAgCQAAgMgPAAQgOAAgLAIIgFgSQAOgIATAAQAnAAAAAmIAAAeIABAVIgYAAIgCgJIAAAAQgJALgQAAQgMAAgJgIgAgMAQQAAALALgBQAEABAEgDQAEgDABgFIAAgEIAAgKIgBAAQgXAAAAAOg");
	this.shape_8.setTransform(131.625,554.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#79232F").s().p("AgdAiQgMgMAAgVQAAgSALgNQAMgPAVAAQATAAALAOQAJAMAAASIgBAKIg4AAQABAIAHAFQAHADAJAAQANAAALgDIAEATQgNAFgTAAQgVAAgNgMgAAQgJQAAgHgCgEQgFgHgIAAQgHAAgEAHQgEAEgBAHIAfAAIAAAAg");
	this.shape_9.setTransform(122.375,554.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#79232F").s().p("AglA9IAAh5IAcAAIAABiIAvAAIAAAXg");
	this.shape_10.setTransform(113.425,552.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]},147).wait(2));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_0 = new cjs.Graphics().p("A3bVGMAAAgqLMAu3AAAMAAAAqLg");
	var mask_graphics_54 = new cjs.Graphics().p("A3bVGMAAAgqLMAu3AAAMAAAAqLg");
	var mask_graphics_55 = new cjs.Graphics().p("A3bUhMAAAgpBMAu3AAAMAAAApBg");
	var mask_graphics_56 = new cjs.Graphics().p("A3bT9MAAAgn5MAu3AAAMAAAAn5g");
	var mask_graphics_57 = new cjs.Graphics().p("A3bTYMAAAgmvMAu3AAAMAAAAmvg");
	var mask_graphics_58 = new cjs.Graphics().p("A3bS0MAAAglnMAu3AAAMAAAAlng");
	var mask_graphics_59 = new cjs.Graphics().p("A3bSPMAAAgkdMAu3AAAMAAAAkdg");
	var mask_graphics_60 = new cjs.Graphics().p("A3bRrMAAAgjVMAu3AAAMAAAAjVg");
	var mask_graphics_61 = new cjs.Graphics().p("A3bRGMAAAgiLMAu3AAAMAAAAiLg");
	var mask_graphics_62 = new cjs.Graphics().p("A3bQiMAAAghCMAu3AAAMAAAAhCg");
	var mask_graphics_63 = new cjs.Graphics().p("A3bP9IAA/5MAu3AAAIAAf5g");
	var mask_graphics_64 = new cjs.Graphics().p("A3bPYIAA+vMAu3AAAIAAevg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:mask_graphics_0,x:150,y:135}).wait(54).to({graphics:mask_graphics_54,x:150,y:135}).wait(1).to({graphics:mask_graphics_55,x:150,y:131.3467}).wait(1).to({graphics:mask_graphics_56,x:150,y:127.6935}).wait(1).to({graphics:mask_graphics_57,x:150,y:124.0402}).wait(1).to({graphics:mask_graphics_58,x:150,y:120.387}).wait(1).to({graphics:mask_graphics_59,x:150,y:116.7337}).wait(1).to({graphics:mask_graphics_60,x:150,y:113.0805}).wait(1).to({graphics:mask_graphics_61,x:150,y:109.4272}).wait(1).to({graphics:mask_graphics_62,x:150,y:105.774}).wait(1).to({graphics:mask_graphics_63,x:150,y:102.1207}).wait(1).to({graphics:mask_graphics_64,x:150,y:98.4492}).wait(83).to({graphics:null,x:0,y:0}).wait(2));

	// watermelon
	this.instance_5 = new lib.watermelon();
	this.instance_5.setTransform(150,135);

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(54).to({y:109},10).to({_off:true},83).wait(2));

	// bkgd
	this.instance_6 = new lib._300x600_bkgd();
	this.instance_6.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(149));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(128,299.5,210,301);
// library properties:
lib.properties = {
	id: '0957C5EC3B874C629166840920B09671',
	width: 300,
	height: 600,
	fps: 24,
	color: "#999999",
	opacity: 1.00,
	manifest: [
		{src:"images/HP_notdone_300x600_atlas_1.jpg?1619525020950", id:"HP_notdone_300x600_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['0957C5EC3B874C629166840920B09671'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;